aaa_root:
  disabled: true
config_end: true
enable_password:
  disabled: true
ethernet_interfaces:
- name: Ethernet1
  description: L2_ISIS-SPINE1_Ethernet1
  shutdown: false
  channel_group:
    id: 1
    mode: active
  peer: ISIS-SPINE1
  peer_interface: Ethernet1
  peer_type: l3spine
hostname: ISIS-LEAF1
ip_igmp_snooping:
  globally_enabled: true
is_deployed: true
management_api_http:
  enable_https: true
  enable_vrfs:
  - name: MGMT
management_interfaces:
- name: Management1
  description: OOB_MANAGEMENT
  shutdown: false
  vrf: MGMT
  ip_address: 192.168.200.105/24
  type: oob
  gateway: 172.31.0.1
metadata:
  platform: vEOS-LAB
port_channel_interfaces:
- name: Port-Channel1
  description: L2_ISIS-SPINE1_Port-Channel1
  shutdown: false
  switchport:
    enabled: true
    mode: trunk
    trunk:
      allowed_vlan: 110,4092
service_routing_protocols_model: multi-agent
static_routes:
- vrf: MGMT
  destination_address_prefix: 0.0.0.0/0
  gateway: 172.31.0.1
- destination_address_prefix: 0.0.0.0/0
  gateway: 172.23.254.1
transceiver_qsfp_default_mode_4x10: true
vlan_interfaces:
- name: Vlan4092
  description: Inband Management
  shutdown: false
  ip_address: 172.23.254.4/24
  mtu: 1500
  type: inband_mgmt
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vlans:
- id: 110
  name: SVI_110
  tenant: L2LS_ISIS
- id: 4092
  name: INBAND_MGMT
  tenant: system
vrfs:
- name: MGMT
  ip_routing: false
