aaa_root:
  disabled: true
config_end: true
enable_password:
  disabled: true
ethernet_interfaces:
- name: Ethernet3
  description: MLAG_OSPF-SPINE2_Ethernet3
  shutdown: false
  channel_group:
    id: 3
    mode: active
  peer: OSPF-SPINE2
  peer_interface: Ethernet3
  peer_type: mlag_peer
- name: Ethernet4
  description: MLAG_OSPF-SPINE2_Ethernet4
  shutdown: false
  channel_group:
    id: 3
    mode: active
  peer: OSPF-SPINE2
  peer_interface: Ethernet4
  peer_type: mlag_peer
- name: Ethernet1
  description: L2_OSPF-LEAF1_Ethernet1
  shutdown: false
  channel_group:
    id: 1
    mode: active
  peer: OSPF-LEAF1
  peer_interface: Ethernet1
  peer_type: l2leaf
- name: Ethernet2
  description: L2_OSPF-LEAF2_Ethernet1
  shutdown: false
  channel_group:
    id: 2
    mode: active
  peer: OSPF-LEAF2
  peer_interface: Ethernet1
  peer_type: l2leaf
- name: Ethernet5
  description: P2P_DUMMY-CORE_Ethernet1/1
  shutdown: false
  mtu: 9214
  ip_address: 192.168.253.0/31
  ospf_network_point_to_point: true
  ospf_area: 0.0.0.0
  peer: DUMMY-CORE
  peer_interface: Ethernet1/1
  peer_type: other
  switchport:
    enabled: false
hostname: OSPF-SPINE1
ip_igmp_snooping:
  globally_enabled: true
ip_routing: true
ip_virtual_router_mac_address: 00:1c:73:00:00:99
is_deployed: true
loopback_interfaces:
- name: Loopback0
  description: ROUTER_ID
  shutdown: false
  ip_address: 192.168.255.1/32
  ospf_area: 0.0.0.0
management_api_http:
  enable_https: true
  enable_vrfs:
  - name: MGMT
mlag_configuration:
  domain_id: OSPF_SPINES
  local_interface: Vlan4094
  peer_address: 192.168.254.1
  peer_link: Port-Channel3
  reload_delay_mlag: '300'
  reload_delay_non_mlag: '330'
port_channel_interfaces:
- name: Port-Channel3
  description: MLAG_OSPF-SPINE2_Port-Channel3
  shutdown: false
  switchport:
    enabled: true
    mode: trunk
    trunk:
      groups:
      - MLAG
- name: Port-Channel1
  description: L2_OSPF-LEAF1_Port-Channel1
  shutdown: false
  mlag: 1
  switchport:
    enabled: true
    mode: trunk
    trunk:
      allowed_vlan: 100,4092
- name: Port-Channel2
  description: L2_OSPF-LEAF2_Port-Channel1
  shutdown: false
  mlag: 2
  switchport:
    enabled: true
    mode: trunk
    trunk:
      allowed_vlan: 100,4092
router_ospf:
  process_ids:
  - id: 100
    passive_interface_default: true
    router_id: 192.168.255.1
    bfd_enable: false
    no_passive_interfaces:
    - Vlan4094
    - Ethernet5
    max_lsa: 12000
    redistribute:
      connected:
        enabled: true
service_routing_protocols_model: multi-agent
spanning_tree:
  no_spanning_tree_vlan: '4094'
static_routes:
- vrf: MGMT
  destination_address_prefix: 0.0.0.0/0
  gateway: 172.31.0.1
transceiver_qsfp_default_mode_4x10: true
vlan_interfaces:
- name: Vlan4094
  description: MLAG
  shutdown: false
  ip_address: 192.168.254.0/31
  ospf_network_point_to_point: true
  ospf_area: 0.0.0.0
  mtu: 9214
  no_autostate: true
- name: Vlan100
  description: SVI_100
  shutdown: false
  ip_address_virtual: 10.0.100.1/24
  tenant: L2LS_OSPF
- name: Vlan4092
  description: Inband Management
  shutdown: false
  ip_address: 172.23.254.2/24
  ip_virtual_router_addresses:
  - 172.23.254.1
  mtu: 1500
  ip_attached_host_route_export:
    enabled: true
    distance: 19
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vlans:
- id: 4094
  name: MLAG
  trunk_groups:
  - MLAG
  tenant: system
- id: 100
  name: SVI_100
  tenant: L2LS_OSPF
- id: 4092
  name: INBAND_MGMT
  tenant: system
vrfs:
- name: MGMT
  ip_routing: false
