aaa_root:
  disabled: true
config_end: true
enable_password:
  disabled: true
eos_cli: "interface Loopback1003\n  description Loopback created from raw_eos_cli under l2leaf node DC1-POD1-L2LEAF2B\n\ninterface Loopback1111\n
  \ description Loopback created from raw_eos_cli under platform_settings vEOS-LAB\n"
ethernet_interfaces:
- name: Ethernet3
  description: MLAG_DC1-POD1-L2LEAF2A_Ethernet3
  shutdown: false
  channel_group:
    id: 3
    mode: active
  peer: DC1-POD1-L2LEAF2A
  peer_interface: Ethernet3
  peer_type: mlag_peer
- name: Ethernet4
  description: MLAG_DC1-POD1-L2LEAF2A_Ethernet4
  shutdown: false
  channel_group:
    id: 3
    mode: active
  peer: DC1-POD1-L2LEAF2A
  peer_interface: Ethernet4
  peer_type: mlag_peer
- name: Ethernet1
  description: L2_DC1.POD1.LEAF2A_Ethernet4
  shutdown: false
  channel_group:
    id: 1
    mode: active
  peer: DC1.POD1.LEAF2A
  peer_interface: Ethernet4
  peer_type: l3leaf
- name: Ethernet2
  description: L2_DC1-POD1-LEAF2B_Ethernet4
  shutdown: false
  channel_group:
    id: 1
    mode: active
  peer: DC1-POD1-LEAF2B
  peer_interface: Ethernet4
  peer_type: l3leaf
hostname: DC1-POD1-L2LEAF2B
ip_igmp_snooping:
  globally_enabled: true
is_deployed: true
local_users:
- name: admin
  privilege: 15
  role: network-admin
  sha512_password: $6$eJ5TvI8oru5i9e8G$R1X/SbtGTk9xoEHEBQASc7SC2nHYmi.crVgp2pXuCXwxsXEA81e4E0cXgQ6kX08fIeQzauqhv2kS.RGJFCon5/
  no_password: true
management_api_http:
  enable_https: true
  enable_vrfs:
  - name: MGMT
management_interfaces:
- name: Management1
  description: OOB_MANAGEMENT
  shutdown: false
  vrf: MGMT
  ip_address: 192.168.1.12/24
  type: oob
  gateway: 192.168.1.254
metadata:
  platform: vEOS-LAB
mlag_configuration:
  domain_id: RACK2_MLAG
  local_interface: Vlan4094
  peer_address: 172.20.110.2
  peer_link: Port-Channel3
  reload_delay_mlag: '300'
  reload_delay_non_mlag: '330'
port_channel_interfaces:
- name: Port-Channel3
  description: MLAG_DC1-POD1-L2LEAF2A_Port-Channel3
  shutdown: false
  service_profile: QOS-PROFILE
  switchport:
    enabled: true
    mode: trunk
    trunk:
      groups:
      - MLAG
- name: Port-Channel1
  description: L2_RACK2_MLAG_Port-Channel3
  shutdown: false
  mlag: 1
  service_profile: QOS-PROFILE
  switchport:
    enabled: true
    mode: trunk
    trunk:
      allowed_vlan: 110-113,1100-1102,2500,2600-2601,4085
service_routing_protocols_model: multi-agent
snmp_server:
  location: TWODC_5STAGE_CLOS DC1 DC1_POD1 DC1-POD1-L2LEAF2B
spanning_tree:
  mode: mstp
  mst_instances:
  - id: '0'
    priority: 8192
  no_spanning_tree_vlan: '4094'
static_routes:
- vrf: MGMT
  destination_address_prefix: 0.0.0.0/0
  gateway: 192.168.1.254
- destination_address_prefix: 0.0.0.0/0
  gateway: 172.21.110.1
transceiver_qsfp_default_mode_4x10: true
vlan_interfaces:
- name: Vlan4094
  description: MLAG
  shutdown: false
  ip_address: 172.20.110.3/31
  no_autostate: true
- name: Vlan4085
  description: L2LEAF_INBAND_MGMT
  shutdown: false
  ip_address: 172.21.110.6/24
  type: inband_mgmt
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vlans:
- id: 4094
  name: MLAG
  trunk_groups:
  - MLAG
  tenant: system
- id: 110
  name: Tenant_A_OP_Zone_1
  tenant: Tenant_A
- id: 111
  name: Tenant_A_OP_Zone_2
  tenant: Tenant_A
- id: 112
  name: Tenant_A_OP_Zone_3
  tenant: Tenant_A
- id: 113
  name: SVI_with_no_vxlan
  tenant: Tenant_A
- id: 1102
  name: test_svi
  tenant: Tenant_A
- id: 1100
  name: test_svi
  tenant: Tenant_A
- id: 1101
  name: test_svi
  tenant: Tenant_A
- id: 2500
  name: web-l2-vlan
  tenant: Tenant_A
- id: 2600
  name: web-l2-vlan-2
  tenant: Tenant_A
- id: 2601
  name: l2vlan_with_no_vxlan
  tenant: Tenant_A
- id: 4085
  name: L2LEAF_INBAND_MGMT
  tenant: system
vrfs:
- name: MGMT
  ip_routing: false
