aaa_root:
  disabled: true
config_end: true
enable_password:
  disabled: true
eos_cli: "interface Loopback1010\n  description Loopback created from raw_eos_cli under l3leaf defaults in DC2 POD1\n\ninterface Loopback1111\n
  \ description Loopback created from raw_eos_cli under platform_settings vEOS-LAB\n"
ethernet_interfaces:
- name: Ethernet1
  description: P2P_DC2-POD1-SPINE1_Ethernet4
  shutdown: false
  ip_address: 172.17.210.5/31
  ptp:
    enable: true
  service_profile: QOS-PROFILE
  peer: DC2-POD1-SPINE1
  peer_interface: Ethernet4
  peer_type: spine
  switchport:
    enabled: false
- name: Ethernet2
  description: P2P_DC2-POD1-SPINE2_Ethernet4
  shutdown: false
  ip_address: 172.17.210.7/31
  ptp:
    enable: true
  service_profile: QOS-PROFILE
  peer: DC2-POD1-SPINE2
  peer_interface: Ethernet4
  peer_type: spine
  switchport:
    enabled: false
- name: Ethernet3
  description: L2_DC2-POD1-L2LEAF2A_Ethernet1
  shutdown: false
  channel_group:
    id: 3
    mode: active
  peer: DC2-POD1-L2LEAF2A
  peer_interface: Ethernet1
  peer_type: l2leaf
hostname: DC2-POD1-LEAF2A
ip_igmp_snooping:
  globally_enabled: true
ip_routing: true
ip_virtual_router_mac_address: 00:1c:73:00:dc:01
is_deployed: true
local_users:
- name: admin
  privilege: 15
  role: network-admin
  sha512_password: $6$eJ5TvI8oru5i9e8G$R1X/SbtGTk9xoEHEBQASc7SC2nHYmi.crVgp2pXuCXwxsXEA81e4E0cXgQ6kX08fIeQzauqhv2kS.RGJFCon5/
  no_password: true
loopback_interfaces:
- name: Loopback0
  description: ROUTER_ID
  shutdown: false
  ip_address: 172.16.210.4/32
- name: Loopback1
  description: VXLAN_TUNNEL_SOURCE
  shutdown: false
  ip_address: 172.18.210.4/32
management_api_http:
  enable_https: true
  enable_vrfs:
  - name: MGMT
management_interfaces:
- name: Management1
  description: OOB_MANAGEMENT
  shutdown: false
  vrf: MGMT
  ip_address: 192.168.1.24/24
  type: oob
  gateway: 192.168.1.254
metadata:
  platform: vEOS-LAB
port_channel_interfaces:
- name: Port-Channel3
  description: L2_DC2-POD1-L2LEAF2A_Port-Channel1
  shutdown: false
  service_profile: QOS-PROFILE
  switchport:
    enabled: true
    mode: trunk
    trunk:
      allowed_vlan: '4092'
prefix_lists:
- name: PL-LOOPBACKS-EVPN-OVERLAY
  sequence_numbers:
  - sequence: 10
    action: permit 172.16.210.0/24 eq 32
  - sequence: 20
    action: permit 172.18.210.0/24 eq 32
- name: PL-L2LEAF-INBAND-MGMT
  sequence_numbers:
  - sequence: 10
    action: permit 172.21.210.0/24
route_maps:
- name: RM-CONN-2-BGP
  sequence_numbers:
  - sequence: 10
    type: permit
    match:
    - ip address prefix-list PL-LOOPBACKS-EVPN-OVERLAY
  - sequence: 20
    type: permit
    match:
    - ip address prefix-list PL-L2LEAF-INBAND-MGMT
router_bfd:
  multihop:
    interval: 300
    min_rx: 300
    multiplier: 3
router_bgp:
  as: '65212'
  router_id: 172.16.210.4
  maximum_paths:
    paths: 4
    ecmp: 4
  updates:
    wait_install: true
  bgp_defaults:
  - distance bgp 20 200 200
  bgp:
    default:
      ipv4_unicast: false
  peer_groups:
  - name: IPv4-UNDERLAY-PEERS
    type: ipv4
    send_community: all
    maximum_routes: 12000
  - name: EVPN-OVERLAY-PEERS
    type: evpn
    update_source: Loopback0
    bfd: true
    ebgp_multihop: 5
    send_community: all
    maximum_routes: 0
  neighbors:
  - ip_address: 172.17.210.4
    peer_group: IPv4-UNDERLAY-PEERS
    remote_as: '65210'
    peer: DC2-POD1-SPINE1
    description: DC2-POD1-SPINE1_Ethernet4
  - ip_address: 172.17.210.6
    peer_group: IPv4-UNDERLAY-PEERS
    remote_as: '65210'
    peer: DC2-POD1-SPINE2
    description: DC2-POD1-SPINE2_Ethernet4
  - ip_address: 172.16.210.3
    peer_group: EVPN-OVERLAY-PEERS
    remote_as: '65211'
    peer: DC2-POD1-LEAF1A
    description: DC2-POD1-LEAF1A_Loopback0
  redistribute:
    attached_host:
      enabled: true
    connected:
      enabled: true
      route_map: RM-CONN-2-BGP
  address_family_evpn:
    peer_groups:
    - name: EVPN-OVERLAY-PEERS
      activate: true
  address_family_rtc:
    peer_groups:
    - name: EVPN-OVERLAY-PEERS
      activate: true
  address_family_ipv4:
    peer_groups:
    - name: IPv4-UNDERLAY-PEERS
      activate: true
    - name: EVPN-OVERLAY-PEERS
      activate: false
service_routing_protocols_model: multi-agent
snmp_server:
  location: TWODC_5STAGE_CLOS DC2 DC2_POD1 DC2-POD1-LEAF2A
spanning_tree:
  mode: rstp
  rstp_priority: 4096
static_routes:
- vrf: MGMT
  destination_address_prefix: 0.0.0.0/0
  gateway: 192.168.1.254
transceiver_qsfp_default_mode_4x10: true
vlan_interfaces:
- name: Vlan4092
  description: Inband Management
  shutdown: false
  ip_address: 172.21.210.2/24
  ip_virtual_router_addresses:
  - 172.21.210.1
  ip_attached_host_route_export:
    enabled: true
    distance: 19
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vlans:
- id: 4092
  name: INBAND_MGMT
  tenant: system
vrfs:
- name: MGMT
  ip_routing: false
vxlan_interface:
  vxlan1:
    description: DC2-POD1-LEAF2A_VTEP
    vxlan:
      source_interface: Loopback1
      udp_port: 4789
