---
### group_vars/DC1_FABRIC.yml

fabric_name: 1PENN

# Set Design Type to L2ls
design:
  type: l2ls

# Ansible connectivity definitions
# eAPI connectivity via HTTPS is specified (as opposed to network_cli via SSH)
ansible_connection: ansible.netcommon.httpapi
# Specifies that we are indeed using Arista EOS
ansible_network_os: arista.eos.eos
# This user/password must exist on the switches to enable Ansible access
ansible_user: admin
ansible_password: admin
# User escalation (to enter enable mode)
ansible_become: true
ansible_become_method: enable
# Use SSL (HTTPS)
ansible_httpapi_use_ssl: true
# Do not try to validate certs
ansible_httpapi_validate_certs: false

# Spine Switches
l3spine:
  defaults:
    platform: 7050SX3
    # Spanning Tree
    spanning_tree_mode: mstp
    spanning_tree_priority: 4096
    # Router ID
    loopback_ipv4_pool: 10.10.1.0/24
    # MLAG
    mlag_peer_vlan: 4094
    mlag_peer_ipv4_pool: 169.254.0.0/31
    mlag_peer_l3_vlan: 4094
    mlag_peer_l3_ipv4_pool: 169.254.0.0/31
    virtual_router_mac_address: 00:1c:73:00:dc:01
    mlag_interfaces: [Ethernet49, Ethernet50]
  node_groups:
    - group: SPLINES
      nodes:
        - name: SPLINE1
          id: 1
          mgmt_ip: 172.100.100.101/24
        - name: SPLINE2
          id: 2
          mgmt_ip: 172.100.100.102/24

# IDF - Leaf Switches
leaf:
  defaults:
    platform: 720XP
    mlag_peer_ipv4_pool: 192.168.0.0/24
    spanning_tree_mode: mstp
    spanning_tree_priority: 57344
    inband_mgmt_subnet: 11.11.11.0/24
    inband_mgmt_vlan: 700
    inband_mgmt_vrf: IB_MGMT

  node_groups:
    - group: 36West
      mlag: false
      mlag_interfaces: [Ethernet58, Ethernet59]
      # ptp
      ptp:
        enabled: true
      # filter:
      #   tags: [ "110", "120", "130" ]
      nodes:
        - name: 36WestIDF
          id: 1
          uplink_interfaces: [Ethernet49, Ethernet50]
          uplink_switches: [SPLINE1, SPLINE2]
          uplink_switch_interfaces: [Ethernet1, Ethernet1]
    - group: 36East
      mlag: true
      mlag_interfaces: [Ethernet58, Ethernet59]
      # ptp
      ptp:
        enabled: true
      # filter:
      #   tags: [ "110", "120", "130" ]
      nodes:
        - name: 36EastIDF-A
          id: 3
          uplink_interfaces: [Ethernet49]
          uplink_switches: [SPLINE1]
          uplink_switch_interfaces: [Ethernet2]
        - name: 36EastIDF-B
          id: 4
          uplink_interfaces: [Ethernet50]
          uplink_switches: [SPLINE2]
          uplink_switch_interfaces: [Ethernet2]
    - group: 36EastIDF_Members
      mlag: false
      # ptp
      ptp:
        enabled: true
      uplink_interfaces: [Ethernet51, Ethernet52]
      uplink_switches: [36EastIDF-A, 36EastIDF-B]
      # filter:
      #   tags: [ "110", "120", "130" ]
      nodes:
        - name: 36EastIDF-Member1
          id: 5
          mgmt_ip: 172.100.100.103/24
          uplink_switch_interfaces: [Ethernet51, Ethernet51]
        - name: 36EastIDF-Member2
          id: 6
          mgmt_ip: 172.100.100.104/24
          uplink_switch_interfaces: [Ethernet52, Ethernet52]
        - name: 36EastIDF-Member3
          id: 7
          mgmt_ip: 172.100.100.104/24
          uplink_interfaces: [Ethernet53, Ethernet54]
          uplink_switches: [36EastIDF-Member1, 36EastIDF-Member2]
          uplink_switch_interfaces: [Ethernet53, Ethernet53]
    - group: 37West
      mlag: true
      mlag_interfaces: [Ethernet58, Ethernet59]
      # filter:
      #   tags: [ "110", "120", "130" ]
      nodes:
        - name: 37WestIDF-A
          id: 8
          mgmt_ip: 172.100.100.103/24
          uplink_interfaces: [Ethernet49, Ethernet50]
          uplink_switches: [SPLINE1, SPLINE2]
          uplink_switch_interfaces: [Ethernet3, Ethernet3]
        - name: 37WestIDF-B
          id: 9
          mgmt_ip: 172.100.100.103/24
          uplink_interfaces: [Ethernet49, Ethernet50]
          uplink_switches: [SPLINE1, SPLINE2]
          uplink_switch_interfaces: [Ethernet4, Ethernet4]

#### Override for vEOS/cEOS Lab Caveats ####
p2p_uplinks_mtu: 1500

# Underlay Routing Protocol
underlay_routing_protocol: ospf

# Multicast
underlay_multicast: true
underlay_multicast_rps:
  - rp: 1.1.1.1
    groups:
      - 224.0.0.0/10

#### WAN/Core Edge Links ####
# core_interfaces:
#   p2p_links:
#     - ip: [ 10.0.0.3/31, 10.0.0.2/31 ]
#       nodes: [ SPLINE1, WAN ]
#       interfaces: [ Ethernet52/1, Ethernet1/1 ]
#       include_in_underlay_protocol: true
#     - ip: [ 10.0.0.5/31, 10.0.0.4/31 ]
#       nodes: [ SPLINE2, WAN ]
#       interfaces: [ Ethernet52/1, Ethernet1/1 ]
#       include_in_underlay_protocol: true
