aaa_root:
  disabled: true
config_end: true
daemon_terminattr:
  cvaddrs:
  - 192.168.200.11:9910
  cvauth:
    method: key
    key: telarista
  cvvrf: MGMT
  disable_aaa: false
  ingestexclude: /Sysdb/cell/1/agent,/Sysdb/cell/2/agent
  smashexcludes: ale,flexCounter,hardware,kni,pulse,strata
enable_password:
  disabled: true
ethernet_interfaces:
- name: Ethernet3
  description: MLAG_DC1-L2LEAF2A_Ethernet3
  shutdown: false
  channel_group:
    id: 3
    mode: active
  peer: DC1-L2LEAF2A
  peer_interface: Ethernet3
  peer_type: mlag_peer
- name: Ethernet4
  description: MLAG_DC1-L2LEAF2A_Ethernet4
  shutdown: false
  channel_group:
    id: 3
    mode: active
  peer: DC1-L2LEAF2A
  peer_interface: Ethernet4
  peer_type: mlag_peer
- name: Ethernet1
  description: L2_DC1-SVC3A_Ethernet8
  shutdown: false
  channel_group:
    id: 1
    mode: active
  peer: DC1-SVC3A
  peer_interface: Ethernet8
  peer_type: l3leaf
- name: Ethernet2
  description: L2_DC1-SVC3B_Ethernet8
  shutdown: false
  channel_group:
    id: 1
    mode: active
  peer: DC1-SVC3B
  peer_interface: Ethernet8
  peer_type: l3leaf
hostname: DC1-L2LEAF2B
ip_igmp_snooping:
  globally_enabled: true
  vlans:
  - id: 120
    enabled: false
ip_name_servers:
- ip_address: 192.168.200.5
  vrf: MGMT
- ip_address: 8.8.8.8
  vrf: MGMT
is_deployed: true
local_users:
- name: admin
  privilege: 15
  role: network-admin
  no_password: true
- name: cvpadmin
  privilege: 15
  role: network-admin
  sha512_password: $6$rZKcbIZ7iWGAWTUM$TCgDn1KcavS0s.OV8lacMTUkxTByfzcGlFlYUWroxYuU7M/9bIodhRO7nXGzMweUxvbk8mJmQl8Bh44cRktUj.
management_api_http:
  enable_https: true
  enable_vrfs:
  - name: MGMT
management_interfaces:
- name: Management1
  description: OOB_MANAGEMENT
  shutdown: false
  vrf: MGMT
  ip_address: 192.168.200.114/24
  type: oob
  gateway: 192.168.200.5
metadata:
  platform: vEOS-LAB
mlag_configuration:
  domain_id: DC1_L2LEAF2
  local_interface: Vlan4094
  peer_address: 10.255.252.16
  peer_address_heartbeat:
    peer_ip: 192.168.200.113
    vrf: MGMT
  dual_primary_detection_delay: 5
  peer_link: Port-Channel3
  reload_delay_mlag: '300'
  reload_delay_non_mlag: '330'
ntp:
  local_interface:
    name: Management1
    vrf: MGMT
  servers:
  - name: 192.168.200.5
    preferred: true
    vrf: MGMT
port_channel_interfaces:
- name: Port-Channel3
  description: MLAG_DC1-L2LEAF2A_Port-Channel3
  shutdown: false
  switchport:
    enabled: true
    mode: trunk
    trunk:
      groups:
      - MLAG
- name: Port-Channel1
  description: L2_DC1_SVC3_Port-Channel7
  shutdown: false
  mlag: 1
  switchport:
    enabled: true
    mode: trunk
    trunk:
      allowed_vlan: 110-111,120-121,130-131,140-141,150,160-161,210-211,250,310-311,350
service_routing_protocols_model: multi-agent
spanning_tree:
  mode: mstp
  mst_instances:
  - id: '0'
    priority: 16384
  no_spanning_tree_vlan: '4094'
static_routes:
- vrf: MGMT
  destination_address_prefix: 0.0.0.0/0
  gateway: 192.168.200.5
transceiver_qsfp_default_mode_4x10: true
vlan_interfaces:
- name: Vlan4094
  description: MLAG
  shutdown: false
  ip_address: 10.255.252.17/31
  mtu: 1500
  no_autostate: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vlans:
- id: 4094
  name: MLAG
  trunk_groups:
  - MLAG
  tenant: system
- id: 130
  name: Tenant_A_APP_Zone_1
  tenant: Tenant_A
- id: 131
  name: Tenant_A_APP_Zone_2
  tenant: Tenant_A
- id: 140
  name: Tenant_A_DB_BZone_1
  tenant: Tenant_A
- id: 141
  name: Tenant_A_DB_Zone_2
  tenant: Tenant_A
- id: 110
  name: Tenant_A_OP_Zone_1
  tenant: Tenant_A
- id: 111
  name: Tenant_A_OP_Zone_2
  tenant: Tenant_A
- id: 150
  name: Tenant_A_WAN_Zone_1
  tenant: Tenant_A
- id: 120
  name: Tenant_A_WEB_Zone_1
  tenant: Tenant_A
- id: 121
  name: Tenant_A_WEBZone_2
  tenant: Tenant_A
- id: 160
  name: Tenant_A_VMOTION
  tenant: Tenant_A
- id: 161
  name: Tenant_A_NFS
  tenant: Tenant_A
- id: 210
  name: Tenant_B_OP_Zone_1
  tenant: Tenant_B
- id: 211
  name: Tenant_B_OP_Zone_2
  tenant: Tenant_B
- id: 250
  name: Tenant_B_WAN_Zone_1
  tenant: Tenant_B
- id: 310
  name: Tenant_C_OP_Zone_1
  tenant: Tenant_C
- id: 311
  name: Tenant_C_OP_Zone_2
  tenant: Tenant_C
- id: 350
  name: Tenant_C_WAN_Zone_1
  tenant: Tenant_C
vrfs:
- name: MGMT
  ip_routing: false
