aaa_root:
  disabled: true
config_end: true
daemon_terminattr:
  cvaddrs:
  - 192.168.200.11:9910
  cvauth:
    method: key
    key: telarista
  cvvrf: MGMT
  disable_aaa: false
  ingestexclude: /Sysdb/cell/1/agent,/Sysdb/cell/2/agent
  smashexcludes: ale,flexCounter,hardware,kni,pulse,strata
enable_password:
  disabled: true
ethernet_interfaces:
- name: Ethernet1
  description: L2_DC1-LEAF2A_Ethernet7
  shutdown: false
  channel_group:
    id: 1
    mode: active
  peer: DC1-LEAF2A
  peer_interface: Ethernet7
  peer_type: l3leaf
- name: Ethernet2
  description: L2_DC1-LEAF2B_Ethernet7
  shutdown: false
  channel_group:
    id: 1
    mode: active
  peer: DC1-LEAF2B
  peer_interface: Ethernet7
  peer_type: l3leaf
hostname: DC1-L2LEAF1A
ip_igmp_snooping:
  globally_enabled: true
  vlans:
  - id: 120
    enabled: false
ip_name_servers:
- ip_address: 192.168.200.5
  vrf: MGMT
- ip_address: 8.8.8.8
  vrf: MGMT
is_deployed: true
local_users:
- name: admin
  privilege: 15
  role: network-admin
  no_password: true
- name: cvpadmin
  privilege: 15
  role: network-admin
  sha512_password: $6$rZKcbIZ7iWGAWTUM$TCgDn1KcavS0s.OV8lacMTUkxTByfzcGlFlYUWroxYuU7M/9bIodhRO7nXGzMweUxvbk8mJmQl8Bh44cRktUj.
management_api_http:
  enable_https: true
  enable_vrfs:
  - name: MGMT
management_interfaces:
- name: Management1
  description: OOB_MANAGEMENT
  shutdown: false
  vrf: MGMT
  ip_address: 192.168.200.112/24
  type: oob
  gateway: 192.168.200.5
metadata:
  platform: vEOS-LAB
ntp:
  local_interface:
    name: Management1
    vrf: MGMT
  servers:
  - name: 192.168.200.5
    preferred: true
    vrf: MGMT
port_channel_interfaces:
- name: Port-Channel1
  description: L2_DC1_LEAF2_Port-Channel7
  shutdown: false
  switchport:
    enabled: true
    mode: trunk
    trunk:
      allowed_vlan: 110-111,120-121,130-131,160-161
service_routing_protocols_model: multi-agent
spanning_tree:
  mode: mstp
  mst_instances:
  - id: '0'
    priority: 16384
static_routes:
- vrf: MGMT
  destination_address_prefix: 0.0.0.0/0
  gateway: 192.168.200.5
transceiver_qsfp_default_mode_4x10: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vlans:
- id: 130
  name: Tenant_A_APP_Zone_1
  tenant: Tenant_A
- id: 131
  name: Tenant_A_APP_Zone_2
  tenant: Tenant_A
- id: 110
  name: Tenant_A_OP_Zone_1
  tenant: Tenant_A
- id: 111
  name: Tenant_A_OP_Zone_2
  tenant: Tenant_A
- id: 120
  name: Tenant_A_WEB_Zone_1
  tenant: Tenant_A
- id: 121
  name: Tenant_A_WEBZone_2
  tenant: Tenant_A
- id: 160
  name: Tenant_A_VMOTION
  tenant: Tenant_A
- id: 161
  name: Tenant_A_NFS
  tenant: Tenant_A
vrfs:
- name: MGMT
  ip_routing: false
