aaa_root:
  disabled: true
config_end: true
daemon_terminattr:
  cvaddrs:
  - 192.168.200.11:9910
  cvauth:
    method: key
    key: telarista
  cvvrf: MGMT
  disable_aaa: false
  ingestexclude: /Sysdb/cell/1/agent,/Sysdb/cell/2/agent
  smashexcludes: ale,flexCounter,hardware,kni,pulse,strata
enable_password:
  disabled: true
ethernet_interfaces:
- name: Ethernet3
  description: MLAG_DC1-L2LEAF1A_Ethernet3
  shutdown: false
  channel_group:
    id: 3
    mode: active
  peer: DC1-L2LEAF1A
  peer_interface: Ethernet3
  peer_type: mlag_peer
- name: Ethernet4
  description: MLAG_DC1-L2LEAF1A_Ethernet4
  shutdown: false
  channel_group:
    id: 3
    mode: active
  peer: DC1-L2LEAF1A
  peer_interface: Ethernet4
  peer_type: mlag_peer
- name: Ethernet1
  description: CUSTOM_DC1-LEAF2A_Ethernet8
  shutdown: false
  channel_group:
    id: 1
    mode: active
  peer: DC1-LEAF2A
  peer_interface: Ethernet8
  peer_type: l3leaf
- name: Ethernet2
  description: CUSTOM_DC1-LEAF2B_Ethernet8
  shutdown: false
  channel_group:
    id: 1
    mode: active
  peer: DC1-LEAF2B
  peer_interface: Ethernet8
  peer_type: l3leaf
hostname: DC1-L2LEAF1B
ip_igmp_snooping:
  globally_enabled: true
  vlans:
  - id: 120
    enabled: false
  - id: 160
    enabled: true
  - id: 161
    enabled: false
ip_name_servers:
- ip_address: 192.168.200.5
  vrf: MGMT
- ip_address: 8.8.8.8
  vrf: MGMT
is_deployed: true
local_users:
- name: admin
  privilege: 15
  role: network-admin
  no_password: true
- name: cvpadmin
  privilege: 15
  role: network-admin
  sha512_password: $6$rZKcbIZ7iWGAWTUM$TCgDn1KcavS0s.OV8lacMTUkxTByfzcGlFlYUWroxYuU7M/9bIodhRO7nXGzMweUxvbk8mJmQl8Bh44cRktUj.
management_api_http:
  enable_https: true
  enable_vrfs:
  - name: MGMT
management_interfaces:
- name: Management1
  description: OOB_MANAGEMENT
  shutdown: false
  vrf: MGMT
  ip_address: 192.168.200.115/24
  type: oob
  gateway: 192.168.200.5
metadata:
  platform: vEOS-LAB
mlag_configuration:
  domain_id: DC1_L2LEAF1
  local_interface: Vlan4091
  peer_address: 10.255.247.14
  peer_link: Port-Channel3
  reload_delay_mlag: '300'
  reload_delay_non_mlag: '330'
ntp:
  local_interface:
    name: Management1
    vrf: MGMT
  servers:
  - name: 192.168.200.5
    preferred: true
    vrf: MGMT
port_channel_interfaces:
- name: Port-Channel3
  description: MLAG_DC1-L2LEAF1A_Port-Channel3
  shutdown: false
  switchport:
    enabled: true
    mode: trunk
    trunk:
      groups:
      - MLAG
- name: Port-Channel1
  description: CUSTOM_DC1-LEAF2A_Po7
  shutdown: false
  mlag: 1
  switchport:
    enabled: true
    mode: trunk
    trunk:
      allowed_vlan: 110-111,120-124,130-131,160-162
queue_monitor_length:
  enabled: true
  log: 5
service_routing_protocols_model: multi-agent
snmp_server:
  contact: example@example.com
  location: DC1_FABRIC rackE DC1-L2LEAF1B
spanning_tree:
  mode: mstp
  mst_instances:
  - id: '0'
    priority: 16384
  no_spanning_tree_vlan: '4091'
static_routes:
- vrf: MGMT
  destination_address_prefix: 0.0.0.0/0
  gateway: 192.168.200.5
transceiver_qsfp_default_mode_4x10: true
vlan_interfaces:
- name: Vlan4091
  description: MLAG
  shutdown: false
  ip_address: 10.255.247.15/31
  mtu: 1500
  no_autostate: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vlans:
- id: 4091
  name: MLAG
  trunk_groups:
  - MLAG
  tenant: system
- id: 130
  name: Tenant_A_APP_Zone_1
  tenant: Tenant_A
- id: 131
  name: Tenant_A_APP_Zone_2
  tenant: Tenant_A
- id: 110
  name: Tenant_A_OP_Zone_1
  tenant: Tenant_A
- id: 111
  name: Tenant_A_OP_Zone_2
  tenant: Tenant_A
- id: 120
  name: Tenant_A_WEB_Zone_1
  tenant: Tenant_A
- id: 121
  name: Tenant_A_WEBZone_2
  tenant: Tenant_A
- id: 122
  name: Tenant_a_WEB_DHCP_no_source_int_no_vrf
  tenant: Tenant_A
- id: 123
  name: Tenant_a_WEB_DHCP_source_int_no_vrf
  tenant: Tenant_A
- id: 124
  name: Tenant_a_WEB_DHCP_vrf_no_source_int
  tenant: Tenant_A
- id: 160
  name: Tenant_A_VMOTION
  tenant: Tenant_A
- id: 161
  name: Tenant_A_NFS
  tenant: Tenant_A
- id: 162
  name: Tenant_A_FTP
  tenant: Tenant_A
vrfs:
- name: MGMT
  ip_routing: false
