aaa_root:
  disabled: true
agents:
- name: KernelFib
  environment_variables:
  - name: KERNELFIB_PROGRAM_ALL_ECMP
    value: '1'
application_traffic_recognition:
  field_sets:
    ipv4_prefixes:
    - name: PFX-LOCAL-VTEP-IP
      prefix_values:
      - 192.168.131.1/32
  applications:
    ipv4_applications:
    - name: APP-CONTROL-PLANE
      src_prefix_set_name: PFX-LOCAL-VTEP-IP
  application_profiles:
  - name: IT
  - name: VOICE
  - name: VIDEO
  - name: APP-PROFILE-CONTROL-PLANE
    applications:
    - name: APP-CONTROL-PLANE
config_end: true
dps_interfaces:
- name: Dps1
  description: DPS Interface
  mtu: 9194
  ip_address: 192.168.131.1/32
  flow_tracker:
    hardware: FLOW-TRACKER
enable_password:
  disabled: true
ethernet_interfaces:
- name: Ethernet1
  description: ATT_777
  shutdown: false
  ip_address: dhcp
  dhcp_client_accept_default_route: true
  peer_type: l3_interface
  switchport:
    enabled: false
flow_tracking:
  hardware:
    trackers:
    - name: FLOW-TRACKER
      record_export:
        on_inactive_timeout: 70000
        on_interval: 300000
      exporters:
      - name: CV-TELEMETRY
        collector:
          host: 127.0.0.1
        local_interface: Loopback0
        template_interval: 3600000
    shutdown: false
hostname: autovpn-rr1
ip_extcommunity_lists:
- name: ECL-EVPN-SOO
  entries:
  - type: permit
    extcommunities: soo 192.168.31.1:0
ip_routing: true
ip_security:
  ike_policies:
  - name: AUTOVPN-IKE
    local_id: 192.168.131.1
  sa_policies:
  - name: AUTOVPN-SA
  profiles:
  - name: AUTOVPN
    ike_policy: AUTOVPN-IKE
    sa_policy: AUTOVPN-SA
    connection: start
    shared_key: ABCDEF1234567890
    dpd:
      interval: 10
      time: 50
      action: clear
    mode: transport
is_deployed: true
loopback_interfaces:
- name: Loopback0
  description: ROUTER_ID
  shutdown: false
  ip_address: 192.168.31.1/32
management_api_http:
  enable_https: true
  enable_vrfs:
  - name: MGMT
platform:
  sfe:
    data_plane_cpu_allocation_max: 2
prefix_lists:
- name: PL-LOOPBACKS-EVPN-OVERLAY
  sequence_numbers:
  - sequence: 10
    action: permit 192.168.31.0/24 eq 32
route_maps:
- name: RM-CONN-2-BGP
  sequence_numbers:
  - sequence: 10
    type: permit
    match:
    - ip address prefix-list PL-LOOPBACKS-EVPN-OVERLAY
    set:
    - extcommunity soo 192.168.31.1:0 additive
- name: RM-EVPN-EXPORT-VRF-DEFAULT
  sequence_numbers:
  - sequence: 10
    type: permit
    match:
    - extcommunity ECL-EVPN-SOO
router_bfd:
  multihop:
    interval: 300
    min_rx: 300
    multiplier: 3
router_bgp:
  as: '65000'
  router_id: 192.168.31.1
  maximum_paths:
    paths: 16
  updates:
    wait_install: true
  bgp_cluster_id: 192.168.31.1
  bgp:
    default:
      ipv4_unicast: false
  listen_ranges:
  - prefix: 192.168.130.0/24
    peer_group: WAN-OVERLAY-PEERS
    remote_as: '65000'
  peer_groups:
  - name: WAN-OVERLAY-PEERS
    type: wan
    remote_as: '65000'
    update_source: Dps1
    route_reflector_client: true
    bfd: true
    bfd_timers:
      interval: 1000
      min_rx: 1000
      multiplier: 10
    password: htm4AZe9mIQOO1uiMuGgYQ==
    send_community: all
    maximum_routes: 0
    ttl_maximum_hops: 1
  - name: WAN-RR-OVERLAY-PEERS
    type: wan
    remote_as: '65000'
    update_source: Dps1
    route_reflector_client: true
    bfd: true
    bfd_timers:
      interval: 1000
      min_rx: 1000
      multiplier: 10
    send_community: all
    maximum_routes: 0
    ttl_maximum_hops: 1
  neighbors:
  - ip_address: 192.168.131.2
    peer_group: WAN-RR-OVERLAY-PEERS
    peer: autovpn-rr2
    description: autovpn-rr2_Dps1
  redistribute:
    connected:
      enabled: true
      route_map: RM-CONN-2-BGP
  address_family_evpn:
    peer_groups:
    - name: WAN-RR-OVERLAY-PEERS
      activate: true
      encapsulation: path-selection
    - name: WAN-OVERLAY-PEERS
      activate: true
      encapsulation: path-selection
    next_hop:
      resolution_disabled: true
  address_family_ipv4:
    peer_groups:
    - name: WAN-OVERLAY-PEERS
      activate: false
    - name: WAN-RR-OVERLAY-PEERS
      activate: false
  address_family_path_selection:
    bgp:
      additional_paths:
        receive: true
        send: any
    peer_groups:
    - name: WAN-OVERLAY-PEERS
      activate: true
    - name: WAN-RR-OVERLAY-PEERS
      activate: true
  vrfs:
  - name: default
    rd: 192.168.31.1:1
    route_targets:
      import:
      - address_family: evpn
        route_targets:
        - '1:1'
      export:
      - address_family: evpn
        route_targets:
        - '1:1'
        - route-map RM-EVPN-EXPORT-VRF-DEFAULT
router_path_selection:
  peer_dynamic_source: stun
  path_groups:
  - name: MPLS
    id: 100
  - name: INET
    id: 101
    ipsec_profile: AUTOVPN
    local_interfaces:
    - name: Ethernet1
    static_peers:
    - router_ip: 192.168.131.2
      name: autovpn-rr2
      ipv4_addresses:
      - 10.8.8.8
  - name: LTE
    id: 102
  load_balance_policies:
  - name: LB-DEFAULT-AUTOVPN-POLICY-CONTROL-PLANE
    path_groups:
    - name: INET
      priority: 42
    - name: MPLS
  - name: LB-DEFAULT-AUTOVPN-POLICY-IT
    path_groups:
    - name: MPLS
    - name: INET
      priority: 2
  - name: LB-PROD-AUTOVPN-POLICY-VOICE
    path_groups:
    - name: INET
  - name: LB-PROD-AUTOVPN-POLICY-VIDEO
    path_groups:
    - name: INET
  - name: LB-PROD-AUTOVPN-POLICY-DEFAULT
    path_groups:
    - name: INET
  policies:
  - name: DEFAULT-AUTOVPN-POLICY-WITH-CP
    rules:
    - id: 10
      application_profile: APP-PROFILE-CONTROL-PLANE
      load_balance: LB-DEFAULT-AUTOVPN-POLICY-CONTROL-PLANE
    - id: 20
      application_profile: IT
      load_balance: LB-DEFAULT-AUTOVPN-POLICY-IT
  - name: PROD-AUTOVPN-POLICY
    default_match:
      load_balance: LB-PROD-AUTOVPN-POLICY-DEFAULT
    rules:
    - id: 10
      application_profile: VOICE
      load_balance: LB-PROD-AUTOVPN-POLICY-VOICE
    - id: 20
      application_profile: VIDEO
      load_balance: LB-PROD-AUTOVPN-POLICY-VIDEO
  vrfs:
  - name: default
    path_selection_policy: DEFAULT-AUTOVPN-POLICY-WITH-CP
  - name: PROD
    path_selection_policy: PROD-AUTOVPN-POLICY
  tcp_mss_ceiling:
    ipv4_segment_size: auto
service_routing_protocols_model: multi-agent
spanning_tree:
  mode: none
stun:
  server:
    local_interfaces:
    - Ethernet1
transceiver_qsfp_default_mode_4x10: false
vrfs:
- name: MGMT
  ip_routing: false
vxlan_interface:
  vxlan1:
    description: autovpn-rr1_VTEP
    vxlan:
      source_interface: Dps1
      udp_port: 4789
      vrfs:
      - name: default
        vni: 1
      - name: PROD
        vni: 42
