aaa_root:
  disabled: true
config_end: true
enable_password:
  disabled: true
ethernet_interfaces:
- name: Ethernet1
  description: P2P_AUTO_NODE_TYPE_SPINE01_Ethernet2
  shutdown: false
  mtu: 9214
  ip_address: 172.31.255.5/31
  peer: AUTO_NODE_TYPE_SPINE01
  peer_interface: Ethernet2
  peer_type: spine
  switchport:
    enabled: false
- name: Ethernet2
  description: P2P_AUTO_NODE_TYPE_SPINE02_Ethernet2
  shutdown: false
  mtu: 9214
  ip_address: 172.31.255.7/31
  peer: AUTO_NODE_TYPE_SPINE02
  peer_interface: Ethernet2
  peer_type: spine
  switchport:
    enabled: false
hostname: AUTO_NODE_TYPE_UNGROUPED_LEAF02
ip_igmp_snooping:
  globally_enabled: true
ip_routing: true
is_deployed: true
loopback_interfaces:
- name: Loopback0
  description: ROUTER_ID
  shutdown: false
  ip_address: 192.168.255.4/32
- name: Loopback1
  description: VXLAN_TUNNEL_SOURCE
  shutdown: false
  ip_address: 192.168.254.4/32
management_api_http:
  enable_https: true
  enable_vrfs:
  - name: MGMT
management_interfaces:
- name: Management1
  description: OOB_MANAGEMENT
  shutdown: false
  vrf: MGMT
  ip_address: 192.168.203.13/24
  type: oob
  gateway: 192.168.203.1
metadata:
  platform: vEOS-LAB
prefix_lists:
- name: PL-LOOPBACKS-EVPN-OVERLAY
  sequence_numbers:
  - sequence: 10
    action: permit 192.168.255.0/24 eq 32
  - sequence: 20
    action: permit 192.168.254.0/24 eq 32
route_maps:
- name: RM-CONN-2-BGP
  sequence_numbers:
  - sequence: 10
    type: permit
    match:
    - ip address prefix-list PL-LOOPBACKS-EVPN-OVERLAY
router_bfd:
  multihop:
    interval: 300
    min_rx: 300
    multiplier: 3
router_bgp:
  as: '65102'
  router_id: 192.168.255.4
  maximum_paths:
    paths: 4
    ecmp: 4
  updates:
    wait_install: true
  bgp_defaults:
  - distance bgp 20 200 200
  bgp:
    default:
      ipv4_unicast: false
  peer_groups:
  - name: IPv4-UNDERLAY-PEERS
    type: ipv4
    send_community: all
    maximum_routes: 12000
  - name: EVPN-OVERLAY-PEERS
    type: evpn
    update_source: Loopback0
    bfd: true
    ebgp_multihop: 3
    send_community: all
    maximum_routes: 0
  neighbors:
  - ip_address: 172.31.255.4
    peer_group: IPv4-UNDERLAY-PEERS
    remote_as: '65100'
    peer: AUTO_NODE_TYPE_SPINE01
    description: AUTO_NODE_TYPE_SPINE01_Ethernet2
  - ip_address: 172.31.255.6
    peer_group: IPv4-UNDERLAY-PEERS
    remote_as: '65100'
    peer: AUTO_NODE_TYPE_SPINE02
    description: AUTO_NODE_TYPE_SPINE02_Ethernet2
  - ip_address: 192.168.255.1
    peer_group: EVPN-OVERLAY-PEERS
    remote_as: '65100'
    peer: AUTO_NODE_TYPE_SPINE01
    description: AUTO_NODE_TYPE_SPINE01_Loopback0
  - ip_address: 192.168.255.2
    peer_group: EVPN-OVERLAY-PEERS
    remote_as: '65100'
    peer: AUTO_NODE_TYPE_SPINE02
    description: AUTO_NODE_TYPE_SPINE02_Loopback0
  redistribute:
    connected:
      enabled: true
      route_map: RM-CONN-2-BGP
  address_family_evpn:
    peer_groups:
    - name: EVPN-OVERLAY-PEERS
      activate: true
  address_family_ipv4:
    peer_groups:
    - name: IPv4-UNDERLAY-PEERS
      activate: true
    - name: EVPN-OVERLAY-PEERS
      activate: false
service_routing_protocols_model: multi-agent
spanning_tree:
  mode: mstp
  mst_instances:
  - id: '0'
    priority: 4096
static_routes:
- vrf: MGMT
  destination_address_prefix: 0.0.0.0/0
  gateway: 192.168.203.1
transceiver_qsfp_default_mode_4x10: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vrfs:
- name: MGMT
  ip_routing: false
vxlan_interface:
  vxlan1:
    description: AUTO_NODE_TYPE_UNGROUPED_LEAF02_VTEP
    vxlan:
      source_interface: Loopback1
      udp_port: 4789
