aaa_root:
  disabled: true
config_end: true
enable_password:
  disabled: true
ethernet_interfaces:
- name: Ethernet3
  description: MLAG_bgp-peer-groups-1_Ethernet3
  shutdown: false
  channel_group:
    id: 3
    mode: active
  peer: bgp-peer-groups-1
  peer_interface: Ethernet3
  peer_type: mlag_peer
hostname: bgp-peer-groups-2
ip_igmp_snooping:
  globally_enabled: true
ip_routing: true
is_deployed: true
loopback_interfaces:
- name: Loopback0
  description: ROUTER_ID
  shutdown: false
  ip_address: 192.168.255.112/32
- name: Loopback1
  description: VXLAN_TUNNEL_SOURCE
  shutdown: false
  ip_address: 192.168.254.111/32
management_api_http:
  enable_https: true
  enable_vrfs:
  - name: MGMT
mlag_configuration:
  domain_id: mlag
  local_interface: Vlan4094
  peer_address: 192.168.253.204
  peer_link: Port-Channel3
  reload_delay_mlag: '300'
  reload_delay_non_mlag: '330'
port_channel_interfaces:
- name: Port-Channel3
  description: MLAG_bgp-peer-groups-1_Port-Channel3
  shutdown: false
  switchport:
    enabled: true
    mode: trunk
    trunk:
      groups:
      - MLAG
prefix_lists:
- name: PL-LOOPBACKS-EVPN-OVERLAY
  sequence_numbers:
  - sequence: 10
    action: permit 192.168.255.0/24 eq 32
  - sequence: 20
    action: permit 192.168.254.0/24 eq 32
route_maps:
- name: RM-MLAG-PEER-IN
  sequence_numbers:
  - sequence: 10
    type: permit
    description: Make routes learned over MLAG Peer-link less preferred on spines to ensure optimal routing
    set:
    - origin incomplete
- name: RM-CONN-2-BGP
  sequence_numbers:
  - sequence: 10
    type: permit
    match:
    - ip address prefix-list PL-LOOPBACKS-EVPN-OVERLAY
router_bfd:
  multihop:
    interval: 300
    min_rx: 300
    multiplier: 3
router_bgp:
  as: '65001'
  router_id: 192.168.255.112
  maximum_paths:
    paths: 4
    ecmp: 4
  updates:
    wait_install: true
  bgp_cluster_id: 192.168.255.112
  bgp:
    default:
      ipv4_unicast: false
  peer_groups:
  - name: MLAG-IPv4-UNDERLAY-PEER
    type: ipv4
    remote_as: '65001'
    description: Description for mlag_ipv4_underlay_peer via structured_config
    bfd: true
    next_hop_self: true
    send_community: all
    maximum_routes: 12000
    route_map_in: RM-MLAG-PEER-IN
  - name: IPv4-UNDERLAY-PEERS
    type: ipv4
    description: Description for ipv4_underlay_peers via structured_config
    bfd: true
    send_community: all
    maximum_routes: 12000
  - name: EVPN-OVERLAY-PEERS
    type: evpn
    remote_as: '65001'
    description: Description for evpn_overlay_peers via structured_config
    update_source: Loopback0
    route_reflector_client: true
    bfd: false
    send_community: all
    maximum_routes: 0
  - name: RR-OVERLAY-PEERS
    type: mpls
    remote_as: '65001'
    description: Description for rr_overlay_peers via structured_config
    update_source: Loopback0
    bfd: false
    send_community: all
    maximum_routes: 0
  neighbors:
  - ip_address: 192.168.253.204
    peer_group: MLAG-IPv4-UNDERLAY-PEER
    peer: bgp-peer-groups-1
    description: bgp-peer-groups-1_Vlan4094
  - ip_address: 192.168.255.111
    peer_group: EVPN-OVERLAY-PEERS
    peer: bgp-peer-groups-1
    description: bgp-peer-groups-1_Loopback0
  redistribute:
    connected:
      enabled: true
      route_map: RM-CONN-2-BGP
  address_family_evpn:
    peer_groups:
    - name: EVPN-OVERLAY-PEERS
      activate: true
  address_family_ipv4:
    peer_groups:
    - name: MLAG-IPv4-UNDERLAY-PEER
      activate: true
    - name: IPv4-UNDERLAY-PEERS
      activate: true
    - name: EVPN-OVERLAY-PEERS
      activate: false
    - name: RR-OVERLAY-PEERS
      activate: false
  address_family_vpn_ipv4:
    peer_groups:
    - name: RR-OVERLAY-PEERS
      activate: true
service_routing_protocols_model: multi-agent
spanning_tree:
  no_spanning_tree_vlan: '4094'
static_routes:
- vrf: MGMT
  destination_address_prefix: 0.0.0.0/0
  gateway: 192.168.0.1
transceiver_qsfp_default_mode_4x10: true
vlan_interfaces:
- name: Vlan4094
  description: MLAG
  shutdown: false
  ip_address: 192.168.253.205/31
  mtu: 9214
  no_autostate: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vlans:
- id: 4094
  name: MLAG
  trunk_groups:
  - MLAG
  tenant: system
vrfs:
- name: MGMT
  ip_routing: false
vxlan_interface:
  vxlan1:
    description: bgp-peer-groups-2_VTEP
    vxlan:
      source_interface: Loopback1
      udp_port: 4789
      virtual_router_encapsulation_mac_address: mlag-system-id
