aaa_root:
  disabled: true
config_end: true
enable_password:
  disabled: true
ethernet_interfaces:
- name: Ethernet10
  description: MLAG_bgp-from-network-services-1_Ethernet10
  shutdown: false
  channel_group:
    id: 10
    mode: active
  peer: bgp-from-network-services-1
  peer_interface: Ethernet10
  peer_type: mlag_peer
hostname: bgp-from-network-services-2
ip_igmp_snooping:
  globally_enabled: true
ip_routing: true
is_deployed: true
loopback_interfaces:
- name: Loopback0
  description: ROUTER_ID
  shutdown: false
  ip_address: 192.0.255.2/32
management_api_http:
  enable_https: true
  enable_vrfs:
  - name: MGMT
management_interfaces:
- name: Management1
  description: OOB_MANAGEMENT
  shutdown: false
  vrf: MGMT
  ip_address: 10.1.1.2/24
  type: oob
mlag_configuration:
  domain_id: GROUP1
  local_interface: Vlan4094
  peer_address: 10.10.10.0
  peer_link: Port-Channel10
  reload_delay_mlag: '300'
  reload_delay_non_mlag: '330'
port_channel_interfaces:
- name: Port-Channel10
  description: MLAG_bgp-from-network-services-1_Port-Channel10
  shutdown: false
  switchport:
    enabled: true
    mode: trunk
    trunk:
      groups:
      - MLAG
service_routing_protocols_model: multi-agent
spanning_tree:
  mode: none
  no_spanning_tree_vlan: 4093-4094
transceiver_qsfp_default_mode_4x10: true
vlan_interfaces:
- name: Vlan4094
  description: MLAG
  shutdown: false
  ip_address: 10.10.10.1/31
  mtu: 9214
  no_autostate: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vlans:
- id: 4094
  name: MLAG
  trunk_groups:
  - MLAG
  tenant: system
vrfs:
- name: MGMT
  ip_routing: false
