aaa_root:
  disabled: true
config_end: true
enable_password:
  disabled: true
ethernet_interfaces:
- name: Ethernet1
  description: Interface description server_OLD_SW-1/2_ENDPOINT_PORT1
  shutdown: false
  channel_group:
    id: 1
    mode: active
  peer: OLD_SW-1/2
  peer_interface: Endpoint_port1
  peer_type: server
- name: Ethernet2
  description: Interface description server_OLD_SW-1/2_ENDPOINT_PORT2
  shutdown: false
  channel_group:
    id: 1
    mode: active
  peer: OLD_SW-1/2
  peer_interface: ENDPOINT_PORT2
  peer_type: server
- name: Ethernet3
  description: SERVER_OLD_SW-1/3_ENDPOINT_PORT
  shutdown: false
  channel_group:
    id: 3
    mode: active
  peer: OLD_SW-1/3
  peer_interface: ENDPOINT_PORT
  peer_type: server
- name: Ethernet4
  description: PHYSICAL_PORT_DESCRIPTION
  shutdown: false
  peer: OLD_SW-1/4
  peer_type: server
  switchport:
    enabled: true
- name: Ethernet5
  description: SERVER_OLD_SW-1/5
  shutdown: false
  channel_group:
    id: 5
    mode: active
  peer: OLD_SW-1/5
  peer_type: server
- name: Ethernet6
  description: SERVER_OLD_SW-1/5
  shutdown: false
  channel_group:
    id: 5
    mode: active
  peer: OLD_SW-1/5
  peer_type: server
- name: Ethernet7
  description: PHYSICAL_PORT_DESCRIPTION
  shutdown: false
  channel_group:
    id: 7
    mode: active
  peer: OLD_SW-1/6
  peer_type: server
- name: Ethernet8
  description: PHYSICAL_PORT_DESCRIPTION
  shutdown: false
  channel_group:
    id: 7
    mode: active
  peer: OLD_SW-1/6
  peer_type: server
- name: Ethernet9
  description: test of var set under play vars
  shutdown: false
  peer: SERVER_WITH_PLAYVAR_DESCRIPTION
  peer_type: server
  switchport:
    enabled: true
- name: Ethernet10
  description: PHYSICAL_PORT_DESCRIPTION_1
  shutdown: false
  channel_group:
    id: 10
    mode: active
  peer: OLD_SW-1/7
  peer_type: server
- name: Ethernet11
  description: PHYSICAL_PORT_DESCRIPTION_2
  shutdown: false
  channel_group:
    id: 10
    mode: active
  peer: OLD_SW-1/7
  peer_type: server
- name: Ethernet12
  description: SERVER_INDIVIDUAL_1
  shutdown: false
  channel_group:
    id: 12
    mode: active
  ptp:
    enable: true
    announce:
      interval: 0
      timeout: 3
    delay_req: -3
    sync_message:
      interval: -3
    role: master
    transport: ipv4
  service_profile: MYQOS
  spanning_tree_bpdufilter: 'True'
  spanning_tree_portfast: edge
  peer: INDIVIDUAL_1
  peer_type: server
  sflow:
    enable: false
  switchport:
    enabled: true
    mode: trunk
    trunk:
      allowed_vlan: 1,2,3,4,5,6,7,123,234
      native_vlan: 123
      native_vlan_tag: false
- name: Ethernet13
  description: SERVER_INDIVIDUAL_1
  shutdown: false
  channel_group:
    id: 12
    mode: active
  ptp:
    enable: true
    announce:
      interval: 0
      timeout: 3
    delay_req: -3
    sync_message:
      interval: -3
    role: master
    transport: ipv4
  service_profile: MYQOS
  spanning_tree_bpdufilter: 'True'
  spanning_tree_portfast: edge
  peer: INDIVIDUAL_1
  peer_type: server
  sflow:
    enable: false
  switchport:
    enabled: true
    mode: trunk
    trunk:
      allowed_vlan: 1,2,3,4,5,6,7,123,234
      native_vlan: 123
      native_vlan_tag: false
- name: Ethernet14
  description: SERVER_DOT1X_UNAUTHORIZED
  shutdown: false
  poe:
    disabled: true
  ptp:
    enable: true
    announce:
      interval: 0
      timeout: 3
    delay_req: -3
    sync_message:
      interval: -3
    role: master
    transport: ipv4
  dot1x:
    unauthorized:
      access_vlan_membership_egress: true
      native_vlan_membership_egress: true
  service_profile: MYQOS
  spanning_tree_bpdufilter: 'True'
  spanning_tree_portfast: edge
  peer: DOT1X_UNAUTHORIZED
  peer_type: server
  sflow:
    enable: false
  port_profile: INDIVIDUAL_TRUNK
  switchport:
    enabled: true
    mode: trunk
    trunk:
      allowed_vlan: 1,2,3,4,5,6,7,123,234
      native_vlan: 123
      native_vlan_tag: false
- name: Ethernet15
  description: SERVER_INDIVIDUAL_2_TRUNK_PHONE
  shutdown: false
  link_tracking_groups:
  - name: LT_GROUP1
    direction: downstream
  channel_group:
    id: 15
    mode: active
  peer: INDIVIDUAL_2_TRUNK_PHONE
  peer_type: server
  switchport:
    enabled: true
    mode: trunk phone
    trunk:
      native_vlan: 123
    phone:
      vlan: 321
- name: Ethernet16
  description: SERVER_INDIVIDUAL_2_TRUNK_PHONE
  shutdown: false
  link_tracking_groups:
  - name: LT_GROUP1
    direction: downstream
  channel_group:
    id: 15
    mode: active
  peer: INDIVIDUAL_2_TRUNK_PHONE
  peer_type: server
  switchport:
    enabled: true
    mode: trunk phone
    trunk:
      native_vlan: 123
    phone:
      vlan: 321
- name: Ethernet17
  description: SERVER_DOT1X_UNAUTHORIZED_PORT_CHANNEL
  shutdown: false
  channel_group:
    id: 17
    mode: active
  poe:
    disabled: true
  dot1x:
    unauthorized:
      access_vlan_membership_egress: true
      native_vlan_membership_egress: true
  peer: DOT1X_UNAUTHORIZED_PORT_CHANNEL
  peer_type: server
  port_profile: INDIVIDUAL_TRUNK
- name: Ethernet18
  description: SERVER_DOT1X_UNAUTHORIZED_PORT_CHANNEL
  shutdown: false
  channel_group:
    id: 17
    mode: active
  poe:
    disabled: true
  dot1x:
    unauthorized:
      access_vlan_membership_egress: true
      native_vlan_membership_egress: true
  peer: DOT1X_UNAUTHORIZED_PORT_CHANNEL
  peer_type: server
  port_profile: INDIVIDUAL_TRUNK
hostname: connected_endpoints
ip_igmp_snooping:
  globally_enabled: true
is_deployed: true
link_tracking_groups:
- name: LT_GROUP1
  recovery_delay: 300
management_api_http:
  enable_https: true
  enable_vrfs:
  - name: MGMT
metadata:
  platform: 720XP
port_channel_interfaces:
- name: Port-Channel1
  description: Port channel description server_OLD_SW-1/2_Po1_ENDPOINT_PORT_CHANNEL_INTERFACE DESCRIPTION SERVER_OLD_SW-1/2_ENDPOINT_PORT_CHANNEL
  shutdown: false
  switchport:
    enabled: true
- name: Port-Channel3
  description: SERVER_OLD_SW-1/3_ENDPOINT_PORT_CHANNEL
  shutdown: false
  switchport:
    enabled: true
- name: Port-Channel5
  description: PORT_CHANNEL_DESCRIPTION
  shutdown: false
  switchport:
    enabled: true
- name: Port-Channel7
  description: PORT_CHANNEL_DESCRIPTION
  shutdown: false
  switchport:
    enabled: true
- name: Port-Channel10
  description: PORT_CHANNEL_DESCRIPTION
  shutdown: false
  switchport:
    enabled: true
- name: Port-Channel12
  description: SERVER_INDIVIDUAL_1_INDIVIDUAL_1
  shutdown: false
  lacp_fallback_timeout: 90
  lacp_fallback_mode: individual
  switchport:
    enabled: true
- name: Port-Channel15
  description: SERVER_INDIVIDUAL_2_TRUNK_PHONE
  shutdown: false
  lacp_fallback_timeout: 90
  lacp_fallback_mode: individual
  switchport:
    enabled: true
- name: Port-Channel17
  description: SERVER_DOT1X_UNAUTHORIZED_PORT_CHANNEL
  shutdown: false
  spanning_tree_bpdufilter: 'True'
  spanning_tree_portfast: edge
  ptp:
    enable: true
    announce:
      interval: 0
      timeout: 3
    delay_req: -3
    sync_message:
      interval: -3
    role: master
    transport: ipv4
  service_profile: MYQOS
  sflow:
    enable: false
  switchport:
    enabled: true
    mode: trunk
    trunk:
      allowed_vlan: 1,2,3,4,5,6,7,123,234
      native_vlan: 123
      native_vlan_tag: false
service_routing_protocols_model: multi-agent
transceiver_qsfp_default_mode_4x10: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vrfs:
- name: MGMT
  ip_routing: false
