aaa_root:
  disabled: true
config_end: true
enable_password:
  disabled: true
hostname: core-3-isis-sr-ldp
ip_routing: true
ipv6_unicast_routing: true
is_deployed: true
loopback_interfaces:
- name: Loopback0
  description: ROUTER_ID
  shutdown: false
  ip_address: 10.0.0.3/32
  ipv6_address: 2000:1234:ffff:ffff::3/128
  mpls:
    ldp:
      interface: true
  isis_enable: CORE
  isis_passive: true
  node_segment:
    ipv4_index: 203
    ipv6_index: 203
management_api_http:
  enable_https: true
  enable_vrfs:
  - name: MGMT
mpls:
  ip: true
  ldp:
    interface_disabled_default: true
    router_id: 10.0.0.3
    shutdown: false
    transport_address_interface: Loopback0
router_isis:
  instance: CORE
  net: 49.0001.0100.0000.0003.00
  router_id: 10.0.0.3
  is_type: level-2
  log_adjacency_changes: true
  mpls_ldp_sync_default: true
  timers:
    local_convergence:
      protected_prefixes: true
      delay: 15000
  advertise:
    passive_only: true
  address_family_ipv4:
    enabled: true
    maximum_paths: 4
    fast_reroute_ti_lfa:
      mode: node-protection
  address_family_ipv6:
    enabled: true
    maximum_paths: 4
    fast_reroute_ti_lfa:
      mode: node-protection
  segment_routing_mpls:
    enabled: true
    router_id: 10.0.0.3
service_routing_protocols_model: multi-agent
spanning_tree:
  mode: none
static_routes:
- vrf: MGMT
  destination_address_prefix: 0.0.0.0/0
  gateway: 192.168.0.1
transceiver_qsfp_default_mode_4x10: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vrfs:
- name: MGMT
  ip_routing: false
