aaa_root:
  disabled: true
config_end: true
enable_password:
  disabled: true
ethernet_interfaces:
- name: Ethernet3
  description: MLAG_CUSTOM-TEMPLATES-L2LEAF1A_Ethernet3
  shutdown: false
  channel_group:
    id: 3
    mode: active
  peer: CUSTOM-TEMPLATES-L2LEAF1A
  peer_interface: Ethernet3
  peer_type: mlag_peer
- name: Ethernet4
  description: MLAG_CUSTOM-TEMPLATES-L2LEAF1A_Ethernet4
  shutdown: false
  channel_group:
    id: 3
    mode: active
  peer: CUSTOM-TEMPLATES-L2LEAF1A
  peer_interface: Ethernet4
  peer_type: mlag_peer
- name: Ethernet1
  description: TEST_CUSTOM_PREFIX_CUSTOM-TEMPLATES-L3LEAF1A_Ethernet6
  shutdown: false
  channel_group:
    id: 1
    mode: active
  peer: CUSTOM-TEMPLATES-L3LEAF1A
  peer_interface: Ethernet6
  peer_type: l3leaf
- name: Ethernet2
  description: TEST_CUSTOM_PREFIX_CUSTOM-TEMPLATES-L3LEAF1B_Ethernet6
  shutdown: false
  channel_group:
    id: 1
    mode: active
  peer: CUSTOM-TEMPLATES-L3LEAF1B
  peer_interface: Ethernet6
  peer_type: l3leaf
hostname: CUSTOM-TEMPLATES-L2LEAF1B
ip_igmp_snooping:
  globally_enabled: true
is_deployed: true
management_api_http:
  enable_https: true
  enable_vrfs:
  - name: MGMT
management_interfaces:
- name: Management1
  description: OOB_MANAGEMENT
  shutdown: false
  vrf: MGMT
  ip_address: 192.168.200.103/24
  type: oob
  gateway: 192.168.200.1
metadata:
  platform: vEOS-LAB
mlag_configuration:
  domain_id: CUSTOM_TEMPLATES_L2LEAF1
  local_interface: Vlan4094
  peer_address: 10.255.252.0
  peer_link: Port-Channel3
  reload_delay_mlag: '300'
  reload_delay_non_mlag: '330'
port_channel_interfaces:
- name: Port-Channel3
  description: MLAG_CUSTOM-TEMPLATES-L2LEAF1A_Port-Channel3
  shutdown: false
  switchport:
    enabled: true
    mode: trunk
    trunk:
      groups:
      - MLAG
- name: Port-Channel1
  description: TEST_CUSTOM_PREFIX_CUSTOM-TEMPLATES-L3LEAF1A_Po1_To_Po5_
  shutdown: false
  mlag: 1
  switchport:
    enabled: true
    mode: trunk
    trunk:
      allowed_vlan: none
service_routing_protocols_model: multi-agent
spanning_tree:
  no_spanning_tree_vlan: '4094'
static_routes:
- vrf: MGMT
  destination_address_prefix: 0.0.0.0/0
  gateway: 192.168.200.1
transceiver_qsfp_default_mode_4x10: true
vlan_interfaces:
- name: Vlan4094
  description: MLAG
  shutdown: false
  ip_address: 10.255.252.1/31
  mtu: 9214
  no_autostate: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vlans:
- id: 4094
  name: MLAG
  trunk_groups:
  - MLAG
  tenant: system
vrfs:
- name: MGMT
  ip_routing: false
