aaa_root:
  disabled: true
config_end: true
enable_password:
  disabled: true
ethernet_interfaces:
- name: Ethernet3
  description: TEST_CUSTOM_PREFIX_MLAG_PEER_CUSTOM-TEMPLATES-L3LEAF1B_Ethernet3
  shutdown: false
  channel_group:
    id: 3
    mode: active
  peer: CUSTOM-TEMPLATES-L3LEAF1B
  peer_interface: Ethernet3
  peer_type: mlag_peer
- name: Ethernet4
  description: TEST_CUSTOM_PREFIX_MLAG_PEER_CUSTOM-TEMPLATES-L3LEAF1B_Ethernet4
  shutdown: false
  channel_group:
    id: 3
    mode: active
  peer: CUSTOM-TEMPLATES-L3LEAF1B
  peer_interface: Ethernet4
  peer_type: mlag_peer
- name: Ethernet1
  description: TEST_CUSTOM_PREFIX_P2P_LINK_TO_CUSTOM-TEMPLATES-SPINE1_Ethernet1
  shutdown: false
  mtu: 9214
  ip_address: 172.31.255.21/31
  peer: CUSTOM-TEMPLATES-SPINE1
  peer_interface: Ethernet1
  peer_type: spine
  switchport:
    enabled: false
- name: Ethernet5
  description: TEST_CUSTOM_PREFIX_CUSTOM-TEMPLATES-L2LEAF1A_Ethernet1
  shutdown: false
  channel_group:
    id: 5
    mode: active
  peer: CUSTOM-TEMPLATES-L2LEAF1A
  peer_interface: Ethernet1
  peer_type: l2leaf
- name: Ethernet6
  description: TEST_CUSTOM_PREFIX_CUSTOM-TEMPLATES-L2LEAF1B_Ethernet1
  shutdown: false
  channel_group:
    id: 5
    mode: active
  peer: CUSTOM-TEMPLATES-L2LEAF1B
  peer_interface: Ethernet1
  peer_type: l2leaf
- name: Ethernet11
  description: TEST_CUSTOM_PREFIX_SERVER-1_Nic1_management
  shutdown: false
  peer: SERVER-1
  peer_interface: Nic1
  peer_type: server
  switchport:
    enabled: true
    mode: trunk
hostname: CUSTOM-TEMPLATES-L3LEAF1A
ip_igmp_snooping:
  globally_enabled: true
ip_routing: true
ip_virtual_router_mac_address: 00:dc:00:00:00:0a
is_deployed: true
loopback_interfaces:
- name: Loopback0
  description: TEST_CUSTOM_PREFIX_EVPN_Overlay_Peering_L3LEAF
  shutdown: false
  ip_address: 192.168.255.21/32
- name: Loopback1
  description: TEST_CUSTOM_PREFIX_VTEP_VXLAN_Tunnel_Source_L3LEAF
  shutdown: false
  ip_address: 192.168.254.21/32
management_api_http:
  enable_https: true
  enable_vrfs:
  - name: MGMT
management_interfaces:
- name: Management1
  description: OOB_MANAGEMENT
  shutdown: false
  vrf: MGMT
  ip_address: 192.168.200.101/24
  type: oob
  gateway: 192.168.200.1
metadata:
  platform: vEOS-LAB
mlag_configuration:
  domain_id: CUSTOM_TEMPLATES_L3LEAF1
  local_interface: Vlan4094
  peer_address: 10.255.252.11
  peer_link: Port-Channel3
  reload_delay_mlag: '300'
  reload_delay_non_mlag: '330'
port_channel_interfaces:
- name: Port-Channel3
  description: TEST_CUSTOM_PREFIX_MLAG_PEER_CUSTOM-TEMPLATES-L3LEAF1B_Eth3_Eth4_Po3
  shutdown: false
  switchport:
    enabled: true
    mode: trunk
    trunk:
      groups:
      - MLAG
- name: Port-Channel5
  description: TEST_CUSTOM_PREFIX_CUSTOM-TEMPLATES-L2LEAF1A_Po5_To_Po1_
  shutdown: false
  mlag: 5
  switchport:
    enabled: true
    mode: trunk
    trunk:
      allowed_vlan: none
prefix_lists:
- name: PL-LOOPBACKS-EVPN-OVERLAY
  sequence_numbers:
  - sequence: 10
    action: permit 192.168.255.0/24 eq 32
  - sequence: 20
    action: permit 192.168.254.0/24 eq 32
- name: PL-MLAG-PEER-VRFS
  sequence_numbers:
  - sequence: 10
    action: permit 10.255.240.10/31
route_maps:
- name: RM-MLAG-PEER-IN
  sequence_numbers:
  - sequence: 10
    type: permit
    description: Make routes learned over MLAG Peer-link less preferred on spines to ensure optimal routing
    set:
    - origin incomplete
- name: RM-CONN-2-BGP
  sequence_numbers:
  - sequence: 10
    type: permit
    match:
    - ip address prefix-list PL-LOOPBACKS-EVPN-OVERLAY
- name: RM-CONN-2-BGP-VRFS
  sequence_numbers:
  - sequence: 10
    type: deny
    match:
    - ip address prefix-list PL-MLAG-PEER-VRFS
  - sequence: 20
    type: permit
router_bfd:
  multihop:
    interval: 300
    min_rx: 300
    multiplier: 3
router_bgp:
  as: '65101'
  router_id: 192.168.255.21
  maximum_paths:
    paths: 4
    ecmp: 4
  updates:
    wait_install: true
  bgp:
    default:
      ipv4_unicast: false
  peer_groups:
  - name: MLAG-IPv4-UNDERLAY-PEER
    type: ipv4
    remote_as: '65101'
    description: CUSTOM-TEMPLATES-L3LEAF1B
    next_hop_self: true
    send_community: all
    maximum_routes: 12000
    route_map_in: RM-MLAG-PEER-IN
  - name: IPv4-UNDERLAY-PEERS
    type: ipv4
    send_community: all
    maximum_routes: 12000
  - name: EVPN-OVERLAY-PEERS
    type: evpn
    update_source: Loopback0
    bfd: true
    ebgp_multihop: 3
    send_community: all
    maximum_routes: 0
  neighbors:
  - ip_address: 10.255.251.11
    peer_group: MLAG-IPv4-UNDERLAY-PEER
    peer: CUSTOM-TEMPLATES-L3LEAF1B
    description: CUSTOM-TEMPLATES-L3LEAF1B_Vlan4093
  - ip_address: 172.31.255.20
    peer_group: IPv4-UNDERLAY-PEERS
    remote_as: '65001'
    peer: CUSTOM-TEMPLATES-SPINE1
    description: CUSTOM-TEMPLATES-SPINE1_Ethernet1
  - ip_address: 192.168.255.1
    peer_group: EVPN-OVERLAY-PEERS
    remote_as: '65001'
    peer: CUSTOM-TEMPLATES-SPINE1
    description: CUSTOM-TEMPLATES-SPINE1_Loopback0
  redistribute:
    connected:
      enabled: true
      route_map: RM-CONN-2-BGP
  vlans:
  - id: 110
    tenant: CUSTOM_TEMPLATES_TENANT
    rd: 192.168.255.21:11110
    route_targets:
      both:
      - 11110:11110
    redistribute_routes:
    - learned
  address_family_evpn:
    peer_groups:
    - name: EVPN-OVERLAY-PEERS
      activate: true
  address_family_ipv4:
    peer_groups:
    - name: MLAG-IPv4-UNDERLAY-PEER
      activate: true
    - name: IPv4-UNDERLAY-PEERS
      activate: true
    - name: EVPN-OVERLAY-PEERS
      activate: false
  vrfs:
  - name: TEST_VRF
    rd: 192.168.255.21:1
    route_targets:
      import:
      - address_family: evpn
        route_targets:
        - '1:1'
      export:
      - address_family: evpn
        route_targets:
        - '1:1'
    router_id: 192.168.255.21
    updates:
      wait_install: true
    neighbors:
    - ip_address: 10.255.240.11
      peer_group: MLAG-IPv4-UNDERLAY-PEER
      description: CUSTOM-TEMPLATES-L3LEAF1B_Vlan3000
    redistribute:
      connected:
        enabled: true
        route_map: RM-CONN-2-BGP-VRFS
service_routing_protocols_model: multi-agent
spanning_tree:
  no_spanning_tree_vlan: 4093-4094
static_routes:
- vrf: MGMT
  destination_address_prefix: 0.0.0.0/0
  gateway: 192.168.200.1
transceiver_qsfp_default_mode_4x10: true
vlan_interfaces:
- name: Vlan4093
  description: MLAG_L3
  shutdown: false
  ip_address: 10.255.251.10/31
  mtu: 9214
- name: Vlan4094
  description: MLAG
  shutdown: false
  ip_address: 10.255.252.10/31
  mtu: 9214
  no_autostate: true
- name: Vlan110
  description: Tenant_A_OP_Zone_1
  shutdown: false
  vrf: TEST_VRF
  ip_address_virtual: 10.1.10.1/24
  tenant: CUSTOM_TEMPLATES_TENANT
  tags:
  - opzone
- name: Vlan3000
  description: MLAG_L3_VRF_TEST_VRF
  shutdown: false
  vrf: TEST_VRF
  ip_address: 10.255.240.10/31
  mtu: 9214
  tenant: CUSTOM_TEMPLATES_TENANT
  type: underlay_peering
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vlans:
- id: 4093
  name: MLAG_L3
  trunk_groups:
  - MLAG
  tenant: system
- id: 4094
  name: MLAG
  trunk_groups:
  - MLAG
  tenant: system
- id: 110
  name: Tenant_A_OP_Zone_1
  tenant: CUSTOM_TEMPLATES_TENANT
- id: 3000
  name: MLAG_L3_VRF_TEST_VRF
  trunk_groups:
  - MLAG
  tenant: CUSTOM_TEMPLATES_TENANT
vrfs:
- name: MGMT
  ip_routing: false
- name: TEST_VRF
  ip_routing: true
  tenant: CUSTOM_TEMPLATES_TENANT
vxlan_interface:
  vxlan1:
    description: CUSTOM-TEMPLATES-L3LEAF1A_VTEP
    vxlan:
      source_interface: Loopback1
      udp_port: 4789
      virtual_router_encapsulation_mac_address: mlag-system-id
      vlans:
      - id: 110
        vni: 11110
      vrfs:
      - name: TEST_VRF
        vni: 1
