aaa_root:
  disabled: true
config_end: true
enable_password:
  disabled: true
ethernet_interfaces:
- name: Ethernet1
  description: TEST_CUSTOM_PREFIX_P2P_LINK_TO_CUSTOM-PYTHON_MODULES-L3LEAF1A_Ethernet3
  shutdown: false
  mtu: 9214
  ip_address: 172.31.255.25/31
  peer: CUSTOM-PYTHON_MODULES-L3LEAF1A
  peer_interface: Ethernet3
  peer_type: l3leaf
  switchport:
    enabled: false
- name: Ethernet1.1
  description: TEST_CUSTOM_PREFIX_P2P_LINK_TO_CUSTOM-PYTHON_MODULES-L3LEAF1A_Ethernet3.1 VRF TEST_VRF
  shutdown: false
  mtu: 9214
  vrf: TEST_VRF
  encapsulation_dot1q:
    vlan: 1
  ip_address: 172.16.0.25/31
  peer: CUSTOM-PYTHON_MODULES-L3LEAF1A
  peer_interface: Ethernet3.1
  peer_type: l3leaf
hostname: CUSTOM-PYTHON_MODULES-L3LEAF2
ip_igmp_snooping:
  globally_enabled: true
ip_routing: true
ip_virtual_router_mac_address: 00:dc:00:00:00:0a
is_deployed: true
loopback_interfaces:
- name: Loopback0
  description: TEST_CUSTOM_PREFIX_EVPN_Overlay_Peering_L3LEAF
  shutdown: false
  ip_address: 192.168.255.23/32
- name: Loopback1
  description: TEST_CUSTOM_PREFIX_VTEP_VXLAN_Tunnel_Source_L3LEAF
  shutdown: false
  ip_address: 192.168.254.23/32
management_api_http:
  enable_https: true
  enable_vrfs:
  - name: MGMT
metadata:
  platform: vEOS-LAB
prefix_lists:
- name: PL-LOOPBACKS-EVPN-OVERLAY
  sequence_numbers:
  - sequence: 10
    action: permit 192.168.255.0/24 eq 32
  - sequence: 20
    action: permit 192.168.254.0/24 eq 32
route_maps:
- name: RM-CONN-2-BGP
  sequence_numbers:
  - sequence: 10
    type: permit
    match:
    - ip address prefix-list PL-LOOPBACKS-EVPN-OVERLAY
router_bfd:
  multihop:
    interval: 300
    min_rx: 300
    multiplier: 3
router_bgp:
  as: '65103'
  router_id: 192.168.255.23
  maximum_paths:
    paths: 4
    ecmp: 4
  updates:
    wait_install: true
  bgp:
    default:
      ipv4_unicast: false
  peer_groups:
  - name: IPv4-UNDERLAY-PEERS
    type: ipv4
    send_community: all
    maximum_routes: 12000
  - name: EVPN-OVERLAY-PEERS
    type: evpn
    update_source: Loopback0
    bfd: true
    ebgp_multihop: 3
    send_community: all
    maximum_routes: 0
  neighbors:
  - ip_address: 172.31.255.24
    peer_group: IPv4-UNDERLAY-PEERS
    remote_as: '65101'
    peer: CUSTOM-PYTHON_MODULES-L3LEAF1A
    description: CUSTOM-PYTHON_MODULES-L3LEAF1A_Ethernet3
  redistribute:
    connected:
      enabled: true
      route_map: RM-CONN-2-BGP
  vlans:
  - id: 110
    tenant: CUSTOM_PYTHON_MODULES_TENANT
    rd: 192.168.255.23:11110
    route_targets:
      both:
      - 11110:11110
    redistribute_routes:
    - learned
  address_family_evpn:
    peer_groups:
    - name: EVPN-OVERLAY-PEERS
      activate: true
  address_family_ipv4:
    peer_groups:
    - name: IPv4-UNDERLAY-PEERS
      activate: true
    - name: EVPN-OVERLAY-PEERS
      activate: false
  vrfs:
  - name: TEST_VRF
    rd: 192.168.255.23:1
    route_targets:
      import:
      - address_family: evpn
        route_targets:
        - '1:1'
      export:
      - address_family: evpn
        route_targets:
        - '1:1'
    router_id: 192.168.255.23
    neighbors:
    - ip_address: 172.16.0.24
      peer_group: IPv4-UNDERLAY-PEERS
      remote_as: '65101'
      description: CUSTOM-PYTHON_MODULES-L3LEAF1A_Ethernet3.1_vrf_TEST_VRF
    redistribute:
      connected:
        enabled: true
service_routing_protocols_model: multi-agent
static_routes:
- vrf: MGMT
  destination_address_prefix: 0.0.0.0/0
  gateway: 192.168.200.1
transceiver_qsfp_default_mode_4x10: true
vlan_interfaces:
- name: Vlan110
  description: Tenant_A_OP_Zone_1
  shutdown: false
  vrf: TEST_VRF
  ip_address_virtual: 10.1.10.1/24
  tenant: CUSTOM_PYTHON_MODULES_TENANT
  tags:
  - opzone
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vlans:
- id: 110
  name: Tenant_A_OP_Zone_1
  tenant: CUSTOM_PYTHON_MODULES_TENANT
vrfs:
- name: MGMT
  ip_routing: false
- name: TEST_VRF
  ip_routing: true
  tenant: CUSTOM_PYTHON_MODULES_TENANT
vxlan_interface:
  vxlan1:
    description: CUSTOM-PYTHON_MODULES-L3LEAF2_VTEP
    vxlan:
      source_interface: Loopback1
      udp_port: 4789
      vlans:
      - id: 110
        vni: 11110
      vrfs:
      - name: TEST_VRF
        vni: 1
