aaa_root:
  disabled: true
agents:
- name: KernelFib
  environment_variables:
  - name: KERNELFIB_PROGRAM_ALL_ECMP
    value: '1'
application_traffic_recognition:
  field_sets:
    ipv4_prefixes:
    - name: PFX-PATHFINDERS
      prefix_values:
      - 192.168.144.1/32
  applications:
    ipv4_applications:
    - name: APP-CONTROL-PLANE
      dest_prefix_set_name: PFX-PATHFINDERS
  application_profiles:
  - name: APP-PROFILE-CONTROL-PLANE
    applications:
    - name: APP-CONTROL-PLANE
config_end: true
dps_interfaces:
- name: Dps1
  description: DPS Interface
  mtu: 9194
  ip_address: 192.168.255.1/32
  flow_tracker:
    hardware: FLOW-TRACKER
enable_password:
  disabled: true
ethernet_interfaces:
- name: Ethernet1
  description: ATT_666
  shutdown: false
  ip_address: dhcp
  dhcp_client_accept_default_route: true
  peer_type: l3_interface
  switchport:
    enabled: false
- name: Ethernet2
  description: Colt_10555
  shutdown: false
  ip_address: 172.15.5.5/31
  peer_type: l3_interface
  switchport:
    enabled: false
- name: Ethernet3
  description: Comcast-5G_AF830
  shutdown: false
  ip_address: 172.20.20.20/31
  peer_type: l3_interface
  switchport:
    enabled: false
flow_tracking:
  hardware:
    trackers:
    - name: FLOW-TRACKER
      record_export:
        on_inactive_timeout: 70000
        on_interval: 300000
      exporters:
      - name: CV-TELEMETRY
        collector:
          host: 127.0.0.1
        local_interface: Loopback0
        template_interval: 3600000
    shutdown: false
hostname: cv-pathfinder-edge-no-default-policy
ip_extcommunity_lists:
- name: ECL-EVPN-SOO
  entries:
  - type: permit
    extcommunities: soo 192.168.42.1:511
ip_routing: true
ip_security:
  ike_policies:
  - name: CP-IKE-POLICY
    local_id: 192.168.255.1
  sa_policies:
  - name: DP-SA-POLICY
    esp:
      encryption: aes256gcm128
    pfs_dh_group: 14
  - name: CP-SA-POLICY
    esp:
      encryption: aes256gcm128
    pfs_dh_group: 14
  profiles:
  - name: DP-PROFILE
    sa_policy: DP-SA-POLICY
    connection: start
    shared_key: ABCDEF1234567890666
    dpd:
      interval: 10
      time: 50
      action: clear
    mode: transport
  - name: CP-PROFILE
    ike_policy: CP-IKE-POLICY
    sa_policy: CP-SA-POLICY
    connection: start
    shared_key: ABCDEF1234567890
    dpd:
      interval: 10
      time: 50
      action: clear
    mode: transport
  key_controller:
    profile: DP-PROFILE
is_deployed: true
loopback_interfaces:
- name: Loopback0
  description: ROUTER_ID
  shutdown: false
  ip_address: 192.168.42.1/32
management_api_http:
  enable_https: true
  enable_vrfs:
  - name: MGMT
management_security:
  ssl_profiles:
  - name: STUN-DTLS
    tls_versions: '1.2'
    trust_certificate:
      certificates:
      - aristaDeviceCertProvisionerDefaultRootCA.crt
    certificate:
      file: STUN-DTLS.crt
      key: STUN-DTLS.key
metadata:
  cv_tags:
    device_tags:
    - name: Role
      value: edge
    - name: Region
      value: AVD_Land_East
    - name: Zone
      value: AVD_Land_East-ZONE
    - name: Site
      value: Site511
    interface_tags:
    - interface: Ethernet1
      tags:
      - name: Type
        value: wan
      - name: Carrier
        value: ATT
      - name: Circuit
        value: '666'
    - interface: Ethernet2
      tags:
      - name: Type
        value: wan
      - name: Carrier
        value: Colt
      - name: Circuit
        value: '10555'
    - interface: Ethernet3
      tags:
      - name: Type
        value: wan
      - name: Carrier
        value: Comcast-5G
      - name: Circuit
        value: AF830
  cv_pathfinder:
    role: edge
    region: AVD_Land_East
    zone: AVD_Land_East-ZONE
    site: Site511
    vtep_ip: 192.168.255.1
    ssl_profile: STUN-DTLS
    pathfinders:
    - vtep_ip: 192.168.144.1
    interfaces:
    - name: Ethernet1
      carrier: ATT
      circuit_id: '666'
      pathgroup: INET
    - name: Ethernet2
      carrier: Colt
      circuit_id: '10555'
      pathgroup: MPLS
    - name: Ethernet3
      carrier: Comcast-5G
      circuit_id: AF830
      pathgroup: LTE
prefix_lists:
- name: PL-LOOPBACKS-EVPN-OVERLAY
  sequence_numbers:
  - sequence: 10
    action: permit 192.168.42.0/24 eq 32
route_maps:
- name: RM-CONN-2-BGP
  sequence_numbers:
  - sequence: 10
    type: permit
    match:
    - ip address prefix-list PL-LOOPBACKS-EVPN-OVERLAY
    set:
    - extcommunity soo 192.168.42.1:511 additive
- name: RM-EVPN-SOO-IN
  sequence_numbers:
  - sequence: 10
    type: deny
    match:
    - extcommunity ECL-EVPN-SOO
  - sequence: 20
    type: permit
- name: RM-EVPN-SOO-OUT
  sequence_numbers:
  - sequence: 10
    type: permit
    set:
    - extcommunity soo 192.168.42.1:511 additive
- name: RM-EVPN-EXPORT-VRF-DEFAULT
  sequence_numbers:
  - sequence: 10
    type: permit
    match:
    - extcommunity ECL-EVPN-SOO
router_adaptive_virtual_topology:
  topology_role: edge
  region:
    name: AVD_Land_East
    id: 43
  zone:
    name: AVD_Land_East-ZONE
    id: 1
  site:
    name: Site511
    id: 511
  profiles:
  - name: DEFAULT-POLICY-DEFAULT
    load_balance_policy: LB-DEFAULT-POLICY-DEFAULT
  - name: DEFAULT-POLICY-CONTROL-PLANE
    load_balance_policy: LB-DEFAULT-POLICY-CONTROL-PLANE
  policies:
  - name: DEFAULT-POLICY
    matches:
    - application_profile: default
      avt_profile: DEFAULT-POLICY-DEFAULT
  - name: DEFAULT-POLICY-WITH-CP
    matches:
    - application_profile: APP-PROFILE-CONTROL-PLANE
      avt_profile: DEFAULT-POLICY-CONTROL-PLANE
    - application_profile: default
      avt_profile: DEFAULT-POLICY-DEFAULT
  vrfs:
  - name: PROD
    policy: DEFAULT-POLICY
    profiles:
    - name: DEFAULT-POLICY-DEFAULT
      id: 1
  - name: IT
    policy: DEFAULT-POLICY
    profiles:
    - name: DEFAULT-POLICY-DEFAULT
      id: 1
  - name: default
    policy: DEFAULT-POLICY-WITH-CP
    profiles:
    - name: DEFAULT-POLICY-CONTROL-PLANE
      id: 254
    - name: DEFAULT-POLICY-DEFAULT
      id: 1
router_bfd:
  multihop:
    interval: 300
    min_rx: 300
    multiplier: 3
router_bgp:
  as: '65000'
  router_id: 192.168.42.1
  maximum_paths:
    paths: 16
  updates:
    wait_install: true
  bgp:
    default:
      ipv4_unicast: false
  peer_groups:
  - name: WAN-OVERLAY-PEERS
    type: wan
    remote_as: '65000'
    update_source: Dps1
    bfd: true
    bfd_timers:
      interval: 1000
      min_rx: 1000
      multiplier: 10
    password: htm4AZe9mIQOO1uiMuGgYQ==
    send_community: all
    maximum_routes: 0
    ttl_maximum_hops: 42
  neighbors:
  - ip_address: 192.168.144.1
    peer_group: WAN-OVERLAY-PEERS
    peer: cv-pathfinder-pathfinder
    description: cv-pathfinder-pathfinder_Dps1
  redistribute:
    connected:
      enabled: true
      route_map: RM-CONN-2-BGP
  address_family_evpn:
    peer_groups:
    - name: WAN-OVERLAY-PEERS
      activate: true
      route_map_in: RM-EVPN-SOO-IN
      route_map_out: RM-EVPN-SOO-OUT
      encapsulation: path-selection
  address_family_ipv4:
    peer_groups:
    - name: WAN-OVERLAY-PEERS
      activate: false
  address_family_ipv4_sr_te:
    peer_groups:
    - name: WAN-OVERLAY-PEERS
      activate: true
  address_family_link_state:
    peer_groups:
    - name: WAN-OVERLAY-PEERS
      activate: true
    path_selection:
      roles:
        producer: true
  address_family_path_selection:
    bgp:
      additional_paths:
        receive: true
        send: any
    peer_groups:
    - name: WAN-OVERLAY-PEERS
      activate: true
  vrfs:
  - name: default
    rd: 192.168.42.1:1
    route_targets:
      import:
      - address_family: evpn
        route_targets:
        - '1:1'
      export:
      - address_family: evpn
        route_targets:
        - '1:1'
        - route-map RM-EVPN-EXPORT-VRF-DEFAULT
  - name: IT
    rd: 192.168.42.1:100
    route_targets:
      import:
      - address_family: evpn
        route_targets:
        - 100:100
      export:
      - address_family: evpn
        route_targets:
        - 100:100
    router_id: 192.168.42.1
    redistribute:
      connected:
        enabled: true
  - name: PROD
    rd: 192.168.42.1:42
    route_targets:
      import:
      - address_family: evpn
        route_targets:
        - '42:42'
      export:
      - address_family: evpn
        route_targets:
        - '42:42'
    router_id: 192.168.42.1
    redistribute:
      connected:
        enabled: true
router_path_selection:
  path_groups:
  - name: INET
    id: 101
    ipsec_profile: CP-PROFILE
    local_interfaces:
    - name: Ethernet1
      stun:
        server_profiles:
        - INET-cv-pathfinder-pathfinder-Ethernet1
        - INET-cv-pathfinder-pathfinder-Ethernet3
    dynamic_peers:
      enabled: true
    static_peers:
    - router_ip: 192.168.144.1
      name: cv-pathfinder-pathfinder
      ipv4_addresses:
      - 172.17.7.7
      - 10.9.9.9
  - name: MPLS
    id: 100
    ipsec_profile: CP-PROFILE
    local_interfaces:
    - name: Ethernet2
      stun:
        server_profiles:
        - MPLS-cv-pathfinder-pathfinder-Ethernet2_2
    dynamic_peers:
      enabled: true
      ipsec: false
    static_peers:
    - router_ip: 192.168.144.1
      name: cv-pathfinder-pathfinder
      ipv4_addresses:
      - 172.16.0.1
  - name: LTE
    id: 102
    ipsec_profile: CP-PROFILE
    local_interfaces:
    - name: Ethernet3
    dynamic_peers:
      enabled: true
  load_balance_policies:
  - name: LB-DEFAULT-POLICY-DEFAULT
    path_groups:
    - name: INET
    - name: LTE
    - name: MPLS
  - name: LB-DEFAULT-POLICY-CONTROL-PLANE
    path_groups:
    - name: INET
    - name: MPLS
  tcp_mss_ceiling:
    ipv4_segment_size: auto
router_traffic_engineering:
  enabled: true
service_routing_protocols_model: multi-agent
spanning_tree:
  mode: none
stun:
  client:
    server_profiles:
    - name: INET-cv-pathfinder-pathfinder-Ethernet1
      ip_address: 172.17.7.7
      ssl_profile: STUN-DTLS
    - name: INET-cv-pathfinder-pathfinder-Ethernet3
      ip_address: 10.9.9.9
      ssl_profile: STUN-DTLS
    - name: MPLS-cv-pathfinder-pathfinder-Ethernet2_2
      ip_address: 172.16.0.1
      ssl_profile: STUN-DTLS
transceiver_qsfp_default_mode_4x10: false
vrfs:
- name: MGMT
  ip_routing: false
- name: IT
  ip_routing: true
  tenant: TenantA
- name: PROD
  ip_routing: true
  tenant: TenantA
vxlan_interface:
  vxlan1:
    description: cv-pathfinder-edge-no-default-policy_VTEP
    vxlan:
      source_interface: Dps1
      udp_port: 4789
      vrfs:
      - name: default
        vni: 1
      - name: IT
        vni: 100
      - name: PROD
        vni: 42
