aaa_root:
  disabled: true
agents:
- name: KernelFib
  environment_variables:
  - name: KERNELFIB_PROGRAM_ALL_ECMP
    value: '1'
application_traffic_recognition:
  categories:
  - name: VIDEO1
    applications:
    - name: CUSTOM-APPLICATION-2
    - name: CUSTOM-DSCP-APPLICATION
    - name: microsoft-teams
  field_sets:
    l4_ports:
    - name: TCP-SRC-2
      port_values:
      - '42'
    - name: TCP-DEST-2
      port_values:
      - '666'
      - '777'
    ipv4_prefixes:
    - name: CUSTOM-SRC-PREFIX-1
      prefix_values:
      - 42.42.42.0/24
    - name: CUSTOM-DEST-PREFIX-1
      prefix_values:
      - 6.6.6.0/24
    - name: PFX-LOCAL-VTEP-IP
      prefix_values:
      - 192.168.144.1/32
  applications:
    ipv4_applications:
    - name: CUSTOM-APPLICATION-1
      src_prefix_set_name: CUSTOM-SRC-PREFIX-1
      dest_prefix_set_name: CUSTOM-DEST-PREFIX-1
      protocols:
      - tcp
    - name: CUSTOM-APPLICATION-2
      protocols:
      - tcp
      tcp_src_port_set_name: TCP-SRC-2
      tcp_dest_port_set_name: TCP-DEST-2
    - name: CUSTOM-DSCP-APPLICATION
      dscp_ranges:
      - ef
      - 12-14
      - cs6
      - '42'
    - name: APP-CONTROL-PLANE
      src_prefix_set_name: PFX-LOCAL-VTEP-IP
  application_profiles:
  - name: VIDEO
    applications:
    - name: CUSTOM-APPLICATION-1
    - name: skype
    application_transports:
    - rtp
    categories:
    - name: VIDEO1
  - name: VOICE
    applications:
    - name: CUSTOM-VOICE-APPLICATION
  - name: MPLS-ONLY
  - name: APP-PROFILE-CONTROL-PLANE
    applications:
    - name: APP-CONTROL-PLANE
config_end: true
dps_interfaces:
- name: Dps1
  description: DPS Interface
  mtu: 9194
  ip_address: 192.168.144.1/32
  flow_tracker:
    hardware: FLOW-TRACKER
enable_password:
  disabled: true
ethernet_interfaces:
- name: Ethernet1
  description: Bouygues_Telecom_777
  shutdown: false
  ip_address: 10.7.7.7/31
  peer_type: l3_interface
  switchport:
    enabled: false
- name: Ethernet2/2
  description: Colt_10000
  shutdown: false
  ip_address: 172.16.0.1/31
  peer_type: l3_interface
  switchport:
    enabled: false
- name: Ethernet3
  description: Another-ISP_999
  shutdown: false
  ip_address: 10.9.9.9/31
  peer_type: l3_interface
  switchport:
    enabled: false
flow_tracking:
  hardware:
    trackers:
    - name: FLOW-TRACKER
      record_export:
        on_inactive_timeout: 70000
        on_interval: 300000
      exporters:
      - name: CV-TELEMETRY
        collector:
          host: 127.0.0.1
        local_interface: Loopback0
        template_interval: 3600000
    shutdown: false
hostname: cv-pathfinder-pathfinder
ip_extcommunity_lists:
- name: ECL-EVPN-SOO
  entries:
  - type: permit
    extcommunities: soo 192.168.44.1:0
ip_routing: true
ip_security:
  ike_policies:
  - name: CP-IKE-POLICY
    local_id: 192.168.144.1
  sa_policies:
  - name: CP-SA-POLICY
    esp:
      encryption: aes256gcm128
    pfs_dh_group: 14
  profiles:
  - name: CP-PROFILE
    ike_policy: CP-IKE-POLICY
    sa_policy: CP-SA-POLICY
    connection: start
    shared_key: ABCDEF1234567890
    dpd:
      interval: 10
      time: 50
      action: clear
    mode: transport
is_deployed: true
loopback_interfaces:
- name: Loopback0
  description: ROUTER_ID
  shutdown: false
  ip_address: 192.168.44.1/32
management_api_http:
  enable_https: true
  enable_vrfs:
  - name: MGMT
management_security:
  ssl_profiles:
  - name: profileA
    tls_versions: '1.2'
    trust_certificate:
      certificates:
      - aristaDeviceCertProvisionerDefaultRootCA.crt
    certificate:
      file: profileA.crt
      key: profileA.key
metadata:
  cv_tags:
    device_tags:
    - name: Role
      value: pathfinder
    - name: PathfinderSet
      value: PATHFINDERS
    interface_tags:
    - interface: Ethernet1
      tags:
      - name: Type
        value: wan
      - name: Carrier
        value: Bouygues_Telecom
      - name: Circuit
        value: '777'
    - interface: Ethernet2/2
      tags:
      - name: Type
        value: wan
      - name: Carrier
        value: Colt
      - name: Circuit
        value: '10000'
    - interface: Ethernet3
      tags:
      - name: Type
        value: wan
      - name: Carrier
        value: Another-ISP
      - name: Circuit
        value: '999'
  cv_pathfinder:
    role: pathfinder
    site: Global-pathfinder-site
    vtep_ip: 192.168.144.1
    ssl_profile: profileA
    address: Somewhere under the rainbow
    interfaces:
    - name: Ethernet1
      carrier: Bouygues_Telecom
      circuit_id: '777'
      pathgroup: INET
      public_ip: 172.17.7.7
    - name: Ethernet2/2
      carrier: Colt
      circuit_id: '10000'
      pathgroup: MPLS
      public_ip: 172.16.0.1
    - name: Ethernet3
      carrier: Another-ISP
      circuit_id: '999'
      pathgroup: INET
      public_ip: 10.9.9.9
    pathgroups:
    - name: MPLS
      carriers:
      - name: Colt
      - name: ATT-MPLS
    - name: INET
      carriers:
      - name: Comcast
      - name: ATT
      - name: Bouygues_Telecom
      - name: SFR
      - name: Orange
      - name: Another-ISP
    - name: LTE
      carriers:
      - name: Comcast-5G
    - name: Equinix
    - name: Satellite
      carriers:
      - name: Inmrasat
    - name: AWS
      carriers:
      - name: AWS-1
    regions:
    - id: 42
      name: AVD_Land_West
      zones:
      - id: 1
        name: AVD_Land_West-ZONE
        sites:
        - id: 404
          name: Site404
          location:
            address: Atlantis
        - id: 405
          name: Site405
          location:
            address: El Dorado
        - id: 422
          name: Site422
          location:
            address: Somewhere
        - id: 423
          name: Site423
          location:
            address: Somewhere-warm
    - id: 43
      name: AVD_Land_East
      zones:
      - id: 1
        name: AVD_Land_East-ZONE
        sites:
        - id: 511
          name: Site511
          location:
            address: Miami
    vrfs:
    - name: default
      vni: 1
      avts:
      - id: 254
        name: DEFAULT-AVT-POLICY-CONTROL-PLANE
        pathgroups:
        - name: AWS
          preference: preferred
        - name: Equinix
          preference: alternate
        - name: INET
          preference: preferred
        - name: MPLS
          preference: preferred
        - name: Satellite
          preference: alternate
        - name: LAN_HA
          preference: preferred
        application_profiles:
        - APP-PROFILE-CONTROL-PLANE
      - id: 3
        name: DEFAULT-AVT-POLICY-VIDEO
        pathgroups:
        - name: MPLS
          preference: preferred
        - name: INET
          preference: preferred
        - name: Equinix
          preference: preferred
        - name: LAN_HA
          preference: preferred
        application_profiles:
        - VIDEO
      - id: 1
        name: DEFAULT-AVT-POLICY-DEFAULT
        pathgroups:
        - name: INET
          preference: preferred
        - name: Equinix
          preference: alternate
        - name: MPLS
          preference: alternate
        - name: LAN_HA
          preference: preferred
    - name: PROD
      vni: 42
      avts:
      - constraints:
          jitter: 42
          hop_count: lowest
        id: 2
        name: PROD-AVT-POLICY-VOICE
        pathgroups:
        - name: MPLS
          preference: preferred
        - name: INET
          preference: alternate
        - name: LAN_HA
          preference: preferred
        application_profiles:
        - VOICE
      - constraints:
          lossrate: '42.0'
        id: 4
        name: PROD-AVT-POLICY-VIDEO
        pathgroups:
        - name: MPLS
          preference: preferred
        - name: LTE
          preference: preferred
        - name: INET
          preference: alternate
        - name: LAN_HA
          preference: preferred
        application_profiles:
        - VIDEO
      - id: 5
        name: PROD-AVT-POLICY-MPLS-ONLY
        pathgroups:
        - name: MPLS
          preference: preferred
        - name: LAN_HA
          preference: preferred
        application_profiles:
        - MPLS-ONLY
      - id: 1
        name: PROD-AVT-POLICY-DEFAULT
        pathgroups:
        - name: INET
          preference: preferred
        - name: MPLS
          preference: alternate
        - name: LAN_HA
          preference: preferred
    - name: IT
      vni: 100
      avts:
      - id: 3
        name: DEFAULT-AVT-POLICY-VIDEO
        pathgroups:
        - name: MPLS
          preference: preferred
        - name: INET
          preference: preferred
        - name: Equinix
          preference: preferred
        - name: LAN_HA
          preference: preferred
        application_profiles:
        - VIDEO
      - id: 1
        name: DEFAULT-AVT-POLICY-DEFAULT
        pathgroups:
        - name: INET
          preference: preferred
        - name: Equinix
          preference: alternate
        - name: MPLS
          preference: alternate
        - name: LAN_HA
          preference: preferred
    - name: TRANSIT
      vni: 66
      avts:
      - id: 42
        name: CUSTOM-VOICE-PROFILE-NAME
        pathgroups:
        - name: MPLS
          preference: preferred
        - name: INET
          preference: alternate
        - name: LAN_HA
          preference: preferred
        application_profiles:
        - VOICE
      - id: 1
        name: TRANSIT-AVT-POLICY-DEFAULT
        pathgroups:
        - name: INET
          preference: preferred
        - name: MPLS
          preference: alternate
        - name: LAN_HA
          preference: preferred
    - name: ATTRACTED-VRF-FROM-UPLINK
      vni: 166
      avts:
      - id: 1
        name: DEFAULT-POLICY-DEFAULT
        pathgroups:
        - name: AWS
          preference: preferred
        - name: Equinix
          preference: alternate
        - name: INET
          preference: preferred
        - name: MPLS
          preference: preferred
        - name: Satellite
          preference: alternate
        - name: LAN_HA
          preference: preferred
    applications:
      profiles:
      - name: VIDEO
        builtin_applications:
        - name: skype
        user_defined_applications:
        - name: CUSTOM-APPLICATION-1
        categories:
        - category: VIDEO1
        transport_protocols:
        - rtp
      - name: VOICE
        builtin_applications:
        - name: CUSTOM-VOICE-APPLICATION
      - name: MPLS-ONLY
      - name: APP-PROFILE-CONTROL-PLANE
        user_defined_applications:
        - name: APP-CONTROL-PLANE
      categories:
        builtin_applications:
        - name: microsoft-teams
          category: VIDEO1
        user_defined_applications:
        - name: CUSTOM-APPLICATION-2
          category: VIDEO1
        - name: CUSTOM-DSCP-APPLICATION
          category: VIDEO1
platform:
  sfe:
    data_plane_cpu_allocation_max: 1
prefix_lists:
- name: PL-LOOPBACKS-EVPN-OVERLAY
  sequence_numbers:
  - sequence: 10
    action: permit 192.168.44.0/24 eq 32
route_maps:
- name: RM-CONN-2-BGP
  sequence_numbers:
  - sequence: 10
    type: permit
    match:
    - ip address prefix-list PL-LOOPBACKS-EVPN-OVERLAY
    set:
    - extcommunity soo 192.168.44.1:0 additive
- name: RM-EVPN-EXPORT-VRF-DEFAULT
  sequence_numbers:
  - sequence: 10
    type: permit
    match:
    - extcommunity ECL-EVPN-SOO
router_adaptive_virtual_topology:
  topology_role: pathfinder
  profiles:
  - name: DEFAULT-AVT-POLICY-CONTROL-PLANE
    load_balance_policy: LB-DEFAULT-AVT-POLICY-CONTROL-PLANE
  - name: DEFAULT-AVT-POLICY-VIDEO
    load_balance_policy: LB-DEFAULT-AVT-POLICY-VIDEO
  - name: DEFAULT-AVT-POLICY-DEFAULT
    load_balance_policy: LB-DEFAULT-AVT-POLICY-DEFAULT
  - name: PROD-AVT-POLICY-VOICE
    load_balance_policy: LB-PROD-AVT-POLICY-VOICE
  - name: PROD-AVT-POLICY-VIDEO
    load_balance_policy: LB-PROD-AVT-POLICY-VIDEO
  - name: PROD-AVT-POLICY-MPLS-ONLY
    load_balance_policy: LB-PROD-AVT-POLICY-MPLS-ONLY
  - name: PROD-AVT-POLICY-DEFAULT
    load_balance_policy: LB-PROD-AVT-POLICY-DEFAULT
  - name: CUSTOM-VOICE-PROFILE-NAME
    load_balance_policy: LB-CUSTOM-VOICE-PROFILE-NAME
  - name: TRANSIT-AVT-POLICY-DEFAULT
    load_balance_policy: LB-TRANSIT-AVT-POLICY-DEFAULT
  - name: DEFAULT-POLICY-DEFAULT
    load_balance_policy: LB-DEFAULT-POLICY-DEFAULT
  policies:
  - name: DEFAULT-AVT-POLICY-WITH-CP
    matches:
    - application_profile: APP-PROFILE-CONTROL-PLANE
      avt_profile: DEFAULT-AVT-POLICY-CONTROL-PLANE
    - application_profile: VIDEO
      avt_profile: DEFAULT-AVT-POLICY-VIDEO
    - application_profile: default
      avt_profile: DEFAULT-AVT-POLICY-DEFAULT
  - name: PROD-AVT-POLICY
    matches:
    - application_profile: VOICE
      avt_profile: PROD-AVT-POLICY-VOICE
    - application_profile: VIDEO
      avt_profile: PROD-AVT-POLICY-VIDEO
    - application_profile: MPLS-ONLY
      avt_profile: PROD-AVT-POLICY-MPLS-ONLY
    - application_profile: default
      avt_profile: PROD-AVT-POLICY-DEFAULT
  - name: DEFAULT-AVT-POLICY
    matches:
    - application_profile: VIDEO
      avt_profile: DEFAULT-AVT-POLICY-VIDEO
    - application_profile: default
      avt_profile: DEFAULT-AVT-POLICY-DEFAULT
  - name: TRANSIT-AVT-POLICY
    matches:
    - application_profile: VOICE
      avt_profile: CUSTOM-VOICE-PROFILE-NAME
    - application_profile: default
      avt_profile: TRANSIT-AVT-POLICY-DEFAULT
  - name: DEFAULT-POLICY
    matches:
    - application_profile: default
      avt_profile: DEFAULT-POLICY-DEFAULT
  vrfs:
  - name: default
    policy: DEFAULT-AVT-POLICY-WITH-CP
    profiles:
    - name: DEFAULT-AVT-POLICY-CONTROL-PLANE
      id: 254
    - name: DEFAULT-AVT-POLICY-VIDEO
      id: 3
    - name: DEFAULT-AVT-POLICY-DEFAULT
      id: 1
  - name: PROD
    policy: PROD-AVT-POLICY
    profiles:
    - name: PROD-AVT-POLICY-VOICE
      id: 2
    - name: PROD-AVT-POLICY-VIDEO
      id: 4
    - name: PROD-AVT-POLICY-MPLS-ONLY
      id: 5
    - name: PROD-AVT-POLICY-DEFAULT
      id: 1
  - name: IT
    policy: DEFAULT-AVT-POLICY
    profiles:
    - name: DEFAULT-AVT-POLICY-VIDEO
      id: 3
    - name: DEFAULT-AVT-POLICY-DEFAULT
      id: 1
  - name: TRANSIT
    policy: TRANSIT-AVT-POLICY
    profiles:
    - name: CUSTOM-VOICE-PROFILE-NAME
      id: 42
    - name: TRANSIT-AVT-POLICY-DEFAULT
      id: 1
  - name: ATTRACTED-VRF-FROM-UPLINK
    policy: DEFAULT-POLICY
    profiles:
    - name: DEFAULT-POLICY-DEFAULT
      id: 1
router_bfd:
  multihop:
    interval: 300
    min_rx: 300
    multiplier: 3
router_bgp:
  as: '65000'
  router_id: 192.168.44.1
  maximum_paths:
    paths: 16
  updates:
    wait_install: true
  bgp_cluster_id: 192.168.44.1
  bgp:
    default:
      ipv4_unicast: false
  listen_ranges:
  - prefix: 192.168.142.0/24
    peer_group: WAN-OVERLAY-PEERS
    remote_as: '65000'
  - prefix: 192.168.143.0/24
    peer_group: WAN-OVERLAY-PEERS
    remote_as: '65000'
  peer_groups:
  - name: IPv4-UNDERLAY-PEERS
    type: ipv4
    send_community: all
    maximum_routes: 12000
    route_map_in: RM-BGP-UNDERLAY-PEERS-IN
  - name: WAN-OVERLAY-PEERS
    type: wan
    remote_as: '65000'
    update_source: Dps1
    route_reflector_client: true
    bfd: true
    bfd_timers:
      interval: 1000
      min_rx: 1000
      multiplier: 10
    password: htm4AZe9mIQOO1uiMuGgYQ==
    send_community: all
    maximum_routes: 0
    ttl_maximum_hops: 1
  redistribute:
    connected:
      enabled: true
      route_map: RM-CONN-2-BGP
  address_family_evpn:
    peer_groups:
    - name: WAN-OVERLAY-PEERS
      activate: true
      encapsulation: path-selection
    next_hop:
      resolution_disabled: true
  address_family_ipv4:
    peer_groups:
    - name: IPv4-UNDERLAY-PEERS
      activate: true
    - name: WAN-OVERLAY-PEERS
      activate: false
  address_family_ipv4_sr_te:
    peer_groups:
    - name: WAN-OVERLAY-PEERS
      activate: true
  address_family_link_state:
    peer_groups:
    - name: WAN-OVERLAY-PEERS
      activate: true
      missing_policy:
        direction_out_action: deny
    path_selection:
      roles:
        consumer: true
        propagator: true
  address_family_path_selection:
    bgp:
      additional_paths:
        receive: true
        send: any
    peer_groups:
    - name: WAN-OVERLAY-PEERS
      activate: true
  vrfs:
  - name: default
    rd: 192.168.44.1:1
    route_targets:
      import:
      - address_family: evpn
        route_targets:
        - '1:1'
      export:
      - address_family: evpn
        route_targets:
        - '1:1'
        - route-map RM-EVPN-EXPORT-VRF-DEFAULT
router_path_selection:
  peer_dynamic_source: stun
  path_groups:
  - name: MPLS
    id: 100
    local_interfaces:
    - name: Ethernet2/2
    keepalive:
      interval: 300
      failure_threshold: 5
  - name: INET
    id: 101
    ipsec_profile: CP-PROFILE
    local_interfaces:
    - name: Ethernet1
    - name: Ethernet3
  - name: LTE
    id: 102
  - name: Equinix
    id: 103
  - name: Satellite
    id: 104
  - name: AWS
    id: 105
  - name: LAN_HA
    id: 65535
    flow_assignment: lan
  load_balance_policies:
  - name: LB-DEFAULT-AVT-POLICY-CONTROL-PLANE
    path_groups:
    - name: AWS
    - name: Equinix
      priority: 2
    - name: INET
    - name: MPLS
    - name: Satellite
      priority: 2
    - name: LAN_HA
  - name: LB-DEFAULT-AVT-POLICY-VIDEO
    path_groups:
    - name: MPLS
    - name: INET
    - name: Equinix
    - name: LAN_HA
  - name: LB-DEFAULT-AVT-POLICY-DEFAULT
    path_groups:
    - name: INET
    - name: Equinix
      priority: 2
    - name: MPLS
      priority: 4223
    - name: LAN_HA
  - name: LB-PROD-AVT-POLICY-VOICE
    lowest_hop_count: true
    jitter: 42
    path_groups:
    - name: MPLS
    - name: INET
      priority: 2
    - name: LAN_HA
  - name: LB-PROD-AVT-POLICY-VIDEO
    loss_rate: '42.0'
    path_groups:
    - name: MPLS
    - name: LTE
    - name: INET
      priority: 2
    - name: LAN_HA
  - name: LB-PROD-AVT-POLICY-MPLS-ONLY
    path_groups:
    - name: MPLS
    - name: LAN_HA
  - name: LB-PROD-AVT-POLICY-DEFAULT
    path_groups:
    - name: INET
    - name: MPLS
      priority: 2
    - name: LAN_HA
  - name: LB-CUSTOM-VOICE-PROFILE-NAME
    path_groups:
    - name: MPLS
    - name: INET
      priority: 2
    - name: LAN_HA
  - name: LB-TRANSIT-AVT-POLICY-DEFAULT
    path_groups:
    - name: INET
    - name: MPLS
      priority: 2
    - name: LAN_HA
  - name: LB-DEFAULT-POLICY-DEFAULT
    path_groups:
    - name: AWS
    - name: Equinix
      priority: 2
    - name: INET
    - name: MPLS
    - name: Satellite
      priority: 2
    - name: LAN_HA
  tcp_mss_ceiling:
    ipv4_segment_size: auto
router_traffic_engineering:
  enabled: true
service_routing_protocols_model: multi-agent
spanning_tree:
  mode: none
static_routes:
- destination_address_prefix: 0.0.0.0/0
  gateway: 10.7.7.6
stun:
  server:
    local_interfaces:
    - Ethernet1
    - Ethernet2/2
    - Ethernet3
    ssl_profile: profileA
transceiver_qsfp_default_mode_4x10: false
vrfs:
- name: MGMT
  ip_routing: false
vxlan_interface:
  vxlan1:
    description: cv-pathfinder-pathfinder_VTEP
    vxlan:
      source_interface: Dps1
      udp_port: 4789
      vrfs:
      - name: default
        vni: 1
      - name: PROD
        vni: 42
      - name: IT
        vni: 100
      - name: TRANSIT
        vni: 66
      - name: ATTRACTED-VRF-FROM-UPLINK
        vni: 166
