aaa_root:
  disabled: true
config_end: true
daemon_terminattr:
  cvaddrs:
  - myonpremcvpserver:9910
  cvauth:
    method: token
    token_file: /tmp/token
  cvvrf: MGMT
  disable_aaa: false
  ingestexclude: /Sysdb/cell/1/agent,/Sysdb/cell/2/agent
  smashexcludes: ale,flexCounter,hardware,kni,pulse,strata
enable_password:
  disabled: true
hostname: cvp-instance-ips-onprem-token
ip_igmp_snooping:
  globally_enabled: true
is_deployed: true
management_api_http:
  enable_https: true
  enable_vrfs:
  - name: MGMT
service_routing_protocols_model: multi-agent
transceiver_qsfp_default_mode_4x10: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vrfs:
- name: MGMT
  ip_routing: false
