aaa_root:
  disabled: true
config_end: true
enable_password:
  disabled: true
ethernet_interfaces:
- name: Ethernet3
  description: P2P_downlink-pools-l3leaf2_Ethernet1
  shutdown: false
  mtu: 9214
  ip_address: 10.0.2.0/31
  peer: downlink-pools-l3leaf2
  peer_interface: Ethernet1
  peer_type: l3leaf
  switchport:
    enabled: false
- name: Ethernet4
  description: P2P_downlink-pools-l3leaf2_Ethernet2
  shutdown: false
  mtu: 9214
  ip_address: 10.0.2.2/31
  peer: downlink-pools-l3leaf2
  peer_interface: Ethernet2
  peer_type: l3leaf
  switchport:
    enabled: false
- name: Ethernet5
  description: P2P_downlink-pools-l3leaf3_Ethernet2
  shutdown: false
  mtu: 9214
  ip_address: 10.0.4.0/31
  peer: downlink-pools-l3leaf3
  peer_interface: Ethernet2
  peer_type: l3leaf
  switchport:
    enabled: false
- name: Ethernet6
  description: P2P_downlink-pools-l3leaf4_Ethernet2
  shutdown: false
  mtu: 9214
  ip_address: 10.0.4.2/31
  peer: downlink-pools-l3leaf4
  peer_interface: Ethernet2
  peer_type: l3leaf
  switchport:
    enabled: false
- name: Ethernet15
  description: P2P_downlink-pools-l3leaf3_Ethernet4
  shutdown: false
  mtu: 9214
  ip_address: 10.0.4.4/31
  peer: downlink-pools-l3leaf3
  peer_interface: Ethernet4
  peer_type: l3leaf
  switchport:
    enabled: false
- name: Ethernet16
  description: P2P_downlink-pools-l3leaf4_Ethernet4
  shutdown: false
  mtu: 9214
  ip_address: 10.0.4.6/31
  peer: downlink-pools-l3leaf4
  peer_interface: Ethernet4
  peer_type: l3leaf
  switchport:
    enabled: false
hostname: downlink-pools-spine2
ip_routing: true
is_deployed: true
loopback_interfaces:
- name: Loopback0
  description: ROUTER_ID
  shutdown: false
  ip_address: 192.168.0.20/32
management_api_http:
  enable_https: true
  enable_vrfs:
  - name: MGMT
prefix_lists:
- name: PL-LOOPBACKS-EVPN-OVERLAY
  sequence_numbers:
  - sequence: 10
    action: permit 192.168.0.0/24 eq 32
route_maps:
- name: RM-CONN-2-BGP
  sequence_numbers:
  - sequence: 10
    type: permit
    match:
    - ip address prefix-list PL-LOOPBACKS-EVPN-OVERLAY
router_bfd:
  multihop:
    interval: 300
    min_rx: 300
    multiplier: 3
router_bgp:
  as: '65000'
  router_id: 192.168.0.20
  maximum_paths:
    paths: 4
    ecmp: 4
  updates:
    wait_install: true
  bgp:
    default:
      ipv4_unicast: false
  peer_groups:
  - name: IPv4-UNDERLAY-PEERS
    type: ipv4
    send_community: all
    maximum_routes: 12000
  - name: EVPN-OVERLAY-PEERS
    type: evpn
    next_hop_unchanged: true
    update_source: Loopback0
    bfd: true
    ebgp_multihop: 3
    send_community: all
    maximum_routes: 0
  neighbors:
  - ip_address: 10.0.2.1
    peer_group: IPv4-UNDERLAY-PEERS
    remote_as: '65019'
    peer: downlink-pools-l3leaf2
    description: downlink-pools-l3leaf2_Ethernet1
  - ip_address: 10.0.2.3
    peer_group: IPv4-UNDERLAY-PEERS
    remote_as: '65019'
    peer: downlink-pools-l3leaf2
    description: downlink-pools-l3leaf2_Ethernet2
  - ip_address: 10.0.4.1
    peer_group: IPv4-UNDERLAY-PEERS
    remote_as: '65029'
    peer: downlink-pools-l3leaf3
    description: downlink-pools-l3leaf3_Ethernet2
  - ip_address: 10.0.4.3
    peer_group: IPv4-UNDERLAY-PEERS
    remote_as: '65039'
    peer: downlink-pools-l3leaf4
    description: downlink-pools-l3leaf4_Ethernet2
  - ip_address: 10.0.4.5
    peer_group: IPv4-UNDERLAY-PEERS
    remote_as: '65029'
    peer: downlink-pools-l3leaf3
    description: downlink-pools-l3leaf3_Ethernet4
  - ip_address: 10.0.4.7
    peer_group: IPv4-UNDERLAY-PEERS
    remote_as: '65039'
    peer: downlink-pools-l3leaf4
    description: downlink-pools-l3leaf4_Ethernet4
  - ip_address: 192.168.1.20
    peer_group: EVPN-OVERLAY-PEERS
    remote_as: '65019'
    peer: downlink-pools-l3leaf2
    description: downlink-pools-l3leaf2_Loopback0
  - ip_address: 192.168.1.30
    peer_group: EVPN-OVERLAY-PEERS
    remote_as: '65029'
    peer: downlink-pools-l3leaf3
    description: downlink-pools-l3leaf3_Loopback0
  - ip_address: 192.168.1.40
    peer_group: EVPN-OVERLAY-PEERS
    remote_as: '65039'
    peer: downlink-pools-l3leaf4
    description: downlink-pools-l3leaf4_Loopback0
  redistribute:
    connected:
      enabled: true
      route_map: RM-CONN-2-BGP
  address_family_evpn:
    peer_groups:
    - name: EVPN-OVERLAY-PEERS
      activate: true
  address_family_ipv4:
    peer_groups:
    - name: IPv4-UNDERLAY-PEERS
      activate: true
    - name: EVPN-OVERLAY-PEERS
      activate: false
service_routing_protocols_model: multi-agent
spanning_tree:
  mode: none
transceiver_qsfp_default_mode_4x10: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vrfs:
- name: MGMT
  ip_routing: false
