aaa_root:
  disabled: true
config_end: true
enable_password:
  disabled: true
hostname: duplicate-vrfs
ip_igmp_snooping:
  globally_enabled: true
ip_routing: true
ip_virtual_router_mac_address: 00:dc:00:00:00:0a
is_deployed: true
loopback_interfaces:
- name: Loopback0
  description: ROUTER_ID
  shutdown: false
  ip_address: 192.168.255.101/32
- name: Loopback1
  description: VXLAN_TUNNEL_SOURCE
  shutdown: false
  ip_address: 192.168.254.101/32
management_api_http:
  enable_https: true
  enable_vrfs:
  - name: MGMT
prefix_lists:
- name: PL-LOOPBACKS-EVPN-OVERLAY
  sequence_numbers:
  - sequence: 10
    action: permit 192.168.255.0/24 eq 32
  - sequence: 20
    action: permit 192.168.254.0/24 eq 32
route_maps:
- name: RM-CONN-2-BGP
  sequence_numbers:
  - sequence: 10
    type: permit
    match:
    - ip address prefix-list PL-LOOPBACKS-EVPN-OVERLAY
router_bfd:
  multihop:
    interval: 300
    min_rx: 300
    multiplier: 3
router_bgp:
  as: '101'
  router_id: 192.168.255.101
  maximum_paths:
    paths: 4
    ecmp: 4
  updates:
    wait_install: true
  bgp:
    default:
      ipv4_unicast: false
  peer_groups:
  - name: IPv4-UNDERLAY-PEERS
    type: ipv4
    send_community: all
    maximum_routes: 12000
  - name: EVPN-OVERLAY-PEERS
    type: evpn
    update_source: Loopback0
    bfd: true
    ebgp_multihop: 3
    send_community: all
    maximum_routes: 0
  redistribute:
    connected:
      enabled: true
      route_map: RM-CONN-2-BGP
  vlans:
  - id: 100
    tenant: DUPLICATE_TENANT1
    rd: 192.168.255.101:10100
    route_targets:
      both:
      - 10100:10100
    redistribute_routes:
    - learned
  - id: 200
    tenant: DUPLICATE_TENANT1
    rd: 192.168.255.101:10200
    route_targets:
      both:
      - 10200:10200
    redistribute_routes:
    - learned
  address_family_evpn:
    peer_groups:
    - name: EVPN-OVERLAY-PEERS
      activate: true
  address_family_ipv4:
    peer_groups:
    - name: IPv4-UNDERLAY-PEERS
      activate: true
    - name: EVPN-OVERLAY-PEERS
      activate: false
  vrfs:
  - name: VRF1
    rd: 192.168.255.101:1
    route_targets:
      import:
      - address_family: evpn
        route_targets:
        - '1:1'
      export:
      - address_family: evpn
        route_targets:
        - '1:1'
    router_id: 192.168.255.101
    redistribute:
      connected:
        enabled: true
service_routing_protocols_model: multi-agent
transceiver_qsfp_default_mode_4x10: true
vlan_interfaces:
- name: Vlan100
  description: VLAN100
  shutdown: false
  vrf: VRF1
  ip_address_virtual: 10.0.100.1/24
  tenant: DUPLICATE_TENANT1
- name: Vlan200
  description: VLAN200
  shutdown: false
  vrf: VRF1
  ip_address_virtual: 10.0.200.1/24
  tenant: DUPLICATE_TENANT1
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vlans:
- id: 100
  name: VLAN100
  tenant: DUPLICATE_TENANT1
- id: 200
  name: VLAN200
  tenant: DUPLICATE_TENANT1
vrfs:
- name: MGMT
  ip_routing: false
- name: VRF1
  ip_routing: true
  tenant: DUPLICATE_TENANT1
vxlan_interface:
  vxlan1:
    description: duplicate-vrfs_VTEP
    vxlan:
      source_interface: Loopback1
      udp_port: 4789
      vlans:
      - id: 100
        vni: 10100
      - id: 200
        vni: 10200
      vrfs:
      - name: VRF1
        vni: 1
