aaa_root:
  disabled: true
config_end: true
enable_password:
  disabled: true
ethernet_interfaces:
- name: Ethernet1
  description: SERVER_testserver_Nic1
  shutdown: false
  peer: testserver
  peer_interface: Nic1
  peer_type: server
  switchport:
    enabled: true
    mode: trunk
    trunk:
      allowed_vlan: 1-2
hostname: filter.only_vlans_in_use
ip_igmp_snooping:
  globally_enabled: true
is_deployed: true
management_api_http:
  enable_https: true
  enable_vrfs:
  - name: MGMT
service_routing_protocols_model: multi-agent
static_routes:
- vrf: MGMT
  destination_address_prefix: 0.0.0.0/0
  gateway: 10.0.0.1
transceiver_qsfp_default_mode_4x10: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vlans:
- id: 2
  name: vlan2
  tenant: test
- id: 1
  name: vlan1
  tenant: test
vrfs:
- name: MGMT
  ip_routing: false
