aaa_root:
  disabled: true
config_end: true
enable_password:
  disabled: true
ethernet_interfaces:
- name: Ethernet1
  description: L2_flow-tracking-tests-leaf3_Ethernet31
  shutdown: false
  channel_group:
    id: 1
    mode: active
  peer: flow-tracking-tests-leaf3
  peer_interface: Ethernet31
  peer_type: l3leaf
- name: Ethernet2
  description: L2_flow-tracking-tests-leaf4_Ethernet31
  shutdown: false
  channel_group:
    id: 1
    mode: active
  peer: flow-tracking-tests-leaf4
  peer_interface: Ethernet31
  peer_type: l3leaf
flow_tracking:
  sampled:
    sample: 10000
    trackers:
    - record_export:
        on_inactive_timeout: 70000
        on_interval: 300000
      name: FLOW-TRACKER
      exporters:
      - name: CV-TELEMETRY
        collector:
          host: 127.0.0.1
        local_interface: Loopback0
        template_interval: 3600000
    shutdown: false
hostname: flow-tracking-tests-l2-leaf1
ip_igmp_snooping:
  globally_enabled: true
is_deployed: true
management_api_http:
  enable_https: true
  enable_vrfs:
  - name: MGMT
management_interfaces:
- name: Management1
  description: OOB_MANAGEMENT
  shutdown: false
  vrf: MGMT
  ip_address: 192.168.0.201/24
  type: oob
  gateway: 192.168.0.1
metadata:
  platform: vEOS-lab
port_channel_interfaces:
- name: Port-Channel1
  description: L2_flow-tracking-tests-leaf-mlag_Port-Channel31
  shutdown: false
  flow_tracker:
    sampled: FLOW-TRACKER
  switchport:
    enabled: true
    mode: trunk
    trunk:
      allowed_vlan: 11,4092
service_routing_protocols_model: multi-agent
static_routes:
- vrf: MGMT
  destination_address_prefix: 0.0.0.0/0
  gateway: 192.168.0.1
- destination_address_prefix: 0.0.0.0/0
  gateway: 10.254.254.1
transceiver_qsfp_default_mode_4x10: true
vlan_interfaces:
- name: Vlan4092
  description: Inband Management
  shutdown: false
  ip_address: 10.254.254.4/24
  mtu: 1500
  type: inband_mgmt
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vlans:
- id: 11
  name: VLAN11
  tenant: FLOW_TRACKING
- id: 4092
  name: INBAND_MGMT
  tenant: system
vrfs:
- name: MGMT
  ip_routing: false
