aaa_root:
  disabled: true
config_end: true
enable_password:
  disabled: true
ethernet_interfaces:
- name: Ethernet1
  description: L2_IGMP-QUERIER-L3LEAF1A_Ethernet1
  shutdown: false
  channel_group:
    id: 1
    mode: active
  peer: IGMP-QUERIER-L3LEAF1A
  peer_interface: Ethernet1
  peer_type: l3leaf
hostname: IGMP-QUERIER-L2LEAF1A
ip_igmp_snooping:
  globally_enabled: true
is_deployed: true
management_api_http:
  enable_https: true
  enable_vrfs:
  - name: MGMT
management_interfaces:
- name: Management1
  description: OOB_MANAGEMENT
  shutdown: false
  vrf: MGMT
  ip_address: 192.168.200.101/24
  type: oob
  gateway: 192.168.200.5
port_channel_interfaces:
- name: Port-Channel1
  description: L2_IGMP-QUERIER-L3LEAF1A_Port-Channel1
  shutdown: false
  switchport:
    enabled: true
    mode: trunk
    trunk:
      allowed_vlan: 1-3,11-12,21-23,101-103,111-113,121-123
service_routing_protocols_model: multi-agent
static_routes:
- vrf: MGMT
  destination_address_prefix: 0.0.0.0/0
  gateway: 192.168.200.5
transceiver_qsfp_default_mode_4x10: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vlans:
- id: 1
  name: VLAN_1
  tenant: Tenant_A
- id: 2
  name: VLAN_2
  tenant: Tenant_A
- id: 3
  name: VLAN_3
  tenant: Tenant_A
- id: 101
  name: VLAN_101
  tenant: Tenant_A
- id: 102
  name: VLAN_102
  tenant: Tenant_A
- id: 103
  name: VLAN_103
  tenant: Tenant_A
- id: 11
  name: VLAN_11
  tenant: Tenant_B
- id: 12
  name: VLAN_12
  tenant: Tenant_B
- id: 111
  name: VLAN_111
  tenant: Tenant_B
- id: 112
  name: VLAN_112
  tenant: Tenant_B
- id: 113
  name: VLAN_113
  tenant: Tenant_B
- id: 21
  name: VLAN_21
  tenant: Tenant_D
- id: 22
  name: VLAN_22
  tenant: Tenant_D
- id: 23
  name: VLAN_23
  tenant: Tenant_D
- id: 121
  name: VLAN_121
  tenant: Tenant_D
- id: 122
  name: VLAN_122
  tenant: Tenant_D
- id: 123
  name: VLAN_123
  tenant: Tenant_D
vrfs:
- name: MGMT
  ip_routing: false
