aaa_root:
  disabled: true
config_end: true
daemon_terminattr:
  cvaddrs:
  - apiserver.arista.io:443
  cvauth:
    method: token-secure
    token_file: /tmp/cv-onboarding-token
  cvvrf: MGMT
  disable_aaa: false
  ingestexclude: /Sysdb/cell/1/agent,/Sysdb/cell/2/agent
  smashexcludes: ale,flexCounter,hardware,kni,pulse,strata
enable_password:
  disabled: true
ethernet_interfaces:
- name: Ethernet1
  description: P2P_inband-mgmt-spine1-ztp_Ethernet1
  shutdown: false
  mtu: 9214
  ip_address: 172.16.255.1/31
  peer: inband-mgmt-spine1-ztp
  peer_interface: Ethernet1
  peer_type: spine
  switchport:
    enabled: false
- name: Ethernet21
  description: INBAND-MGMT-SUBNET_Ethernet1
  shutdown: false
  channel_group:
    id: 21
    mode: active
  peer: inband-mgmt-subnet
  peer_interface: Ethernet1
  peer_type: l2leaf
  switchport:
    enabled: true
    mode: access
    access_vlan: 101
- name: Ethernet22
  description: INBAND-MGMT-SUBNET-VRF_Ethernet1
  shutdown: false
  channel_group:
    id: 22
    mode: active
  peer: inband-mgmt-subnet-vrf
  peer_interface: Ethernet1
  peer_type: l2leaf
  switchport:
    enabled: true
    mode: access
    access_vlan: 102
- name: Ethernet23
  description: INBAND-MGMT-IP_Ethernet1
  shutdown: false
  channel_group:
    id: 23
    mode: active
  peer: inband-mgmt-ip
  peer_interface: Ethernet1
  peer_type: l2leaf
- name: Ethernet101
  description: INBAND-MGMT-MLAG-A_Ethernet1
  shutdown: false
  channel_group:
    id: 101
    mode: active
  peer: inband-mgmt-mlag-a
  peer_interface: Ethernet1
  peer_type: l2leaf
  switchport:
    enabled: true
    mode: access
    access_vlan: 101
- name: Ethernet102
  description: INBAND-MGMT-MLAG-B_Ethernet1
  shutdown: false
  channel_group:
    id: 101
    mode: active
  peer: inband-mgmt-mlag-b
  peer_interface: Ethernet1
  peer_type: l2leaf
  switchport:
    enabled: true
    mode: access
    access_vlan: 101
hostname: inband-mgmt-parent
ip_igmp_snooping:
  globally_enabled: true
ip_name_servers:
- ip_address: 1.1.1.1
  vrf: MGMT
- ip_address: 8.8.8.8
  vrf: MGMT
ip_routing: true
ip_virtual_router_mac_address: 00:1c:73:00:dc:01
is_deployed: true
loopback_interfaces:
- name: Loopback0
  description: ROUTER_ID
  shutdown: false
  ip_address: 10.0.255.1/32
- name: Loopback1
  description: VXLAN_TUNNEL_SOURCE
  shutdown: false
  ip_address: 10.0.254.1/32
management_api_http:
  enable_https: true
  enable_vrfs:
  - name: MGMT
ntp:
  servers:
  - name: 2.2.2.55
    preferred: true
  - name: pool.ntp.org
port_channel_interfaces:
- name: Port-Channel21
  description: INBAND-MGMT-SUBNET_Po1
  shutdown: false
  lacp_fallback_timeout: 30
  lacp_fallback_mode: individual
  switchport:
    enabled: true
    mode: trunk
    trunk:
      allowed_vlan: '101'
- name: Port-Channel22
  description: INBAND-MGMT-SUBNET-VRF_Po1
  shutdown: false
  lacp_fallback_timeout: 90
  lacp_fallback_mode: individual
  switchport:
    enabled: true
    mode: trunk
    trunk:
      allowed_vlan: '102'
- name: Port-Channel23
  description: INBAND-MGMT-IP_Po1
  shutdown: false
  switchport:
    enabled: true
    mode: trunk
    trunk:
      allowed_vlan: '103'
- name: Port-Channel101
  description: inband-mgmt-mlag-test_Po1
  shutdown: false
  lacp_fallback_timeout: 30
  lacp_fallback_mode: individual
  switchport:
    enabled: true
    mode: trunk
    trunk:
      allowed_vlan: '101'
prefix_lists:
- name: PL-LOOPBACKS-EVPN-OVERLAY
  sequence_numbers:
  - sequence: 10
    action: permit 10.0.255.0/24 eq 32
  - sequence: 20
    action: permit 10.0.254.0/24 eq 32
- name: PL-L2LEAF-INBAND-MGMT
  sequence_numbers:
  - sequence: 10
    action: permit 192.168.101.0/24
  - sequence: 20
    action: permit 192.168.102.0/24
route_maps:
- name: RM-CONN-2-BGP
  sequence_numbers:
  - sequence: 10
    type: permit
    match:
    - ip address prefix-list PL-LOOPBACKS-EVPN-OVERLAY
  - sequence: 20
    type: permit
    match:
    - ip address prefix-list PL-L2LEAF-INBAND-MGMT
router_bfd:
  multihop:
    interval: 300
    min_rx: 300
    multiplier: 3
router_bgp:
  as: '65000'
  router_id: 10.0.255.1
  maximum_paths:
    paths: 4
    ecmp: 4
  updates:
    wait_install: true
  bgp:
    default:
      ipv4_unicast: false
  peer_groups:
  - name: IPv4-UNDERLAY-PEERS
    type: ipv4
    send_community: all
    maximum_routes: 12000
  - name: EVPN-OVERLAY-PEERS
    type: evpn
    update_source: Loopback0
    bfd: true
    ebgp_multihop: 3
    send_community: all
    maximum_routes: 0
  neighbors:
  - ip_address: 172.16.255.0
    peer_group: IPv4-UNDERLAY-PEERS
    remote_as: '64999'
    peer: inband-mgmt-spine1-ztp
    description: inband-mgmt-spine1-ztp_Ethernet1
  - ip_address: 10.0.254.1
    peer_group: EVPN-OVERLAY-PEERS
    remote_as: '64999'
    peer: inband-mgmt-spine1-ztp
    description: inband-mgmt-spine1-ztp_Loopback0
  redistribute:
    attached_host:
      enabled: true
    connected:
      enabled: true
      route_map: RM-CONN-2-BGP
  address_family_evpn:
    peer_groups:
    - name: EVPN-OVERLAY-PEERS
      activate: true
  address_family_ipv4:
    peer_groups:
    - name: IPv4-UNDERLAY-PEERS
      activate: true
    - name: EVPN-OVERLAY-PEERS
      activate: false
  vrfs:
  - name: INBANDMGMT
    rd: 10.0.255.1:1
    route_targets:
      import:
      - address_family: evpn
        route_targets:
        - '1:1'
      export:
      - address_family: evpn
        route_targets:
        - '1:1'
    router_id: 10.0.255.1
    redistribute:
      connected:
        enabled: true
service_routing_protocols_model: multi-agent
transceiver_qsfp_default_mode_4x10: true
vlan_interfaces:
- name: Vlan103
  description: Inband management vlan
  shutdown: true
  vrf: INBANDMGMT
  ip_address: 192.168.103.1/24
  tenant: INBAND_MGMT_TESTS
- name: Vlan101
  description: Inband Management
  shutdown: false
  ip_address: 192.168.101.2/24
  ip_virtual_router_addresses:
  - 192.168.101.1
  mtu: 1500
  ip_attached_host_route_export:
    enabled: true
    distance: 19
- name: Vlan102
  description: Inband Management
  shutdown: false
  ip_address: 192.168.102.2/24
  ip_virtual_router_addresses:
  - 192.168.102.1
  mtu: 1500
  ip_attached_host_route_export:
    enabled: true
    distance: 19
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vlans:
- id: 103
  name: Inband management vlan
  tenant: INBAND_MGMT_TESTS
- id: 101
  name: INBAND_MGMT
  tenant: system
- id: 102
  name: INBAND_MGMT
  tenant: system
vrfs:
- name: MGMT
  ip_routing: false
- name: INBANDMGMT
  ip_routing: true
  tenant: INBAND_MGMT_TESTS
vxlan_interface:
  vxlan1:
    description: inband-mgmt-parent_VTEP
    vxlan:
      source_interface: Loopback1
      udp_port: 4789
      vrfs:
      - name: INBANDMGMT
        vni: 1
