aaa_root:
  disabled: true
config_end: true
daemon_terminattr:
  cvaddrs:
  - apiserver.arista.io:443
  cvauth:
    method: token-secure
    token_file: /tmp/cv-onboarding-token
  cvvrf: MGMT
  disable_aaa: false
  ingestexclude: /Sysdb/cell/1/agent,/Sysdb/cell/2/agent
  smashexcludes: ale,flexCounter,hardware,kni,pulse,strata
enable_password:
  disabled: true
ethernet_interfaces:
- name: Ethernet1
  description: INBAND-MGMT-PARENT-IPV6-1_Ethernet27
  shutdown: false
  channel_group:
    id: 1
    mode: active
  peer: inband-mgmt-parent-ipv6-1
  peer_interface: Ethernet27
  peer_type: l3leaf
- name: Ethernet2
  description: INBAND-MGMT-PARENT-IPV6-2_Ethernet27
  shutdown: false
  channel_group:
    id: 1
    mode: active
  peer: inband-mgmt-parent-ipv6-2
  peer_interface: Ethernet27
  peer_type: l3leaf
hostname: inband-mgmt-ipv6-only-vrf
ip_igmp_snooping:
  globally_enabled: true
ip_name_servers:
- ip_address: 1.1.1.1
  vrf: MGMT
- ip_address: 8.8.8.8
  vrf: MGMT
ipv6_static_routes:
- vrf: INBANDMGMT
  destination_address_prefix: ::/0
  gateway: 2a00:107::1
is_deployed: true
management_api_http:
  enable_https: true
  enable_vrfs:
  - name: MGMT
ntp:
  servers:
  - name: 2.2.2.55
    preferred: true
  - name: pool.ntp.org
port_channel_interfaces:
- name: Port-Channel1
  description: inband-mgmt-parents-ipv6_Po27
  shutdown: false
  switchport:
    enabled: true
    mode: trunk
    trunk:
      allowed_vlan: '107'
service_routing_protocols_model: multi-agent
transceiver_qsfp_default_mode_4x10: true
vlan_interfaces:
- name: Vlan107
  description: Inband Management
  shutdown: false
  vrf: INBANDMGMT
  ipv6_enable: true
  ipv6_address: 2a00:107::a/64
  mtu: 1500
  type: inband_mgmt
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vlans:
- id: 107
  name: INBAND_MGMT
  tenant: system
vrfs:
- name: MGMT
  ip_routing: false
