aaa_root:
  disabled: true
config_end: true
daemon_terminattr:
  cvaddrs:
  - apiserver.arista.io:443
  cvauth:
    method: token-secure
    token_file: /tmp/cv-onboarding-token
  cvvrf: MGMT
  disable_aaa: false
  ingestexclude: /Sysdb/cell/1/agent,/Sysdb/cell/2/agent
  smashexcludes: ale,flexCounter,hardware,kni,pulse,strata
enable_password:
  disabled: true
ethernet_interfaces:
- name: Ethernet11
  description: MLAG_inband-mgmt-mlag-b_Ethernet11
  shutdown: false
  channel_group:
    id: 11
    mode: active
  peer: inband-mgmt-mlag-b
  peer_interface: Ethernet11
  peer_type: mlag_peer
  switchport:
    enabled: true
    mode: access
    access_vlan: 101
- name: Ethernet12
  description: MLAG_inband-mgmt-mlag-b_Ethernet12
  shutdown: false
  channel_group:
    id: 11
    mode: active
  peer: inband-mgmt-mlag-b
  peer_interface: Ethernet12
  peer_type: mlag_peer
  switchport:
    enabled: true
    mode: access
    access_vlan: 101
- name: Ethernet13
  description: MLAG_inband-mgmt-mlag-b_Ethernet13
  shutdown: false
  channel_group:
    id: 11
    mode: active
  peer: inband-mgmt-mlag-b
  peer_interface: Ethernet13
  peer_type: mlag_peer
  switchport:
    enabled: true
    mode: access
    access_vlan: 101
- name: Ethernet14
  description: MLAG_inband-mgmt-mlag-b_Ethernet14
  shutdown: false
  channel_group:
    id: 11
    mode: active
  peer: inband-mgmt-mlag-b
  peer_interface: Ethernet14
  peer_type: mlag_peer
  switchport:
    enabled: true
    mode: access
    access_vlan: 101
- name: Ethernet15
  description: MLAG_inband-mgmt-mlag-b_Ethernet15
  shutdown: false
  channel_group:
    id: 11
    mode: active
  peer: inband-mgmt-mlag-b
  peer_interface: Ethernet15
  peer_type: mlag_peer
  switchport:
    enabled: true
    mode: access
    access_vlan: 101
- name: Ethernet16
  description: MLAG_inband-mgmt-mlag-b_Ethernet16
  shutdown: false
  channel_group:
    id: 11
    mode: active
  peer: inband-mgmt-mlag-b
  peer_interface: Ethernet16
  peer_type: mlag_peer
  switchport:
    enabled: true
    mode: access
    access_vlan: 101
- name: Ethernet17
  description: MLAG_inband-mgmt-mlag-b_Ethernet17
  shutdown: false
  channel_group:
    id: 11
    mode: active
  peer: inband-mgmt-mlag-b
  peer_interface: Ethernet17
  peer_type: mlag_peer
  switchport:
    enabled: true
    mode: access
    access_vlan: 101
- name: Ethernet18
  description: MLAG_inband-mgmt-mlag-b_Ethernet18
  shutdown: false
  channel_group:
    id: 11
    mode: active
  peer: inband-mgmt-mlag-b
  peer_interface: Ethernet18
  peer_type: mlag_peer
  switchport:
    enabled: true
    mode: access
    access_vlan: 101
- name: Ethernet19
  description: MLAG_inband-mgmt-mlag-b_Ethernet19
  shutdown: false
  channel_group:
    id: 11
    mode: active
  peer: inband-mgmt-mlag-b
  peer_interface: Ethernet19
  peer_type: mlag_peer
  switchport:
    enabled: true
    mode: access
    access_vlan: 101
- name: Ethernet20
  description: MLAG_inband-mgmt-mlag-b_Ethernet20
  shutdown: false
  channel_group:
    id: 11
    mode: active
  peer: inband-mgmt-mlag-b
  peer_interface: Ethernet20
  peer_type: mlag_peer
  switchport:
    enabled: true
    mode: access
    access_vlan: 101
- name: Ethernet1
  description: INBAND-MGMT-PARENT_Ethernet101
  shutdown: false
  channel_group:
    id: 1
    mode: active
  peer: inband-mgmt-parent
  peer_interface: Ethernet101
  peer_type: l3leaf
- name: Ethernet2
  description: INBAND-MGMT-PARENT-VRF_Ethernet101
  shutdown: false
  channel_group:
    id: 1
    mode: active
  peer: inband-mgmt-parent-vrf
  peer_interface: Ethernet101
  peer_type: l3leaf
hostname: inband-mgmt-mlag-a
ip_igmp_snooping:
  globally_enabled: true
ip_name_servers:
- ip_address: 1.1.1.1
  vrf: MGMT
- ip_address: 8.8.8.8
  vrf: MGMT
is_deployed: true
management_api_http:
  enable_https: true
  enable_vrfs:
  - name: MGMT
mlag_configuration:
  domain_id: inband-mgmt-mlag-test
  local_interface: Vlan4094
  peer_address: 100.64.0.201
  peer_link: Port-Channel11
  reload_delay_mlag: '300'
  reload_delay_non_mlag: '330'
ntp:
  servers:
  - name: 2.2.2.55
    preferred: true
  - name: pool.ntp.org
port_channel_interfaces:
- name: Port-Channel11
  description: MLAG_inband-mgmt-mlag-b_Port-Channel11
  shutdown: false
  lacp_fallback_timeout: 30
  lacp_fallback_mode: individual
  switchport:
    enabled: true
    mode: trunk
    trunk:
      groups:
      - MLAG
- name: Port-Channel1
  description: INBAND-MGMT-PARENT_Po101
  shutdown: false
  mlag: 1
  switchport:
    enabled: true
    mode: trunk
    trunk:
      allowed_vlan: '101'
service_routing_protocols_model: multi-agent
spanning_tree:
  no_spanning_tree_vlan: '4094'
static_routes:
- destination_address_prefix: 0.0.0.0/0
  gateway: 192.168.101.21
transceiver_qsfp_default_mode_4x10: true
vlan_interfaces:
- name: Vlan4094
  description: MLAG
  shutdown: false
  ip_address: 100.64.0.200/31
  mtu: 9214
  no_autostate: true
- name: Vlan101
  description: Inband Management
  shutdown: false
  ip_address: 192.168.101.22/24
  mtu: 1500
  type: inband_mgmt
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vlans:
- id: 4094
  name: MLAG
  trunk_groups:
  - MLAG
  tenant: system
- id: 101
  name: INBAND_MGMT
  tenant: system
vrfs:
- name: MGMT
  ip_routing: false
