aaa_root:
  disabled: true
config_end: true
enable_password:
  disabled: true
ethernet_interfaces:
- name: ethernet1
  description: P2P_peer1_ethernet1
  shutdown: false
  speed: forced 10000full
  mtu: 2000
  ip_address: 192.168.0.0/31
  mac_security:
    profile: TEST-MACSEC-PROFILE
  ptp:
    enable: true
    announce:
      interval: 0
      timeout: 3
    delay_req: -3
    sync_message:
      interval: -3
    transport: ipv4
  service_profile: TEST-QOS-PROFILE
  peer: peer1
  peer_interface: ethernet1
  peer_type: other
  switchport:
    enabled: false
- name: ethernet2
  description: P2P_peer2_ethernet2
  shutdown: false
  mtu: 9214
  ip_address: 192.168.0.2/31
  isis_enable: EVPN_UNDERLAY
  isis_bfd: true
  isis_metric: 60
  isis_network_point_to_point: true
  isis_circuit_type: level-2
  isis_hello_padding: false
  isis_authentication:
    both:
      key_type: '7'
      key: $1c$sTNAlR6rKSw=
      mode: md5
  peer: peer2
  peer_interface: ethernet2
  peer_type: other
  switchport:
    enabled: false
- name: ethernet3
  description: P2P_peer3_ethernet3
  shutdown: false
  mtu: 9214
  ip_address: 192.168.0.4/31
  isis_enable: EVPN_UNDERLAY
  isis_bfd: true
  isis_metric: 50
  isis_network_point_to_point: true
  isis_circuit_type: level-2
  isis_hello_padding: true
  isis_authentication:
    both:
      key_type: '7'
      key: $1c$sTNAlR6rKSw=
      mode: text
  peer: peer3
  peer_interface: ethernet3
  peer_type: other
  switchport:
    enabled: false
- name: ethernet4
  description: P2P_peer4_ethernet4
  shutdown: false
  mtu: 9214
  ip_address: 192.168.0.6/31
  isis_enable: EVPN_UNDERLAY
  isis_bfd: true
  isis_metric: 50
  isis_network_point_to_point: true
  isis_circuit_type: level-2
  isis_hello_padding: true
  isis_authentication:
    both:
      key_type: '7'
      key: $1c$sTNAlR6rKSw=
      mode: text
  peer: peer4
  peer_interface: ethernet4
  peer_type: other
  switchport:
    enabled: false
hostname: l3_edge_isis
ip_routing: true
is_deployed: true
loopback_interfaces:
- name: Loopback0
  description: ROUTER_ID
  shutdown: false
  ip_address: 1.2.3.1/32
  isis_enable: EVPN_UNDERLAY
  isis_passive: true
management_api_http:
  enable_https: true
  enable_vrfs:
  - name: MGMT
ptp:
  mode: boundary
  clock_identity: 00:1C:73:14:00:01
  priority1: 20
  priority2: 1
  domain: 127
  monitor:
    enabled: true
    threshold:
      offset_from_master: 250
      mean_path_delay: 1500
    missing_message:
      sequence_ids:
        enabled: true
        announce: 3
        delay_resp: 3
        follow_up: 3
        sync: 3
router_isis:
  instance: EVPN_UNDERLAY
  net: 49.0001.0010.0200.3001.00
  router_id: 1.2.3.1
  is_type: level-2
  log_adjacency_changes: true
  address_family_ipv4:
    enabled: true
    maximum_paths: 4
service_routing_protocols_model: multi-agent
spanning_tree:
  mode: none
transceiver_qsfp_default_mode_4x10: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vrfs:
- name: MGMT
  ip_routing: false
