aaa_root:
  disabled: true
config_end: true
enable_password:
  disabled: true
ethernet_interfaces:
- name: ethernet1
  description: P2P_peer1_ethernet1
  shutdown: false
  mtu: 9214
  ip_address: 192.168.0.4/31
  ospf_network_point_to_point: true
  ospf_area: 0.0.0.0
  peer: peer1
  peer_interface: ethernet1
  peer_type: other
  switchport:
    enabled: false
- name: ethernet2
  description: P2P_peer2_ethernet2
  shutdown: false
  mtu: 9214
  ip_address: 192.168.0.2/31
  ospf_network_point_to_point: true
  ospf_area: 0.0.0.0
  pim:
    ipv4:
      sparse_mode: true
  peer: peer2
  peer_interface: ethernet2
  peer_type: other
  switchport:
    enabled: false
hostname: l3_edge_multicast
ip_routing: true
is_deployed: true
loopback_interfaces:
- name: Loopback0
  description: ROUTER_ID
  shutdown: false
  ip_address: 1.2.3.1/32
  ospf_area: 0.0.0.0
management_api_http:
  enable_https: true
  enable_vrfs:
  - name: MGMT
router_multicast:
  ipv4:
    routing: true
router_ospf:
  process_ids:
  - id: 100
    passive_interface_default: true
    router_id: 1.2.3.1
    bfd_enable: false
    no_passive_interfaces:
    - ethernet1
    - ethernet2
    max_lsa: 12000
service_routing_protocols_model: multi-agent
spanning_tree:
  mode: none
transceiver_qsfp_default_mode_4x10: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vrfs:
- name: MGMT
  ip_routing: false
