aaa_root:
  disabled: true
config_end: true
enable_password:
  disabled: true
hostname: mgmt_interface_ipv6
ip_igmp_snooping:
  globally_enabled: true
ipv6_static_routes:
- vrf: MGMT
  destination_address_prefix: ::/0
  gateway: 0200::2
is_deployed: true
management_api_http:
  enable_https: true
  enable_vrfs:
  - name: MGMT
management_interfaces:
- name: Management1
  description: OOB_MANAGEMENT
  shutdown: false
  vrf: MGMT
  ipv6_enable: true
  ipv6_address: 0200::105/64
  type: oob
  ipv6_gateway: 0200::2
service_routing_protocols_model: multi-agent
transceiver_qsfp_default_mode_4x10: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vrfs:
- name: MGMT
  ip_routing: false
  ipv6_routing: false
