aaa_root:
  disabled: true
config_end: true
enable_password:
  disabled: true
hostname: mgmt_interface_dualstack
ip_igmp_snooping:
  globally_enabled: true
ipv6_static_routes:
- vrf: MGMT
  destination_address_prefix: 0200:1::/64
  gateway: 0200::1
- vrf: MGMT
  destination_address_prefix: 0200:2::/64
  gateway: 0200::1
is_deployed: true
management_api_http:
  enable_https: true
  enable_vrfs:
  - name: MGMT
management_interfaces:
- name: Management1
  description: OOB_MANAGEMENT
  shutdown: false
  vrf: MGMT
  ip_address: 192.168.200.105
  ipv6_enable: true
  ipv6_address: 0200::105/64
  type: oob
  gateway: 192.168.200.5
  ipv6_gateway: 0200::1
service_routing_protocols_model: multi-agent
static_routes:
- vrf: MGMT
  destination_address_prefix: 10.0.10.0/24
  gateway: 192.168.200.5
- vrf: MGMT
  destination_address_prefix: 172.16.254.0/23
  gateway: 192.168.200.5
transceiver_qsfp_default_mode_4x10: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vrfs:
- name: MGMT
  ip_routing: false
  ipv6_routing: false
