aaa_root:
  disabled: true
config_end: true
enable_password:
  disabled: true
hostname: mgmt_interface_description
ip_igmp_snooping:
  globally_enabled: true
is_deployed: true
management_api_http:
  enable_https: true
  enable_vrfs:
  - name: MGMT
management_interfaces:
- name: Management1
  description: Custom Management Interface Description
  shutdown: false
  vrf: MGMT
  ip_address: 1.1.1.2/24
  type: oob
  gateway: 1.1.1.254
service_routing_protocols_model: multi-agent
static_routes:
- vrf: MGMT
  destination_address_prefix: 0.0.0.0/0
  gateway: 1.1.1.254
transceiver_qsfp_default_mode_4x10: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vrfs:
- name: MGMT
  ip_routing: false
