aaa_root:
  disabled: true
config_end: true
daemon_terminattr:
  cvaddrs:
  - 192.168.200.11:9910
  cvauth:
    method: key
    key: telarista
  cvvrf: MGMT
  disable_aaa: false
  ingestexclude: /Sysdb/cell/1/agent,/Sysdb/cell/2/agent
  smashexcludes: ale,flexCounter,hardware,kni,pulse,strata
enable_password:
  disabled: true
ethernet_interfaces:
- name: Ethernet1
  description: MH-LEAF2A_Ethernet2
  shutdown: false
  channel_group:
    id: 1
    mode: active
  peer: MH-LEAF2A
  peer_interface: Ethernet2
  peer_type: l3leaf
- name: Ethernet10
  description: server02_Eth1
  shutdown: false
  link_tracking_groups:
  - name: l2leaf-server02
    direction: downstream
  peer: server02
  peer_interface: Eth1
  peer_type: server
  switchport:
    enabled: true
hostname: MH-L2LEAF1A
ip_igmp_snooping:
  globally_enabled: true
ip_name_servers:
- ip_address: 192.168.200.5
  vrf: MGMT
- ip_address: 8.8.8.8
  vrf: MGMT
- ip_address: 2001:db8::1
  vrf: MGMT
- ip_address: 2001:db8::2
  vrf: MGMT
is_deployed: true
link_tracking_groups:
- name: l2leaf-server02
  recovery_delay: 300
local_users:
- name: admin
  disabled: true
  privilege: 15
  role: network-admin
  no_password: true
- name: cvpadmin
  privilege: 15
  role: network-admin
  sha512_password: $6$rZKcbIZ7iWGAWTUM$TCgDn1KcavS0s.OV8lacMTUkxTByfzcGlFlYUWroxYuU7M/9bIodhRO7nXGzMweUxvbk8mJmQl8Bh44cRktUj.
  ssh_key: ssh-rsa AAAAB3NzaC1yc2EAA82spi2mkxp4FgaLi4CjWkpnL1A/MD7WhrSNgqXToF7QCb9Lidagy9IHafQxfu7LwkFdyQIMu8XNwDZIycuf29wHbDdz1N+YNVK8zwyNAbMOeKMqblsEm2YIorgjzQX1m9+/rJeFBKz77PSgeMp/Rc3txFVuSmFmeTy3aMkU=
    cvpadmin@hostmachine.local
  secondary_ssh_key: ssh-rsa AAAAB3NzaC1yc2EAA82spi2mkxp4FgaLi4CjWkpnL1A/MD7WhrSNgqXToF7QCb9Lidagy9IHafQxfu7LwkFdyQIMu8XNwDZIycuf29wHbDdz1N+YNVK8zwyNAbMOeKMqblsEm2YIorgjzQX1m9+/rJeFBKz77PSgeMp/Rc3txFVuSmFmeTy3aMkz=
    cvpadmin@hostmachine.local
management_api_http:
  enable_https: true
  default_services: false
  enable_vrfs:
  - name: MGMT
management_interfaces:
- name: Management1
  description: OOB_MANAGEMENT
  shutdown: false
  vrf: MGMT
  ip_address: 192.168.201.201/24
  type: oob
  gateway: 192.168.200.5
metadata:
  platform: vEOS-LAB
ntp:
  local_interface:
    name: Management1
    vrf: MGMT
  servers:
  - name: 192.168.200.5
    preferred: true
    vrf: MGMT
  - name: 2001:db8::3
    vrf: MGMT
port_channel_interfaces:
- name: Port-Channel1
  description: MH-LEAF2A_Po2
  shutdown: false
  link_tracking_groups:
  - name: l2leaf-server02
    direction: upstream
  switchport:
    enabled: true
    mode: trunk
    trunk:
      allowed_vlan: '310'
service_routing_protocols_model: multi-agent
snmp_server:
  contact: example@example.com
  location: EOS_DESIGNS_UNIT_TESTS MH-L2LEAF1A
spanning_tree:
  mode: mstp
  mst_instances:
  - id: '0'
    priority: 16384
static_routes:
- vrf: MGMT
  destination_address_prefix: 0.0.0.0/0
  gateway: 192.168.200.5
transceiver_qsfp_default_mode_4x10: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vlans:
- id: 310
  name: Tenant_X_OP_Zone_1
  tenant: Tenant_X
vrfs:
- name: MGMT
  ip_routing: false
