aaa_root:
  disabled: true
config_end: true
daemon_terminattr:
  cvaddrs:
  - 192.168.200.11:9910
  cvauth:
    method: key
    key: telarista
  cvvrf: MGMT
  disable_aaa: false
  ingestexclude: /Sysdb/cell/1/agent,/Sysdb/cell/2/agent
  smashexcludes: ale,flexCounter,hardware,kni,pulse,strata
enable_password:
  disabled: true
ethernet_interfaces:
- name: Ethernet5
  description: MLAG_PEER_MLAG-OSPF-L3LEAF1A_Ethernet5
  shutdown: false
  channel_group:
    id: 5
    mode: active
  peer: MLAG-OSPF-L3LEAF1A
  peer_interface: Ethernet5
  peer_type: mlag_peer
- name: Ethernet6
  description: MLAG_PEER_MLAG-OSPF-L3LEAF1A_Ethernet6
  shutdown: false
  channel_group:
    id: 5
    mode: active
  peer: MLAG-OSPF-L3LEAF1A
  peer_interface: Ethernet6
  peer_type: mlag_peer
- name: Ethernet1
  description: P2P_LINK_TO_DC1-SPINE1_Ethernet220
  shutdown: false
  mtu: 1500
  ip_address: 10.10.101.9/31
  ospf_network_point_to_point: true
  ospf_area: 0.0.0.0
  ospf_authentication: message-digest
  ospf_message_digest_keys:
  - id: 1
    hash_algorithm: sha512
    key: qO39Oo+xVTO7l/La1StOQcW1t7hpfAAH
  - id: 2
    hash_algorithm: sha512
    key: pWGuZ4QaDATcfTOKCkm1p2Rq2A4O9j5j
  peer: DC1-SPINE1
  peer_interface: Ethernet220
  peer_type: spine
  switchport:
    enabled: false
hostname: MLAG-OSPF-L3LEAF1B
ip_igmp_snooping:
  globally_enabled: true
ip_name_servers:
- ip_address: 192.168.200.5
  vrf: MGMT
- ip_address: 8.8.8.8
  vrf: MGMT
- ip_address: 2001:db8::1
  vrf: MGMT
- ip_address: 2001:db8::2
  vrf: MGMT
ip_routing: true
is_deployed: true
local_users:
- name: admin
  disabled: true
  privilege: 15
  role: network-admin
  no_password: true
- name: cvpadmin
  privilege: 15
  role: network-admin
  sha512_password: $6$rZKcbIZ7iWGAWTUM$TCgDn1KcavS0s.OV8lacMTUkxTByfzcGlFlYUWroxYuU7M/9bIodhRO7nXGzMweUxvbk8mJmQl8Bh44cRktUj.
  ssh_key: ssh-rsa AAAAB3NzaC1yc2EAA82spi2mkxp4FgaLi4CjWkpnL1A/MD7WhrSNgqXToF7QCb9Lidagy9IHafQxfu7LwkFdyQIMu8XNwDZIycuf29wHbDdz1N+YNVK8zwyNAbMOeKMqblsEm2YIorgjzQX1m9+/rJeFBKz77PSgeMp/Rc3txFVuSmFmeTy3aMkU=
    cvpadmin@hostmachine.local
  secondary_ssh_key: ssh-rsa AAAAB3NzaC1yc2EAA82spi2mkxp4FgaLi4CjWkpnL1A/MD7WhrSNgqXToF7QCb9Lidagy9IHafQxfu7LwkFdyQIMu8XNwDZIycuf29wHbDdz1N+YNVK8zwyNAbMOeKMqblsEm2YIorgjzQX1m9+/rJeFBKz77PSgeMp/Rc3txFVuSmFmeTy3aMkz=
    cvpadmin@hostmachine.local
loopback_interfaces:
- name: Loopback0
  description: ROUTER_ID
  shutdown: false
  ip_address: 192.168.255.37/32
  ospf_area: 0.0.0.0
- name: Loopback1
  description: VXLAN_TUNNEL_SOURCE
  shutdown: false
  ip_address: 192.168.254.36/32
  ospf_area: 0.0.0.0
management_api_http:
  enable_https: true
  default_services: false
  enable_vrfs:
  - name: MGMT
management_interfaces:
- name: Management1
  description: OOB_MANAGEMENT
  shutdown: false
  vrf: MGMT
  ip_address: 192.168.201.115/24
  type: oob
  gateway: 192.168.200.5
metadata:
  platform: vEOS-LAB
mlag_configuration:
  domain_id: MLAG_OSPF_L3LEAF1
  local_interface: Vlan4094
  peer_address: 10.10.255.6
  peer_link: Port-Channel5
  reload_delay_mlag: '300'
  reload_delay_non_mlag: '330'
ntp:
  local_interface:
    name: Management1
    vrf: MGMT
  servers:
  - name: 192.168.200.5
    preferred: true
    vrf: MGMT
  - name: 2001:db8::3
    vrf: MGMT
port_channel_interfaces:
- name: Port-Channel5
  description: MLAG_PEER_MLAG-OSPF-L3LEAF1A_Po5
  shutdown: false
  switchport:
    enabled: true
    mode: trunk
    trunk:
      groups:
      - MLAG
      - LEAF_PEER_L3
router_bfd:
  multihop:
    interval: 1200
    min_rx: 1200
    multiplier: 3
router_bgp:
  as: '65161'
  router_id: 192.168.255.37
  maximum_paths:
    paths: 4
    ecmp: 4
  updates:
    wait_install: true
  bgp:
    default:
      ipv4_unicast: false
  peer_groups:
  - name: EVPN-OVERLAY-PEERS
    type: evpn
    update_source: Loopback0
    bfd: true
    ebgp_multihop: 3
    password: q+VNViP5i4rVjW1cxFv2wA==
    send_community: all
    maximum_routes: 0
  neighbors:
  - ip_address: 192.168.255.1
    peer_group: EVPN-OVERLAY-PEERS
    remote_as: '65001'
    peer: DC1-SPINE1
    description: DC1-SPINE1
  address_family_evpn:
    peer_groups:
    - name: EVPN-OVERLAY-PEERS
      activate: true
    evpn_hostflap_detection:
      enabled: true
      window: 180
      threshold: 5
      expiry_timeout: 10
  address_family_ipv4:
    peer_groups:
    - name: EVPN-OVERLAY-PEERS
      activate: false
router_ospf:
  process_ids:
  - id: 100
    passive_interface_default: true
    router_id: 192.168.255.37
    bfd_enable: false
    no_passive_interfaces:
    - Ethernet1
    - Vlan4094
    max_lsa: 12000
service_routing_protocols_model: multi-agent
snmp_server:
  contact: example@example.com
  location: EOS_DESIGNS_UNIT_TESTS MLAG-OSPF-L3LEAF1B
spanning_tree:
  no_spanning_tree_vlan: '4094'
static_routes:
- vrf: MGMT
  destination_address_prefix: 0.0.0.0/0
  gateway: 192.168.200.5
transceiver_qsfp_default_mode_4x10: true
vlan_interfaces:
- name: Vlan4094
  description: MLAG_PEER
  shutdown: false
  ip_address: 10.10.255.7/31
  ospf_network_point_to_point: true
  ospf_area: 0.0.0.0
  mtu: 1500
  no_autostate: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vlans:
- id: 4094
  name: MLAG_PEER
  trunk_groups:
  - MLAG
  tenant: system
vrfs:
- name: MGMT
  ip_routing: false
vxlan_interface:
  vxlan1:
    description: MLAG-OSPF-L3LEAF1B_VTEP
    vxlan:
      source_interface: Loopback1
      udp_port: 4789
      virtual_router_encapsulation_mac_address: mlag-system-id
