aaa_root:
  disabled: true
config_end: true
enable_password:
  disabled: true
ethernet_interfaces:
- name: Ethernet1
  description: peer1_eth1
  shutdown: false
  speed: forced 10000full
  ip_address: 192.168.1.2/31
  service_profile: TEST-QOS-PROFILE
  service_policy:
    qos:
      input: TEST_POLICY
  peer: peer1
  peer_interface: eth1
  peer_type: l3_interface
  sflow:
    enable: true
  switchport:
    enabled: false
  eos_cli: '! TEST RAW_EOS_CLI

    '
- name: Ethernet2/2
  description: peer2
  shutdown: false
  ip_address: dhcp
  dhcp_client_accept_default_route: true
  peer: peer2
  peer_type: l3_interface
  sflow:
    enable: true
  switchport:
    enabled: false
- name: Ethernet42
  description: This is a custom description
  shutdown: true
  ip_address: dhcp
  dhcp_client_accept_default_route: true
  peer: peer3
  peer_type: l3_interface
  sflow:
    enable: true
  switchport:
    enabled: false
- name: Ethernet43
  shutdown: true
  ip_address: 192.168.42.42/24
  peer_type: l3_interface
  sflow:
    enable: true
  switchport:
    enabled: false
hostname: node-type-l3-interfaces
ip_routing: true
is_deployed: true
loopback_interfaces:
- name: Loopback0
  description: ROUTER_ID
  shutdown: false
  ip_address: 1.2.3.1/32
management_api_http:
  enable_https: true
  enable_vrfs:
  - name: MGMT
prefix_lists:
- name: PL-LOOPBACKS-EVPN-OVERLAY
  sequence_numbers:
  - sequence: 10
    action: permit 1.2.3.4/24 eq 32
route_maps:
- name: RM-CONN-2-BGP
  sequence_numbers:
  - sequence: 10
    type: permit
    match:
    - ip address prefix-list PL-LOOPBACKS-EVPN-OVERLAY
router_bgp:
  as: '65000'
  router_id: 1.2.3.1
  maximum_paths:
    paths: 4
    ecmp: 4
  updates:
    wait_install: true
  bgp:
    default:
      ipv4_unicast: false
  peer_groups:
  - name: IPv4-UNDERLAY-PEERS
    type: ipv4
    send_community: all
    maximum_routes: 12000
  redistribute:
    connected:
      enabled: true
      route_map: RM-CONN-2-BGP
  address_family_ipv4:
    peer_groups:
    - name: IPv4-UNDERLAY-PEERS
      activate: true
service_routing_protocols_model: multi-agent
sflow:
  vrfs:
  - name: sflow_vrf
    destinations:
    - destination: 10.10.10.12
      port: 1234
  run: true
spanning_tree:
  mode: none
static_routes:
- destination_address_prefix: 0.0.0.0/0
  gateway: 192.168.1.3
transceiver_qsfp_default_mode_4x10: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vrfs:
- name: MGMT
  ip_routing: false
