aaa_root:
  disabled: true
config_end: true
cvx:
  shutdown: false
  peer_hosts:
  - 192.168.254.255
  services:
    vxlan:
      shutdown: false
enable_password:
  disabled: true
hostname: OVERLAY_ROUTING_PROTOCOL_CVX_SERVER1
is_deployed: true
management_api_http:
  enable_https: true
  enable_vrfs:
  - name: MGMT
management_interfaces:
- name: Management1
  description: OOB_MANAGEMENT
  shutdown: false
  vrf: MGMT
  ip_address: 192.168.254.254/23
  type: oob
service_routing_protocols_model: multi-agent
spanning_tree:
  mode: none
transceiver_qsfp_default_mode_4x10: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vrfs:
- name: MGMT
  ip_routing: false
