aaa_root:
  disabled: true
config_end: true
enable_password:
  disabled: true
hostname: OVERLAY_ROUTING_PROTOCOL_HER_L3LEAF2
ip_igmp_snooping:
  globally_enabled: true
ip_routing: true
is_deployed: true
loopback_interfaces:
- name: Loopback0
  description: ROUTER_ID
  shutdown: false
  ip_address: 192.168.254.2/32
- name: Loopback1
  description: VXLAN_TUNNEL_SOURCE
  shutdown: false
  ip_address: 192.168.253.2/32
management_api_http:
  enable_https: true
  enable_vrfs:
  - name: MGMT
prefix_lists:
- name: PL-LOOPBACKS-EVPN-OVERLAY
  sequence_numbers:
  - sequence: 10
    action: permit 192.168.254.0/24 eq 32
  - sequence: 20
    action: permit 192.168.253.0/24 eq 32
route_maps:
- name: RM-CONN-2-BGP
  sequence_numbers:
  - sequence: 10
    type: permit
    match:
    - ip address prefix-list PL-LOOPBACKS-EVPN-OVERLAY
router_bgp:
  as: '65002'
  router_id: 192.168.254.2
  maximum_paths:
    paths: 4
    ecmp: 4
  updates:
    wait_install: true
  bgp:
    default:
      ipv4_unicast: false
  peer_groups:
  - name: IPv4-UNDERLAY-PEERS
    type: ipv4
    send_community: all
    maximum_routes: 12000
  redistribute:
    connected:
      enabled: true
      route_map: RM-CONN-2-BGP
  address_family_ipv4:
    peer_groups:
    - name: IPv4-UNDERLAY-PEERS
      activate: true
service_routing_protocols_model: multi-agent
transceiver_qsfp_default_mode_4x10: true
vlan_interfaces:
- name: Vlan3900
  description: SVI_ON_ALL_LEAFS
  shutdown: true
  vrf: TEST
  tenant: TEST
  tags:
  - leaf1
  - leaf2
  - leaf3
- name: Vlan3902
  description: SVI_ON_LEAF1-2
  shutdown: true
  vrf: TEST
  tenant: TEST
  tags:
  - leaf1
  - leaf2
- name: Vlan3903
  description: SVI_ON_LEAF2-3
  shutdown: true
  vrf: TEST
  tenant: TEST
  tags:
  - leaf2
  - leaf3
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vlans:
- id: 3900
  name: SVI_ON_ALL_LEAFS
  tenant: TEST
- id: 3902
  name: SVI_ON_LEAF1-2
  tenant: TEST
- id: 3903
  name: SVI_ON_LEAF2-3
  tenant: TEST
- id: 2900
  name: L2VLAN_ON_ALL_LEAFS
  tenant: TEST
- id: 2902
  name: L2VLAN_ON_LEAF1-2
  tenant: TEST
- id: 2903
  name: L2VLAN_ON_LEAF2-3
  tenant: TEST
vrfs:
- name: MGMT
  ip_routing: false
- name: TEST
  ip_routing: true
  tenant: TEST
vxlan_interface:
  vxlan1:
    description: OVERLAY_ROUTING_PROTOCOL_HER_L3LEAF2_VTEP
    vxlan:
      source_interface: Loopback1
      udp_port: 4789
      vlans:
      - id: 3900
        vni: 13900
        flood_vteps:
        - 192.168.253.1
        - 192.168.253.3
      - id: 3902
        vni: 13902
        flood_vteps:
        - 192.168.253.1
      - id: 3903
        vni: 13903
        flood_vteps:
        - 192.168.253.3
      - id: 2900
        vni: 12900
        flood_vteps:
        - 192.168.253.1
        - 192.168.253.3
      - id: 2902
        vni: 12902
        flood_vteps:
        - 192.168.253.1
      - id: 2903
        vni: 12903
        flood_vteps:
        - 192.168.253.3
