aaa_root:
  disabled: true
config_end: true
enable_password:
  disabled: true
ethernet_interfaces:
- name: Ethernet1
  description: L2_ptp-tests-leaf1_Ethernet11
  shutdown: false
  channel_group:
    id: 1
    mode: active
  peer: ptp-tests-leaf1
  peer_interface: Ethernet11
  peer_type: l3leaf
- name: Ethernet2
  description: L2_ptp-tests-leaf2_Ethernet11
  shutdown: false
  channel_group:
    id: 1
    mode: active
  peer: ptp-tests-leaf2
  peer_interface: Ethernet11
  peer_type: l3leaf
hostname: ptp-tests-l2leaf1-ptp-disabled
ip_igmp_snooping:
  globally_enabled: true
is_deployed: true
management_api_http:
  enable_https: true
  enable_vrfs:
  - name: MGMT
metadata:
  platform: vEOS-lab
port_channel_interfaces:
- name: Port-Channel1
  description: L2_ptp-test-leaf_Port-Channel11
  shutdown: false
  switchport:
    enabled: true
    mode: trunk
    trunk:
      allowed_vlan: '11'
service_routing_protocols_model: multi-agent
spanning_tree:
  mode: mstp
  mst_instances:
  - id: '0'
    priority: 32768
static_routes:
- vrf: MGMT
  destination_address_prefix: 0.0.0.0/0
  gateway: 192.168.0.1
transceiver_qsfp_default_mode_4x10: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vlans:
- id: 11
  name: VLAN11
  tenant: PTP
vrfs:
- name: MGMT
  ip_routing: false
