aaa_root:
  disabled: true
config_end: true
enable_password:
  disabled: true
ethernet_interfaces:
- name: Ethernet9
  description: MLAG_ptp-tests-leaf1_Ethernet9
  shutdown: false
  channel_group:
    id: 9
    mode: active
  peer: ptp-tests-leaf1
  peer_interface: Ethernet9
  peer_type: mlag_peer
- name: Ethernet10
  description: MLAG_ptp-tests-leaf1_Ethernet10
  shutdown: false
  channel_group:
    id: 9
    mode: active
  peer: ptp-tests-leaf1
  peer_interface: Ethernet10
  peer_type: mlag_peer
- name: Ethernet1
  description: P2P_ptp-tests-spine1_Ethernet3
  shutdown: false
  mtu: 9214
  ip_address: 10.254.2.5/31
  ptp:
    enable: true
    announce:
      interval: 0
      timeout: 3
    delay_req: -3
    sync_message:
      interval: -3
    transport: ipv4
  peer: ptp-tests-spine1
  peer_interface: Ethernet3
  peer_type: spine
  switchport:
    enabled: false
- name: Ethernet2
  description: P2P_ptp-tests-spine1_Ethernet4
  shutdown: false
  mtu: 9214
  ip_address: 10.254.2.7/31
  ptp:
    enable: true
    announce:
      interval: 0
      timeout: 3
    delay_req: -3
    sync_message:
      interval: -3
    transport: ipv4
  peer: ptp-tests-spine1
  peer_interface: Ethernet4
  peer_type: spine
  switchport:
    enabled: false
- name: Ethernet11
  description: L2_ptp-tests-l2leaf1-ptp-disabled_Ethernet2
  shutdown: false
  channel_group:
    id: 11
    mode: active
  peer: ptp-tests-l2leaf1-ptp-disabled
  peer_interface: Ethernet2
  peer_type: l2leaf
- name: Ethernet12
  description: L2_ptp-tests-l2leaf2-ptp-enabled_Ethernet2
  shutdown: false
  channel_group:
    id: 12
    mode: active
  peer: ptp-tests-l2leaf2-ptp-enabled
  peer_interface: Ethernet2
  peer_type: l2leaf
- name: Ethernet14
  description: L2_ptp-tests-l2leaf2-ptp-enabled-uplink-disabled_Ethernet2
  shutdown: false
  channel_group:
    id: 14
    mode: active
  peer: ptp-tests-l2leaf2-ptp-enabled-uplink-disabled
  peer_interface: Ethernet2
  peer_type: l2leaf
- name: Ethernet5
  description: SERVER_video-endpoint_PCI2
  shutdown: false
  ptp:
    enable: true
    announce:
      interval: 0
      timeout: 3
    delay_req: -3
    sync_message:
      interval: -3
    role: master
    transport: ipv4
  spanning_tree_portfast: edge
  peer: video-endpoint
  peer_interface: PCI2
  peer_type: server
  switchport:
    enabled: true
    mode: access
    access_vlan: 11
- name: Ethernet6
  description: SERVER_Endpoint-with-mpass_PCI2
  shutdown: false
  channel_group:
    id: 6
    mode: active
  peer: Endpoint-with-mpass
  peer_interface: PCI2
  peer_type: server
hostname: ptp-tests-leaf2
ip_igmp_snooping:
  globally_enabled: true
ip_routing: true
is_deployed: true
loopback_interfaces:
- name: Loopback0
  description: ROUTER_ID
  shutdown: false
  ip_address: 10.254.1.2/32
- name: Loopback1
  description: VXLAN_TUNNEL_SOURCE
  shutdown: false
  ip_address: 10.254.11.1/32
management_api_http:
  enable_https: true
  enable_vrfs:
  - name: MGMT
management_interfaces:
- name: Management1
  description: OOB_MANAGEMENT
  shutdown: false
  vrf: MGMT
  ip_address: 192.168.0.102/24
  type: oob
  gateway: 192.168.0.1
metadata:
  platform: vEOS-lab
mlag_configuration:
  domain_id: ptp-test-leaf
  local_interface: Vlan4094
  peer_address: 10.254.1.64
  peer_link: Port-Channel9
  reload_delay_mlag: '300'
  reload_delay_non_mlag: '330'
port_channel_interfaces:
- name: Port-Channel9
  description: MLAG_ptp-tests-leaf1_Port-Channel9
  shutdown: false
  ptp:
    enable: true
    announce:
      interval: 0
      timeout: 3
    delay_req: -3
    sync_message:
      interval: -3
    transport: ipv4
  switchport:
    enabled: true
    mode: trunk
    trunk:
      groups:
      - MLAG
- name: Port-Channel11
  description: L2_ptp-tests-l2leaf1-ptp-disabled_Port-Channel1
  shutdown: false
  mlag: 11
  switchport:
    enabled: true
    mode: trunk
    trunk:
      allowed_vlan: '11'
- name: Port-Channel12
  description: L2_ptp-tests-l2leaf2-ptp-enabled_Port-Channel1
  shutdown: false
  mlag: 12
  ptp:
    enable: true
    announce:
      interval: 0
      timeout: 3
    delay_req: -3
    sync_message:
      interval: -3
    transport: ipv4
  switchport:
    enabled: true
    mode: trunk
    trunk:
      allowed_vlan: '11'
- name: Port-Channel14
  description: L2_ptp-tests-l2leaf2-ptp-enabled-uplink-disabled_Port-Channel1
  shutdown: false
  mlag: 14
  switchport:
    enabled: true
    mode: trunk
    trunk:
      allowed_vlan: '11'
- name: Port-Channel6
  description: SERVER_Endpoint-with-mpass
  shutdown: false
  mlag: 6
  ptp:
    enable: true
    announce:
      interval: 0
      timeout: 3
    delay_req: -3
    sync_message:
      interval: -3
    role: master
    transport: ipv4
    mpass: true
  switchport:
    enabled: true
    mode: access
    access_vlan: 11
prefix_lists:
- name: PL-LOOPBACKS-EVPN-OVERLAY
  sequence_numbers:
  - sequence: 10
    action: permit 10.254.1.0/27 eq 32
  - sequence: 20
    action: permit 10.254.11.0/27 eq 32
- name: PL-MLAG-PEER-VRFS
  sequence_numbers:
  - sequence: 10
    action: permit 10.254.1.96/31
ptp:
  mode: boundary
  forward_unicast: true
  source:
    ip: 10.254.1.2
  priority1: 40
  priority2: 1
  ttl: 16
  domain: 127
  message_type:
    general:
      dscp: 46
    event:
      dscp: 48
  monitor:
    enabled: true
    threshold:
      offset_from_master: 1234
      mean_path_delay: 4567
    missing_message:
      intervals:
        announce: 10
        follow_up: 9
        sync: 8
      sequence_ids:
        enabled: true
        announce: 11
        delay_resp: 12
        follow_up: 13
        sync: 14
route_maps:
- name: RM-MLAG-PEER-IN
  sequence_numbers:
  - sequence: 10
    type: permit
    description: Make routes learned over MLAG Peer-link less preferred on spines to ensure optimal routing
    set:
    - origin incomplete
- name: RM-CONN-2-BGP
  sequence_numbers:
  - sequence: 10
    type: permit
    match:
    - ip address prefix-list PL-LOOPBACKS-EVPN-OVERLAY
- name: RM-CONN-2-BGP-VRFS
  sequence_numbers:
  - sequence: 10
    type: deny
    match:
    - ip address prefix-list PL-MLAG-PEER-VRFS
  - sequence: 20
    type: permit
router_bfd:
  multihop:
    interval: 300
    min_rx: 300
    multiplier: 3
router_bgp:
  as: '65102'
  router_id: 10.254.1.2
  maximum_paths:
    paths: 4
    ecmp: 4
  bgp:
    default:
      ipv4_unicast: false
  peer_groups:
  - name: MLAG-IPv4-UNDERLAY-PEER
    type: ipv4
    remote_as: '65102'
    description: ptp-tests-leaf1
    next_hop_self: true
    send_community: all
    maximum_routes: 12000
    route_map_in: RM-MLAG-PEER-IN
  - name: IPv4-UNDERLAY-PEERS
    type: ipv4
    send_community: all
    maximum_routes: 12000
  - name: EVPN-OVERLAY-PEERS
    type: evpn
    update_source: Loopback0
    bfd: true
    ebgp_multihop: 3
    send_community: all
    maximum_routes: 0
  neighbors:
  - ip_address: 10.254.1.96
    peer_group: MLAG-IPv4-UNDERLAY-PEER
    peer: ptp-tests-leaf1
    description: ptp-tests-leaf1_Vlan4093
  - ip_address: 10.254.2.4
    peer_group: IPv4-UNDERLAY-PEERS
    remote_as: '65200'
    peer: ptp-tests-spine1
    description: ptp-tests-spine1_Ethernet3
  - ip_address: 10.254.2.6
    peer_group: IPv4-UNDERLAY-PEERS
    remote_as: '65200'
    peer: ptp-tests-spine1
    description: ptp-tests-spine1_Ethernet4
  - ip_address: 10.255.0.1
    peer_group: EVPN-OVERLAY-PEERS
    remote_as: '65200'
    peer: ptp-tests-spine1
    description: ptp-tests-spine1_Loopback0
  redistribute:
    connected:
      enabled: true
      route_map: RM-CONN-2-BGP
  vlans:
  - id: 11
    tenant: PTP
    rd: 10.254.1.2:10011
    route_targets:
      both:
      - 10011:10011
    redistribute_routes:
    - learned
  address_family_evpn:
    peer_groups:
    - name: EVPN-OVERLAY-PEERS
      activate: true
  address_family_ipv4:
    peer_groups:
    - name: MLAG-IPv4-UNDERLAY-PEER
      activate: true
    - name: IPv4-UNDERLAY-PEERS
      activate: true
    - name: EVPN-OVERLAY-PEERS
      activate: false
  vrfs:
  - name: VRF1
    rd: 10.254.1.2:1
    route_targets:
      import:
      - address_family: evpn
        route_targets:
        - '1:1'
      export:
      - address_family: evpn
        route_targets:
        - '1:1'
    router_id: 10.254.1.2
    neighbors:
    - ip_address: 10.254.1.96
      peer_group: MLAG-IPv4-UNDERLAY-PEER
      description: ptp-tests-leaf1_Vlan3000
    redistribute:
      connected:
        enabled: true
        route_map: RM-CONN-2-BGP-VRFS
service_routing_protocols_model: multi-agent
spanning_tree:
  mode: mstp
  mst_instances:
  - id: '0'
    priority: 4096
  no_spanning_tree_vlan: 4093-4094
static_routes:
- vrf: MGMT
  destination_address_prefix: 0.0.0.0/0
  gateway: 192.168.0.1
transceiver_qsfp_default_mode_4x10: true
vlan_interfaces:
- name: Vlan4093
  description: MLAG_L3
  shutdown: false
  ip_address: 10.254.1.97/31
  mtu: 9214
- name: Vlan4094
  description: MLAG
  shutdown: false
  ip_address: 10.254.1.65/31
  mtu: 9214
  no_autostate: true
- name: Vlan11
  description: VLAN11
  shutdown: false
  vrf: VRF1
  ip_address: 172.17.11.1/24
  tenant: PTP
- name: Vlan3000
  description: MLAG_L3_VRF_VRF1
  shutdown: false
  vrf: VRF1
  ip_address: 10.254.1.97/31
  mtu: 9214
  tenant: PTP
  type: underlay_peering
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vlans:
- id: 4093
  name: MLAG_L3
  trunk_groups:
  - MLAG
  tenant: system
- id: 4094
  name: MLAG
  trunk_groups:
  - MLAG
  tenant: system
- id: 11
  name: VLAN11
  tenant: PTP
- id: 3000
  name: MLAG_L3_VRF_VRF1
  trunk_groups:
  - MLAG
  tenant: PTP
vrfs:
- name: MGMT
  ip_routing: false
- name: VRF1
  ip_routing: true
  tenant: PTP
vxlan_interface:
  vxlan1:
    description: ptp-tests-leaf2_VTEP
    vxlan:
      source_interface: Loopback1
      udp_port: 4789
      virtual_router_encapsulation_mac_address: mlag-system-id
      vlans:
      - id: 11
        vni: 10011
      vrfs:
      - name: VRF1
        vni: 1
