aaa_root:
  disabled: true
config_end: true
enable_password:
  disabled: true
hostname: RD-RT-ADMIN-SUBFIELD-L3LEAF7
ip_igmp_snooping:
  globally_enabled: true
ip_routing: true
ip_virtual_router_mac_address: 00:dc:00:00:00:0a
is_deployed: true
loopback_interfaces:
- name: Loopback0
  description: ROUTER_ID
  shutdown: false
  ip_address: 192.168.255.7/32
- name: Loopback1
  description: VXLAN_TUNNEL_SOURCE
  shutdown: false
  ip_address: 192.168.254.7/32
management_api_http:
  enable_https: true
  enable_vrfs:
  - name: MGMT
management_interfaces:
- name: Management1
  description: OOB_MANAGEMENT
  shutdown: false
  vrf: MGMT
  ip_address: 192.168.200.107/24
  type: oob
  gateway: 192.168.200.1
metadata:
  platform: vEOS-LAB
prefix_lists:
- name: PL-LOOPBACKS-EVPN-OVERLAY
  sequence_numbers:
  - sequence: 10
    action: permit 192.168.255.0/24 eq 32
  - sequence: 20
    action: permit 192.168.254.0/24 eq 32
route_maps:
- name: RM-CONN-2-BGP
  sequence_numbers:
  - sequence: 10
    type: permit
    match:
    - ip address prefix-list PL-LOOPBACKS-EVPN-OVERLAY
router_bfd:
  multihop:
    interval: 300
    min_rx: 300
    multiplier: 3
router_bgp:
  as: '65007'
  router_id: 192.168.255.7
  maximum_paths:
    paths: 4
    ecmp: 4
  updates:
    wait_install: true
  bgp:
    default:
      ipv4_unicast: false
  peer_groups:
  - name: IPv4-UNDERLAY-PEERS
    type: ipv4
    send_community: all
    maximum_routes: 12000
  - name: EVPN-OVERLAY-PEERS
    type: evpn
    update_source: Loopback0
    bfd: true
    ebgp_multihop: 3
    send_community: all
    maximum_routes: 0
  redistribute:
    connected:
      enabled: true
      route_map: RM-CONN-2-BGP
  vlans:
  - id: 1
    tenant: Tenant_A
    rd: 4294967295:10001
    route_targets:
      both:
      - 10001:10001
    redistribute_routes:
    - learned
  - id: 2
    tenant: Tenant_A
    rd: 4294967295:10002
    route_targets:
      both:
      - 10002:10002
    redistribute_routes:
    - learned
  - id: 3
    tenant: Tenant_A
    rd: 4294967295:33333
    route_targets:
      both:
      - 3333:3333
    redistribute_routes:
    - learned
  - id: 4
    tenant: Tenant_A
    rd: 33333:33333
    route_targets:
      both:
      - 3333:3333
    redistribute_routes:
    - learned
  address_family_evpn:
    peer_groups:
    - name: EVPN-OVERLAY-PEERS
      activate: true
  address_family_ipv4:
    peer_groups:
    - name: IPv4-UNDERLAY-PEERS
      activate: true
    - name: EVPN-OVERLAY-PEERS
      activate: false
  vrfs:
  - name: TEST1
    rd: '4294967295:11'
    route_targets:
      import:
      - address_family: evpn
        route_targets:
        - '11:11'
      export:
      - address_family: evpn
        route_targets:
        - '11:11'
    router_id: 192.168.255.7
    redistribute:
      connected:
        enabled: true
service_routing_protocols_model: multi-agent
static_routes:
- vrf: MGMT
  destination_address_prefix: 0.0.0.0/0
  gateway: 192.168.200.1
transceiver_qsfp_default_mode_4x10: true
vlan_interfaces:
- name: Vlan1
  description: VLAN_1
  shutdown: false
  vrf: TEST1
  ip_address_virtual: 10.0.1.1/24
  tenant: Tenant_A
  tags:
  - test_l3
- name: Vlan2
  description: VLAN_2
  shutdown: false
  vrf: TEST1
  ip_address_virtual: 10.0.2.1/24
  tenant: Tenant_A
  tags:
  - test_l3
- name: Vlan3
  description: VLAN_3
  shutdown: false
  vrf: TEST1
  ip_address_virtual: 10.0.3.1/24
  tenant: Tenant_A
  tags:
  - test_l3
- name: Vlan4
  description: VLAN_4
  shutdown: false
  vrf: TEST1
  ip_address_virtual: 10.0.4.1/24
  tenant: Tenant_A
  tags:
  - test_l3
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vlans:
- id: 1
  name: VLAN_1
  tenant: Tenant_A
- id: 2
  name: VLAN_2
  tenant: Tenant_A
- id: 3
  name: VLAN_3
  tenant: Tenant_A
- id: 4
  name: VLAN_4
  tenant: Tenant_A
vrfs:
- name: MGMT
  ip_routing: false
- name: TEST1
  description: TEST1
  ip_routing: true
  tenant: Tenant_A
vxlan_interface:
  vxlan1:
    description: RD-RT-ADMIN-SUBFIELD-L3LEAF7_VTEP
    vxlan:
      source_interface: Loopback1
      udp_port: 4789
      vlans:
      - id: 1
        vni: 80001
      - id: 2
        vni: 80002
      - id: 3
        vni: 80003
      - id: 4
        vni: 80004
      vrfs:
      - name: TEST1
        vni: 22
