aaa_root:
  disabled: true
config_end: true
enable_password:
  disabled: true
ethernet_interfaces:
- name: Ethernet1
  description: P2P_sflow-tests-leaf1_Ethernet1
  shutdown: false
  mtu: 9214
  ip_address: 10.254.2.0/31
  peer: sflow-tests-leaf1
  peer_interface: Ethernet1
  peer_type: l3leaf
  sflow:
    enable: true
  switchport:
    enabled: false
- name: Ethernet2
  description: P2P_sflow-tests-leaf1_Ethernet2
  shutdown: false
  mtu: 9214
  ip_address: 10.254.2.2/31
  peer: sflow-tests-leaf1
  peer_interface: Ethernet2
  peer_type: l3leaf
  sflow:
    enable: true
  switchport:
    enabled: false
- name: Ethernet3
  description: P2P_sflow-tests-leaf2_Ethernet1
  shutdown: false
  mtu: 9214
  ip_address: 10.254.2.4/31
  peer: sflow-tests-leaf2
  peer_interface: Ethernet1
  peer_type: l3leaf
  sflow:
    enable: true
  switchport:
    enabled: false
- name: Ethernet4
  description: P2P_sflow-tests-leaf2_Ethernet2
  shutdown: false
  mtu: 9214
  ip_address: 10.254.2.6/31
  peer: sflow-tests-leaf2
  peer_interface: Ethernet2
  peer_type: l3leaf
  sflow:
    enable: true
  switchport:
    enabled: false
- name: Ethernet5
  description: P2P_sflow-tests-leaf3_Ethernet1
  shutdown: false
  mtu: 9214
  ip_address: 10.254.2.16/31
  peer: sflow-tests-leaf3
  peer_interface: Ethernet1
  peer_type: l3leaf
  sflow:
    enable: true
  switchport:
    enabled: false
- name: Ethernet6
  description: P2P_sflow-tests-leaf3_Ethernet2
  shutdown: false
  mtu: 9214
  ip_address: 10.254.2.18/31
  peer: sflow-tests-leaf3
  peer_interface: Ethernet2
  peer_type: l3leaf
  sflow:
    enable: true
  switchport:
    enabled: false
- name: Ethernet7
  description: P2P_sflow-tests-leaf4_Ethernet1
  shutdown: false
  mtu: 9214
  ip_address: 10.254.2.20/31
  peer: sflow-tests-leaf4
  peer_interface: Ethernet1
  peer_type: l3leaf
  sflow:
    enable: true
  switchport:
    enabled: false
- name: Ethernet8
  description: P2P_sflow-tests-leaf4_Ethernet2
  shutdown: false
  mtu: 9214
  ip_address: 10.254.2.22/31
  peer: sflow-tests-leaf4
  peer_interface: Ethernet2
  peer_type: l3leaf
  sflow:
    enable: true
  switchport:
    enabled: false
- name: Ethernet9
  description: P2P_sflow-tests-spine2_Ethernet9
  shutdown: false
  mtu: 9214
  peer: sflow-tests-spine2
  peer_interface: Ethernet9
  peer_type: spine
  sflow:
    enable: true
  switchport:
    enabled: false
- name: Ethernet10
  description: P2P_sflow-tests-spine2_Ethernet10
  shutdown: false
  mtu: 9214
  peer: sflow-tests-spine2
  peer_interface: Ethernet10
  peer_type: spine
  sflow:
    enable: false
  switchport:
    enabled: false
- name: Ethernet11
  description: P2P_sflow-tests-spine2_Ethernet11
  shutdown: false
  mtu: 9214
  peer: sflow-tests-spine2
  peer_interface: Ethernet11
  peer_type: spine
  sflow:
    enable: true
  switchport:
    enabled: false
- name: Ethernet12
  description: P2P_sflow-tests-spine2_Ethernet12
  shutdown: false
  mtu: 9214
  peer: sflow-tests-spine2
  peer_interface: Ethernet12
  peer_type: spine
  sflow:
    enable: true
  switchport:
    enabled: false
- name: Ethernet13
  description: P2P_sflow-tests-spine2_Ethernet13
  shutdown: false
  mtu: 9214
  peer: sflow-tests-spine2
  peer_interface: Ethernet13
  peer_type: spine
  sflow:
    enable: false
  switchport:
    enabled: false
- name: Ethernet14
  description: P2P_sflow-tests-spine2_Ethernet14
  shutdown: false
  mtu: 9214
  peer: sflow-tests-spine2
  peer_interface: Ethernet14
  peer_type: spine
  sflow:
    enable: true
  switchport:
    enabled: false
hostname: sflow-tests-spine1
ip_routing: true
is_deployed: true
loopback_interfaces:
- name: Loopback0
  description: ROUTER_ID
  shutdown: false
  ip_address: 10.255.0.1/32
management_api_http:
  enable_https: true
  enable_vrfs:
  - name: MGMT
management_interfaces:
- name: Management1
  description: OOB_MANAGEMENT
  shutdown: false
  vrf: MGMT
  ip_address: 192.168.0.11/24
  type: oob
  gateway: 192.168.0.1
metadata:
  platform: vEOS-LAB
prefix_lists:
- name: PL-LOOPBACKS-EVPN-OVERLAY
  sequence_numbers:
  - sequence: 10
    action: permit 10.255.0.0/27 eq 32
route_maps:
- name: RM-CONN-2-BGP
  sequence_numbers:
  - sequence: 10
    type: permit
    match:
    - ip address prefix-list PL-LOOPBACKS-EVPN-OVERLAY
router_bfd:
  multihop:
    interval: 300
    min_rx: 300
    multiplier: 3
router_bgp:
  as: '65200'
  router_id: 10.255.0.1
  maximum_paths:
    paths: 4
    ecmp: 4
  updates:
    wait_install: true
  bgp:
    default:
      ipv4_unicast: false
  peer_groups:
  - name: IPv4-UNDERLAY-PEERS
    type: ipv4
    send_community: all
    maximum_routes: 12000
  - name: EVPN-OVERLAY-PEERS
    type: evpn
    next_hop_unchanged: true
    update_source: Loopback0
    bfd: true
    ebgp_multihop: 3
    send_community: all
    maximum_routes: 0
  neighbors:
  - ip_address: 10.254.2.1
    peer_group: IPv4-UNDERLAY-PEERS
    remote_as: '65101'
    peer: sflow-tests-leaf1
    description: sflow-tests-leaf1_Ethernet1
  - ip_address: 10.254.2.3
    peer_group: IPv4-UNDERLAY-PEERS
    remote_as: '65101'
    peer: sflow-tests-leaf1
    description: sflow-tests-leaf1_Ethernet2
  - ip_address: 10.254.2.5
    peer_group: IPv4-UNDERLAY-PEERS
    remote_as: '65102'
    peer: sflow-tests-leaf2
    description: sflow-tests-leaf2_Ethernet1
  - ip_address: 10.254.2.7
    peer_group: IPv4-UNDERLAY-PEERS
    remote_as: '65102'
    peer: sflow-tests-leaf2
    description: sflow-tests-leaf2_Ethernet2
  - ip_address: 10.254.2.17
    peer_group: IPv4-UNDERLAY-PEERS
    remote_as: '65105'
    peer: sflow-tests-leaf3
    description: sflow-tests-leaf3_Ethernet1
  - ip_address: 10.254.2.19
    peer_group: IPv4-UNDERLAY-PEERS
    remote_as: '65105'
    peer: sflow-tests-leaf3
    description: sflow-tests-leaf3_Ethernet2
  - ip_address: 10.254.2.21
    peer_group: IPv4-UNDERLAY-PEERS
    remote_as: '65105'
    peer: sflow-tests-leaf4
    description: sflow-tests-leaf4_Ethernet1
  - ip_address: 10.254.2.23
    peer_group: IPv4-UNDERLAY-PEERS
    remote_as: '65105'
    peer: sflow-tests-leaf4
    description: sflow-tests-leaf4_Ethernet2
  - ip_address: 10.254.1.1
    peer_group: EVPN-OVERLAY-PEERS
    remote_as: '65101'
    peer: sflow-tests-leaf1
    description: sflow-tests-leaf1_Loopback0
  - ip_address: 10.254.1.2
    peer_group: EVPN-OVERLAY-PEERS
    remote_as: '65102'
    peer: sflow-tests-leaf2
    description: sflow-tests-leaf2_Loopback0
  - ip_address: 10.254.1.5
    peer_group: EVPN-OVERLAY-PEERS
    remote_as: '65105'
    peer: sflow-tests-leaf3
    description: sflow-tests-leaf3_Loopback0
  - ip_address: 10.254.1.6
    peer_group: EVPN-OVERLAY-PEERS
    remote_as: '65105'
    peer: sflow-tests-leaf4
    description: sflow-tests-leaf4_Loopback0
  redistribute:
    connected:
      enabled: true
      route_map: RM-CONN-2-BGP
  address_family_evpn:
    peer_groups:
    - name: EVPN-OVERLAY-PEERS
      activate: true
  address_family_ipv4:
    peer_groups:
    - name: IPv4-UNDERLAY-PEERS
      activate: true
    - name: EVPN-OVERLAY-PEERS
      activate: false
service_routing_protocols_model: multi-agent
sflow:
  vrfs:
  - name: MGMT
    destinations:
    - destination: 10.10.10.10
    - destination: 10.10.10.11
    source_interface: Management1
  - name: sflowvrf
    destinations:
    - destination: 10.10.10.12
      port: 1234
    source_interface: Loopback321
  run: true
spanning_tree:
  mode: none
static_routes:
- vrf: MGMT
  destination_address_prefix: 0.0.0.0/0
  gateway: 192.168.0.1
transceiver_qsfp_default_mode_4x10: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vrfs:
- name: MGMT
  ip_routing: false
