aaa_root:
  disabled: true
config_end: true
enable_password:
  disabled: true
ethernet_interfaces:
- name: Ethernet25
  description: MLAG_SL-LEAF0B_Ethernet25
  shutdown: false
  channel_group:
    id: 25
    mode: active
  peer: SL-LEAF0B
  peer_interface: Ethernet25
  peer_type: mlag_peer
- name: Ethernet26
  description: MLAG_SL-LEAF0B_Ethernet26
  shutdown: false
  channel_group:
    id: 25
    mode: active
  peer: SL-LEAF0B
  peer_interface: Ethernet26
  peer_type: mlag_peer
hostname: SL-LEAF0A
ip_igmp_snooping:
  globally_enabled: true
is_deployed: true
management_api_http:
  enable_https: true
  enable_vrfs:
  - name: MGMT
metadata:
  platform: vEOS-LAB
mlag_configuration:
  domain_id: SL-LEAF0
  local_interface: Vlan4094
  peer_address: 10.10.255.1
  peer_link: Port-Channel25
  reload_delay_mlag: '300'
  reload_delay_non_mlag: '330'
port_channel_interfaces:
- name: Port-Channel25
  description: MLAG_SL-LEAF0B_Port-Channel25
  shutdown: false
  switchport:
    enabled: true
    mode: trunk
    trunk:
      groups:
      - MLAG
service_routing_protocols_model: multi-agent
spanning_tree:
  no_spanning_tree_vlan: '4094'
transceiver_qsfp_default_mode_4x10: true
vlan_interfaces:
- name: Vlan4094
  description: MLAG
  shutdown: false
  ip_address: 10.10.255.0/31
  mtu: 9214
  no_autostate: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vlans:
- id: 4094
  name: MLAG
  trunk_groups:
  - MLAG
  tenant: system
vrfs:
- name: MGMT
  ip_routing: false
