aaa_root:
  disabled: true
config_end: true
enable_password:
  disabled: true
ethernet_interfaces:
- name: Ethernet25
  description: MLAG_SL-LEAF1B_Ethernet25
  shutdown: false
  channel_group:
    id: 25
    mode: active
  peer: SL-LEAF1B
  peer_interface: Ethernet25
  peer_type: mlag_peer
- name: Ethernet26
  description: MLAG_SL-LEAF1B_Ethernet26
  shutdown: false
  channel_group:
    id: 25
    mode: active
  peer: SL-LEAF1B
  peer_interface: Ethernet26
  peer_type: mlag_peer
- name: Ethernet27
  description: L2_SL-LEAF0B_Ethernet27
  shutdown: false
  channel_group:
    id: 27
    mode: active
  peer: SL-LEAF0B
  peer_interface: Ethernet27
  peer_type: l2leaf
- name: Ethernet28
  description: L2_SL-MLEAF1_Ethernet16
  shutdown: false
  channel_group:
    id: 28
    mode: active
  peer: SL-MLEAF1
  peer_interface: Ethernet16
  peer_type: l2leaf
hostname: SL-LEAF1A
ip_igmp_snooping:
  globally_enabled: true
is_deployed: true
management_api_http:
  enable_https: true
  enable_vrfs:
  - name: MGMT
metadata:
  platform: vEOS-LAB
mlag_configuration:
  domain_id: SL-LEAF1
  local_interface: Vlan4094
  peer_address: 10.10.255.5
  peer_link: Port-Channel25
  reload_delay_mlag: '300'
  reload_delay_non_mlag: '330'
port_channel_interfaces:
- name: Port-Channel25
  description: MLAG_SL-LEAF1B_Port-Channel25
  shutdown: false
  switchport:
    enabled: true
    mode: trunk
    trunk:
      groups:
      - MLAG
- name: Port-Channel27
  description: L2_SL-LEAF0_Port-Channel27
  shutdown: false
  mlag: 27
  switchport:
    enabled: true
    mode: trunk
    trunk:
      allowed_vlan: none
- name: Port-Channel28
  description: L2_SL-MLEAF1_Port-Channel16
  shutdown: false
  mlag: 28
  switchport:
    enabled: true
    mode: trunk
    trunk:
      allowed_vlan: none
service_routing_protocols_model: multi-agent
spanning_tree:
  no_spanning_tree_vlan: '4094'
transceiver_qsfp_default_mode_4x10: true
vlan_interfaces:
- name: Vlan4094
  description: MLAG
  shutdown: false
  ip_address: 10.10.255.4/31
  mtu: 9214
  no_autostate: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vlans:
- id: 4094
  name: MLAG
  trunk_groups:
  - MLAG
  tenant: system
vrfs:
- name: MGMT
  ip_routing: false
