aaa_root:
  disabled: true
config_end: true
enable_password:
  disabled: true
ethernet_interfaces:
- name: Ethernet1
  description: P2P_underlay_filter_peer_as_evpn_1_Ethernet2
  shutdown: false
  mtu: 9214
  ip_address: 192.168.153.2/31
  peer: underlay_filter_peer_as_evpn_1
  peer_interface: Ethernet2
  peer_type: l3leaf
  switchport:
    enabled: false
hostname: underlay_filter_peer_as_evpn_3
ip_igmp_snooping:
  globally_enabled: true
ip_routing: true
ip_virtual_router_mac_address: 00:dc:00:00:00:0a
is_deployed: true
loopback_interfaces:
- name: Loopback0
  description: ROUTER_ID
  shutdown: false
  ip_address: 192.168.255.3/32
- name: Loopback1
  description: VXLAN_TUNNEL_SOURCE
  shutdown: false
  ip_address: 192.168.254.3/32
management_api_http:
  enable_https: true
  enable_vrfs:
  - name: MGMT
prefix_lists:
- name: PL-LOOPBACKS-EVPN-OVERLAY
  sequence_numbers:
  - sequence: 10
    action: permit 192.168.255.0/24 eq 32
  - sequence: 20
    action: permit 192.168.254.0/24 eq 32
route_maps:
- name: RM-CONN-2-BGP
  sequence_numbers:
  - sequence: 10
    type: permit
    match:
    - ip address prefix-list PL-LOOPBACKS-EVPN-OVERLAY
- name: RM-BGP-AS64512-OUT
  sequence_numbers:
  - sequence: 10
    type: deny
    match:
    - as 64512
  - sequence: 20
    type: permit
router_bfd:
  multihop:
    interval: 300
    min_rx: 300
    multiplier: 3
router_bgp:
  as: '64513'
  router_id: 192.168.255.3
  maximum_paths:
    paths: 4
    ecmp: 4
  updates:
    wait_install: true
  bgp:
    default:
      ipv4_unicast: false
  peer_groups:
  - name: IPv4-UNDERLAY-PEERS
    type: ipv4
    send_community: all
    maximum_routes: 12000
  - name: EVPN-OVERLAY-PEERS
    type: evpn
    next_hop_unchanged: true
    update_source: Loopback0
    bfd: true
    ebgp_multihop: 3
    send_community: all
    maximum_routes: 0
  neighbors:
  - ip_address: 192.168.153.3
    peer_group: IPv4-UNDERLAY-PEERS
    remote_as: '64512'
    peer: underlay_filter_peer_as_evpn_1
    description: underlay_filter_peer_as_evpn_1_Ethernet2
    route_map_out: RM-BGP-AS64512-OUT
  - ip_address: 192.168.255.1
    peer_group: EVPN-OVERLAY-PEERS
    remote_as: '64512'
    peer: underlay_filter_peer_as_evpn_1
    description: underlay_filter_peer_as_evpn_1_Loopback0
  redistribute:
    connected:
      enabled: true
      route_map: RM-CONN-2-BGP
  address_family_evpn:
    peer_groups:
    - name: EVPN-OVERLAY-PEERS
      activate: true
  address_family_ipv4:
    peer_groups:
    - name: IPv4-UNDERLAY-PEERS
      activate: true
    - name: EVPN-OVERLAY-PEERS
      activate: false
service_routing_protocols_model: multi-agent
transceiver_qsfp_default_mode_4x10: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vrfs:
- name: MGMT
  ip_routing: false
vxlan_interface:
  vxlan1:
    description: underlay_filter_peer_as_evpn_3_VTEP
    vxlan:
      source_interface: Loopback1
      udp_port: 4789
