aaa_root:
  disabled: true
config_end: true
enable_password:
  disabled: true
ethernet_interfaces:
- name: Ethernet1
  description: P2P_UNDERLAY_FILTER_PEER_AS_L3LEAF1_Ethernet1
  shutdown: false
  mtu: 9214
  ip_address: 192.168.0.0/31
  peer: UNDERLAY_FILTER_PEER_AS_L3LEAF1
  peer_interface: Ethernet1
  peer_type: l3leaf
  switchport:
    enabled: false
hostname: UNDERLAY_FILTER_PEER_AS_SPINE1
ip_routing: true
is_deployed: true
loopback_interfaces:
- name: Loopback0
  description: ROUTER_ID
  shutdown: false
  ip_address: 192.168.255.1/32
management_api_http:
  enable_https: true
  enable_vrfs:
  - name: MGMT
prefix_lists:
- name: PL-LOOPBACKS-EVPN-OVERLAY
  sequence_numbers:
  - sequence: 10
    action: permit 192.168.255.0/24 eq 32
route_maps:
- name: RM-CONN-2-BGP
  sequence_numbers:
  - sequence: 10
    type: permit
    match:
    - ip address prefix-list PL-LOOPBACKS-EVPN-OVERLAY
- name: RM-BGP-AS65001-OUT
  sequence_numbers:
  - sequence: 10
    type: deny
    match:
    - as 65001
  - sequence: 20
    type: permit
router_bgp:
  as: '65000'
  router_id: 192.168.255.1
  maximum_paths:
    paths: 4
    ecmp: 4
  updates:
    wait_install: true
  bgp:
    default:
      ipv4_unicast: false
  peer_groups:
  - name: IPv4-UNDERLAY-PEERS
    type: ipv4
    send_community: all
    maximum_routes: 12000
  neighbors:
  - ip_address: 192.168.0.1
    peer_group: IPv4-UNDERLAY-PEERS
    remote_as: '65001'
    peer: UNDERLAY_FILTER_PEER_AS_L3LEAF1
    description: UNDERLAY_FILTER_PEER_AS_L3LEAF1_Ethernet1
    route_map_out: RM-BGP-AS65001-OUT
  redistribute:
    connected:
      enabled: true
      route_map: RM-CONN-2-BGP
  address_family_ipv4:
    peer_groups:
    - name: IPv4-UNDERLAY-PEERS
      activate: true
service_routing_protocols_model: multi-agent
spanning_tree:
  mode: none
transceiver_qsfp_default_mode_4x10: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vrfs:
- name: MGMT
  ip_routing: false
