aaa_root:
  disabled: true
config_end: true
enable_password:
  disabled: true
ethernet_interfaces:
- name: Ethernet1
  description: L2_uplink_lan_wan_router1_Ethernet2
  shutdown: false
  flow_tracker:
    sampled: FLOW-TRACKER
  spanning_tree_portfast: edge
  peer: uplink_lan_wan_router1
  peer_interface: Ethernet2
  peer_type: wan_router
  switchport:
    enabled: true
    mode: trunk
    trunk:
      allowed_vlan: 10,100
      native_vlan: 10
- name: Ethernet2
  description: L2_uplink_lan_wan_router2_Ethernet2
  shutdown: false
  flow_tracker:
    sampled: FLOW-TRACKER
  spanning_tree_portfast: edge
  peer: uplink_lan_wan_router2
  peer_interface: Ethernet2
  peer_type: wan_router
  switchport:
    enabled: true
    mode: trunk
    trunk:
      allowed_vlan: 10,100
flow_tracking:
  sampled:
    sample: 10000
    trackers:
    - record_export:
        on_inactive_timeout: 70000
        on_interval: 300000
      name: FLOW-TRACKER
      exporters:
      - name: CV-TELEMETRY
        collector:
          host: 127.0.0.1
        local_interface: Loopback0
        template_interval: 3600000
    shutdown: false
hostname: uplink_lan_l2leaf
ip_igmp_snooping:
  globally_enabled: true
is_deployed: true
management_api_http:
  enable_https: true
  enable_vrfs:
  - name: MGMT
service_routing_protocols_model: multi-agent
transceiver_qsfp_default_mode_4x10: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vlans:
- id: 10
  name: VLAN10_NATIVE
  tenant: TEST
- id: 100
  name: VLAN100
  tenant: TEST
- id: 102
  name: VLAN102
  tenant: TEST
vrfs:
- name: MGMT
  ip_routing: false
