aaa_root:
  disabled: true
config_end: true
enable_password:
  disabled: true
ethernet_interfaces:
- name: Ethernet1
  description: L2_uplink-native-vlan-parent_Ethernet1
  shutdown: false
  channel_group:
    id: 1
    mode: active
  peer: uplink-native-vlan-parent
  peer_interface: Ethernet1
  peer_type: l2leaf
hostname: uplink-native-vlan-grandparent
ip_igmp_snooping:
  globally_enabled: true
is_deployed: true
management_api_http:
  enable_https: true
  enable_vrfs:
  - name: MGMT
port_channel_interfaces:
- name: Port-Channel1
  description: L2_uplink-native-vlan-parent_Port-Channel1
  shutdown: false
  switchport:
    enabled: true
    mode: trunk
    trunk:
      allowed_vlan: '100'
      native_vlan: 100
service_routing_protocols_model: multi-agent
transceiver_qsfp_default_mode_4x10: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vlans:
- id: 100
  name: NETWORK_SERVICES_VLAN
  tenant: test
vrfs:
- name: MGMT
  ip_routing: false
