aaa_root:
  disabled: true
config_end: true
enable_password:
  disabled: true
ethernet_interfaces:
- name: Ethernet1
  description: L2_UPLINK_P2P_VRFS_TESTS_LEAF1_Ethernet51
  shutdown: false
  channel_group:
    id: 1
    mode: active
  peer: UPLINK_P2P_VRFS_TESTS_LEAF1
  peer_interface: Ethernet51
  peer_type: l3leaf
- name: Ethernet2
  description: L2_UPLINK_P2P_VRFS_TESTS_LEAF1_Ethernet52
  shutdown: false
  channel_group:
    id: 1
    mode: active
  peer: UPLINK_P2P_VRFS_TESTS_LEAF1
  peer_interface: Ethernet52
  peer_type: l3leaf
- name: Ethernet10
  shutdown: false
  peer_type: network_port
  switchport:
    enabled: true
hostname: UPLINK_P2P_VRFS_TESTS_L2LEAF1
ip_igmp_snooping:
  globally_enabled: true
is_deployed: true
management_api_http:
  enable_https: true
  enable_vrfs:
  - name: MGMT
metadata:
  platform: vEOS-LAB
port_channel_interfaces:
- name: Port-Channel1
  description: L2_UPLINK_P2P_VRFS_TESTS_LEAF1_Port-Channel51
  shutdown: false
  switchport:
    enabled: true
    mode: trunk
    trunk:
      allowed_vlan: '66'
service_routing_protocols_model: multi-agent
transceiver_qsfp_default_mode_4x10: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vlans:
- id: 66
  name: TEST-L2VLAN-ATTRACTION
  tenant: TenantC
vrfs:
- name: MGMT
  ip_routing: false
