aaa_root:
  disabled: true
agents:
- name: KernelFib
  environment_variables:
  - name: KERNELFIB_PROGRAM_ALL_ECMP
    value: '1'
application_traffic_recognition:
  field_sets:
    ipv4_prefixes:
    - name: PFX-PATHFINDERS
      prefix_values:
      - 10.255.255.10/32
      - 10.255.255.20/32
  applications:
    ipv4_applications:
    - name: APP-CONTROL-PLANE
      dest_prefix_set_name: PFX-PATHFINDERS
  application_profiles:
  - name: APP-PROFILE-CONTROL-PLANE
    applications:
    - name: APP-CONTROL-PLANE
as_path:
  access_lists:
  - name: ASPATH-WAN
    entries:
    - type: permit
      match: '65101'
config_end: true
dns_domain: dc1.local
dps_interfaces:
- name: Dps1
  description: DPS Interface
  mtu: 9194
  ip_address: 10.255.1.2/32
  flow_tracker:
    sampled: FLOW-TRACKER
enable_password:
  disabled: true
ethernet_interfaces:
- name: Ethernet1
  description: P2P_dc1-leaf1a_Ethernet7
  shutdown: false
  mtu: 1500
  ip_address: 10.255.255.5/31
  peer: dc1-leaf1a
  peer_interface: Ethernet7
  peer_type: l3leaf
  switchport:
    enabled: false
- name: Ethernet2
  description: P2P_dc1-leaf1b_Ethernet7
  shutdown: false
  mtu: 1500
  ip_address: 10.255.255.7/31
  peer: dc1-leaf1b
  peer_interface: Ethernet7
  peer_type: l3leaf
  switchport:
    enabled: false
- name: Ethernet3
  description: mpls-sp-1_DC1-MPLS-4
  shutdown: false
  ip_address: 172.18.4.2/24
  peer_type: l3_interface
  switchport:
    enabled: false
- name: Ethernet4
  description: isp-1_DC1-INET-4
  shutdown: false
  ip_address: dhcp
  dhcp_client_accept_default_route: true
  peer_type: l3_interface
  switchport:
    enabled: false
flow_tracking:
  sampled:
    sample: 10000
    trackers:
    - record_export:
        on_inactive_timeout: 70000
        on_interval: 300000
      name: FLOW-TRACKER
      exporters:
      - name: CV-TELEMETRY
        collector:
          host: 127.0.0.1
        local_interface: Loopback0
        template_interval: 3600000
    shutdown: false
hostname: dc1-wan2
ip_extcommunity_lists:
- name: ECL-EVPN-SOO
  entries:
  - type: permit
    extcommunities: soo 10.255.2.1:100
ip_routing: true
ip_security:
  ike_policies:
  - name: DP-IKE-POLICY
    local_id: 10.255.1.2
  - name: CP-IKE-POLICY
    local_id: 10.255.1.2
  sa_policies:
  - name: DP-SA-POLICY
    esp:
      encryption: aes256gcm128
    pfs_dh_group: 14
  - name: CP-SA-POLICY
    esp:
      encryption: aes256gcm128
    pfs_dh_group: 14
  profiles:
  - name: DP-PROFILE
    ike_policy: DP-IKE-POLICY
    sa_policy: DP-SA-POLICY
    connection: start
    shared_key: 0110100A480E0A0E231D1E
    dpd:
      interval: 10
      time: 50
      action: clear
    mode: transport
  - name: CP-PROFILE
    ike_policy: CP-IKE-POLICY
    sa_policy: CP-SA-POLICY
    connection: start
    shared_key: 0110100A480E0A0E231D1E
    dpd:
      interval: 10
      time: 50
      action: clear
    mode: transport
  key_controller:
    profile: DP-PROFILE
is_deployed: true
local_users:
- name: admin
  privilege: 15
  role: network-admin
  no_password: true
- name: ansible
  privilege: 15
  role: network-admin
  sha512_password: $6$7u4j1rkb3VELgcZE$EJt2Qff8kd/TapRoci0XaIZsL4tFzgq1YZBLD9c6f/knXzvcYY0NcMKndZeCv0T268knGKhOEwZAxqKjlMm920
loopback_interfaces:
- name: Loopback0
  description: ROUTER_ID
  shutdown: false
  ip_address: 10.255.2.2/32
management_api_http:
  enable_https: true
  https_ssl_profile: eAPI_SSL_Profile
  enable_vrfs:
  - name: MGMT
management_interfaces:
- name: Management1
  description: OOB_MANAGEMENT
  shutdown: false
  vrf: MGMT
  ip_address: 172.16.1.16/24
  type: oob
  gateway: 172.16.1.1
management_security:
  ssl_profiles:
  - name: STUN-DTLS
    tls_versions: '1.2'
    trust_certificate:
      certificates:
      - aristaDeviceCertProvisionerDefaultRootCA.crt
    certificate:
      file: STUN-DTLS.crt
      key: STUN-DTLS.key
metadata:
  cv_tags:
    device_tags:
    - name: Role
      value: edge
    - name: Region
      value: Global
    - name: Zone
      value: Global-ZONE
    - name: Site
      value: DC1
    interface_tags:
    - interface: Ethernet1
      tags:
      - name: Type
        value: lan
    - interface: Ethernet2
      tags:
      - name: Type
        value: lan
    - interface: Ethernet3
      tags:
      - name: Type
        value: wan
      - name: Carrier
        value: mpls-sp-1
      - name: Circuit
        value: DC1-MPLS-4
    - interface: Ethernet4
      tags:
      - name: Type
        value: wan
      - name: Carrier
        value: isp-1
      - name: Circuit
        value: DC1-INET-4
  cv_pathfinder:
    role: edge
    region: Global
    zone: Global-ZONE
    site: DC1
    vtep_ip: 10.255.1.2
    ssl_profile: STUN-DTLS
    pathfinders:
    - vtep_ip: 10.255.255.10
    - vtep_ip: 10.255.255.20
    interfaces:
    - name: Ethernet3
      carrier: mpls-sp-1
      circuit_id: DC1-MPLS-4
      pathgroup: mpls
    - name: Ethernet4
      carrier: isp-1
      circuit_id: DC1-INET-4
      pathgroup: internet
prefix_lists:
- name: PL-LOOPBACKS-EVPN-OVERLAY
  sequence_numbers:
  - sequence: 10
    action: permit 10.255.2.0/27 eq 32
- name: PL-WAN-HA-PREFIXES
  sequence_numbers:
  - sequence: 10
    action: permit 10.255.255.4/31
  - sequence: 20
    action: permit 10.255.255.6/31
- name: PL-WAN-HA-PEER-PREFIXES
  sequence_numbers:
  - sequence: 10
    action: permit 10.255.255.0/31
  - sequence: 20
    action: permit 10.255.255.2/31
route_maps:
- name: RM-CONN-2-BGP
  sequence_numbers:
  - sequence: 10
    type: permit
    match:
    - ip address prefix-list PL-LOOPBACKS-EVPN-OVERLAY
    set:
    - extcommunity soo 10.255.2.1:100 additive
  - sequence: 50
    type: permit
    match:
    - ip address prefix-list PL-WAN-HA-PREFIXES
- name: RM-BGP-UNDERLAY-PEERS-IN
  sequence_numbers:
  - sequence: 40
    type: permit
    description: Mark prefixes originated from the LAN
    set:
    - extcommunity soo 10.255.2.1:100 additive
  - sequence: 10
    type: permit
    description: Allow WAN HA peer interface prefixes
    match:
    - ip address prefix-list PL-WAN-HA-PEER-PREFIXES
  - sequence: 20
    type: deny
    description: Deny other routes from the HA peer
    match:
    - as-path ASPATH-WAN
- name: RM-BGP-UNDERLAY-PEERS-OUT
  sequence_numbers:
  - sequence: 10
    type: permit
    description: Make routes learned from WAN HA peer less preferred on LAN routers
    match:
    - tag 50
    - route-type internal
    set:
    - metric 50
  - sequence: 20
    type: permit
- name: RM-EVPN-SOO-IN
  sequence_numbers:
  - sequence: 10
    type: deny
    match:
    - extcommunity ECL-EVPN-SOO
  - sequence: 20
    type: permit
- name: RM-EVPN-SOO-OUT
  sequence_numbers:
  - sequence: 10
    type: permit
    set:
    - extcommunity soo 10.255.2.1:100 additive
- name: RM-WAN-HA-PEER-IN
  sequence_numbers:
  - sequence: 10
    type: permit
    description: Set tag 50 on routes received from HA peer over EVPN
    set:
    - tag 50
- name: RM-WAN-HA-PEER-OUT
  sequence_numbers:
  - sequence: 10
    type: permit
    description: Make EVPN routes learned from WAN less preferred on HA peer
    match:
    - route-type internal
    set:
    - local-preference 50
  - sequence: 20
    type: permit
    description: Make locally injected routes less preferred on HA peer
    set:
    - local-preference 75
- name: RM-EVPN-EXPORT-VRF-DEFAULT
  sequence_numbers:
  - sequence: 10
    type: permit
    match:
    - extcommunity ECL-EVPN-SOO
router_adaptive_virtual_topology:
  topology_role: edge
  region:
    name: Global
    id: 1
  zone:
    name: Global-ZONE
    id: 1
  site:
    name: DC1
    id: 100
  profiles:
  - name: DEFAULT-POLICY-CONTROL-PLANE
    load_balance_policy: LB-DEFAULT-POLICY-CONTROL-PLANE
  - name: DEFAULT-POLICY-DEFAULT
    load_balance_policy: LB-DEFAULT-POLICY-DEFAULT
  policies:
  - name: DEFAULT-POLICY-WITH-CP
    matches:
    - application_profile: APP-PROFILE-CONTROL-PLANE
      avt_profile: DEFAULT-POLICY-CONTROL-PLANE
    - application_profile: default
      avt_profile: DEFAULT-POLICY-DEFAULT
  vrfs:
  - name: default
    policy: DEFAULT-POLICY-WITH-CP
    profiles:
    - name: DEFAULT-POLICY-CONTROL-PLANE
      id: 254
    - name: DEFAULT-POLICY-DEFAULT
      id: 1
router_bfd:
  multihop:
    interval: 300
    min_rx: 300
    multiplier: 3
router_bgp:
  as: '65101'
  router_id: 10.255.2.2
  maximum_paths:
    paths: 16
  updates:
    wait_install: true
  bgp:
    default:
      ipv4_unicast: false
  peer_groups:
  - name: IPv4-UNDERLAY-PEERS
    type: ipv4
    password: 7x4B4rnJhZB438m9+BrBfQ==
    send_community: all
    maximum_routes: 12000
    allowas_in:
      enabled: true
      times: 1
    route_map_in: RM-BGP-UNDERLAY-PEERS-IN
    route_map_out: RM-BGP-UNDERLAY-PEERS-OUT
  - name: WAN-OVERLAY-PEERS
    type: wan
    remote_as: '65101'
    update_source: Dps1
    bfd: true
    bfd_timers:
      interval: 1000
      min_rx: 1000
      multiplier: 10
    password: htm4AZe9mIQOO1uiMuGgYQ==
    send_community: all
    maximum_routes: 0
    ttl_maximum_hops: 1
  neighbors:
  - ip_address: 10.255.255.4
    peer_group: IPv4-UNDERLAY-PEERS
    remote_as: '65101'
    peer: dc1-leaf1a
    description: dc1-leaf1a_Ethernet7
  - ip_address: 10.255.255.6
    peer_group: IPv4-UNDERLAY-PEERS
    remote_as: '65101'
    peer: dc1-leaf1b
    description: dc1-leaf1b_Ethernet7
  - ip_address: 10.255.255.10
    peer_group: WAN-OVERLAY-PEERS
    peer: dc1-leaf1a
    description: dc1-leaf1a_Dps1
  - ip_address: 10.255.255.20
    peer_group: WAN-OVERLAY-PEERS
    peer: dc1-leaf1b
    description: dc1-leaf1b_Dps1
  - ip_address: 10.255.1.1
    remote_as: '65101'
    peer: dc1-wan1
    description: dc1-wan1
    route_reflector_client: true
    update_source: Dps1
    route_map_in: RM-WAN-HA-PEER-IN
    route_map_out: RM-WAN-HA-PEER-OUT
    send_community: all
  redistribute:
    connected:
      enabled: true
      route_map: RM-CONN-2-BGP
  address_family_evpn:
    neighbor_default:
      next_hop_self_received_evpn_routes:
        enable: true
    neighbors:
    - ip_address: 10.255.1.1
      activate: true
      encapsulation: path-selection
    peer_groups:
    - name: WAN-OVERLAY-PEERS
      activate: true
      route_map_in: RM-EVPN-SOO-IN
      route_map_out: RM-EVPN-SOO-OUT
      encapsulation: path-selection
  address_family_ipv4:
    peer_groups:
    - name: IPv4-UNDERLAY-PEERS
      activate: true
    - name: WAN-OVERLAY-PEERS
      activate: false
  address_family_ipv4_sr_te:
    peer_groups:
    - name: WAN-OVERLAY-PEERS
      activate: true
  address_family_link_state:
    peer_groups:
    - name: WAN-OVERLAY-PEERS
      activate: true
    path_selection:
      roles:
        producer: true
  address_family_path_selection:
    bgp:
      additional_paths:
        receive: true
        send: any
    peer_groups:
    - name: WAN-OVERLAY-PEERS
      activate: true
  vrfs:
  - name: default
    rd: 10.255.2.2:1
    route_targets:
      import:
      - address_family: evpn
        route_targets:
        - '1:1'
      export:
      - address_family: evpn
        route_targets:
        - '1:1'
        - route-map RM-EVPN-EXPORT-VRF-DEFAULT
router_path_selection:
  path_groups:
  - name: mpls
    id: 101
    ipsec_profile: CP-PROFILE
    local_interfaces:
    - name: Ethernet3
      stun:
        server_profiles:
        - mpls-dc1-leaf1a-Ethernet6
        - mpls-dc1-leaf1b-Ethernet6
    dynamic_peers:
      enabled: true
    static_peers:
    - router_ip: 10.255.255.10
      name: dc1-leaf1a
      ipv4_addresses:
      - 172.18.1.2
    - router_ip: 10.255.255.20
      name: dc1-leaf1b
      ipv4_addresses:
      - 172.18.2.2
  - name: internet
    id: 102
    ipsec_profile: CP-PROFILE
    local_interfaces:
    - name: Ethernet4
      stun:
        server_profiles:
        - internet-dc1-leaf1a-Ethernet7
        - internet-dc1-leaf1b-Ethernet7
    dynamic_peers:
      enabled: true
    static_peers:
    - router_ip: 10.255.255.10
      name: dc1-leaf1a
      ipv4_addresses:
      - 100.64.1.2
    - router_ip: 10.255.255.20
      name: dc1-leaf1b
      ipv4_addresses:
      - 100.64.2.2
  - name: LAN_HA
    id: 65535
    ipsec_profile: DP-PROFILE
    flow_assignment: lan
    local_interfaces:
    - name: Ethernet1
    - name: Ethernet2
    static_peers:
    - router_ip: 10.255.1.1
      name: dc1-wan1
      ipv4_addresses:
      - 10.255.255.1
      - 10.255.255.3
  load_balance_policies:
  - name: LB-DEFAULT-POLICY-CONTROL-PLANE
    path_groups:
    - name: internet
    - name: mpls
    - name: LAN_HA
  - name: LB-DEFAULT-POLICY-DEFAULT
    path_groups:
    - name: internet
    - name: mpls
    - name: LAN_HA
  tcp_mss_ceiling:
    ipv4_segment_size: auto
router_traffic_engineering:
  enabled: true
service_routing_protocols_model: multi-agent
spanning_tree:
  mode: none
static_routes:
- vrf: MGMT
  destination_address_prefix: 0.0.0.0/0
  gateway: 172.16.1.1
- destination_address_prefix: 172.18.0.0/16
  gateway: 172.18.4.1
- destination_address_prefix: 100.64.0.0/16
  gateway: 100.64.4.1
stun:
  client:
    server_profiles:
    - name: mpls-dc1-leaf1a-Ethernet6
      ip_address: 172.18.1.2
      ssl_profile: STUN-DTLS
    - name: mpls-dc1-leaf1b-Ethernet6
      ip_address: 172.18.2.2
      ssl_profile: STUN-DTLS
    - name: internet-dc1-leaf1a-Ethernet7
      ip_address: 100.64.1.2
      ssl_profile: STUN-DTLS
    - name: internet-dc1-leaf1b-Ethernet7
      ip_address: 100.64.2.2
      ssl_profile: STUN-DTLS
transceiver_qsfp_default_mode_4x10: false
vrfs:
- name: MGMT
  ip_routing: false
vxlan_interface:
  vxlan1:
    description: dc1-wan2_VTEP
    vxlan:
      source_interface: Dps1
      udp_port: 4789
      vrfs:
      - name: default
        vni: 1
