aaa_root:
  disabled: true
config_end: true
dns_domain: dc1.local
enable_password:
  disabled: true
ethernet_interfaces:
- name: Ethernet1
  description: P2P_dc1-leaf1a_Ethernet1
  shutdown: false
  mtu: 1500
  ip_address: 10.255.255.0/31
  peer: dc1-leaf1a
  peer_interface: Ethernet1
  peer_type: l3leaf
  switchport:
    enabled: false
- name: Ethernet2
  description: P2P_dc1-leaf1b_Ethernet1
  shutdown: false
  mtu: 1500
  ip_address: 10.255.255.4/31
  peer: dc1-leaf1b
  peer_interface: Ethernet1
  peer_type: l3leaf
  switchport:
    enabled: false
- name: Ethernet3
  description: P2P_dc1-leaf2a_Ethernet1
  shutdown: false
  mtu: 1500
  ip_address: 10.255.255.8/31
  peer: dc1-leaf2a
  peer_interface: Ethernet1
  peer_type: l3leaf
  switchport:
    enabled: false
- name: Ethernet4
  description: P2P_dc1-leaf2b_Ethernet1
  shutdown: true
  mtu: 1500
  ip_address: 10.255.255.12/31
  peer: dc1-leaf2b
  peer_interface: Ethernet1
  peer_type: l3leaf
  switchport:
    enabled: false
- name: Ethernet5
  description: P2P_dc1-svc-leaf1a_Ethernet1
  shutdown: false
  mtu: 1500
  ip_address: 10.33.255.16/31
  peer: dc1-svc-leaf1a
  peer_interface: Ethernet1
  peer_type: service_leaf
  switchport:
    enabled: false
- name: Ethernet6
  description: P2P_dc1-svc-leaf1b_Ethernet1
  shutdown: false
  mtu: 1500
  ip_address: 10.33.255.20/31
  peer: dc1-svc-leaf1b
  peer_interface: Ethernet1
  peer_type: service_leaf
  switchport:
    enabled: false
hostname: dc1-spine1
ip_routing: true
is_deployed: true
local_users:
- name: admin
  privilege: 15
  role: network-admin
  no_password: true
- name: ansible
  privilege: 15
  role: network-admin
  sha512_password: $6$7u4j1rkb3VELgcZE$EJt2Qff8kd/TapRoci0XaIZsL4tFzgq1YZBLD9c6f/knXzvcYY0NcMKndZeCv0T268knGKhOEwZAxqKjlMm920
loopback_interfaces:
- name: Loopback0
  description: ROUTER_ID
  shutdown: false
  ip_address: 10.255.0.1/32
management_api_http:
  enable_https: true
  https_ssl_profile: eAPI_SSL_Profile
  enable_vrfs:
  - name: MGMT
management_interfaces:
- name: Management1
  description: OOB_MANAGEMENT
  shutdown: false
  vrf: MGMT
  ip_address: 172.16.1.11/24
  type: oob
  gateway: 172.16.1.1
metadata:
  platform: vEOS-lab
prefix_lists:
- name: PL-LOOPBACKS-EVPN-OVERLAY
  sequence_numbers:
  - sequence: 10
    action: permit 10.255.0.0/27 eq 32
route_maps:
- name: RM-CONN-2-BGP
  sequence_numbers:
  - sequence: 10
    type: permit
    match:
    - ip address prefix-list PL-LOOPBACKS-EVPN-OVERLAY
router_bfd:
  multihop:
    interval: 300
    min_rx: 300
    multiplier: 3
router_bgp:
  as: '65100'
  router_id: 10.255.0.1
  maximum_paths:
    paths: 4
    ecmp: 4
  bgp:
    default:
      ipv4_unicast: false
  peer_groups:
  - name: IPv4-UNDERLAY-PEERS
    type: ipv4
    password: 7x4B4rnJhZB438m9+BrBfQ==
    send_community: all
    maximum_routes: 12000
  - name: EVPN-OVERLAY-PEERS
    type: evpn
    next_hop_unchanged: true
    update_source: Loopback0
    bfd: true
    ebgp_multihop: 3
    password: Q4fqtbqcZ7oQuKfuWtNGRQ==
    send_community: all
    maximum_routes: 0
  neighbors:
  - ip_address: 10.255.255.1
    peer_group: IPv4-UNDERLAY-PEERS
    remote_as: '65101'
    peer: dc1-leaf1a
    description: dc1-leaf1a_Ethernet1
  - ip_address: 10.255.255.5
    peer_group: IPv4-UNDERLAY-PEERS
    remote_as: '65101'
    peer: dc1-leaf1b
    description: dc1-leaf1b_Ethernet1
  - ip_address: 10.255.255.9
    peer_group: IPv4-UNDERLAY-PEERS
    remote_as: '65102'
    peer: dc1-leaf2a
    description: dc1-leaf2a_Ethernet1
  - ip_address: 10.255.255.13
    peer_group: IPv4-UNDERLAY-PEERS
    remote_as: '65102'
    peer: dc1-leaf2b
    description: dc1-leaf2b_Ethernet1
    shutdown: true
  - ip_address: 10.33.255.17
    peer_group: IPv4-UNDERLAY-PEERS
    remote_as: '65133'
    peer: dc1-svc-leaf1a
    description: dc1-svc-leaf1a_Ethernet1
  - ip_address: 10.33.255.21
    peer_group: IPv4-UNDERLAY-PEERS
    remote_as: '65133'
    peer: dc1-svc-leaf1b
    description: dc1-svc-leaf1b_Ethernet1
  - ip_address: 10.255.0.3
    peer_group: EVPN-OVERLAY-PEERS
    remote_as: '65101'
    peer: dc1-leaf1a
    description: dc1-leaf1a_Loopback0
  - ip_address: 10.255.0.4
    peer_group: EVPN-OVERLAY-PEERS
    remote_as: '65101'
    peer: dc1-leaf1b
    description: dc1-leaf1b_Loopback0
  - ip_address: 10.255.0.5
    peer_group: EVPN-OVERLAY-PEERS
    remote_as: '65102'
    peer: dc1-leaf2a
    description: dc1-leaf2a_Loopback0
  - ip_address: 10.255.0.6
    peer_group: EVPN-OVERLAY-PEERS
    remote_as: '65102'
    peer: dc1-leaf2b
    description: dc1-leaf2b_Loopback0
    shutdown: true
  - ip_address: 10.33.0.5
    peer_group: EVPN-OVERLAY-PEERS
    remote_as: '65133'
    peer: dc1-svc-leaf1a
    description: dc1-svc-leaf1a_Loopback0
  - ip_address: 10.33.0.6
    peer_group: EVPN-OVERLAY-PEERS
    remote_as: '65133'
    peer: dc1-svc-leaf1b
    description: dc1-svc-leaf1b_Loopback0
  - ip_address: 123.1.1.10
    remote_as: '1234'
    local_as: '123'
    description: External IPv4 BGP peer
    password: oBztv71m2uhR7hh58/OCNA==
    update_source: Loopback123
    route_map_in: RM-123-1-1-10-IN
    route_map_out: RM-Tenant_A_WAN_Zone-123.1.1.10-SET-NEXT-HOP-OUT
    default_originate:
      always: false
      route_map: RM-Tenant_A_WAN_Zone-123.1.1.10-SET-NEXT-HOP-OUT
    send_community: standard extended
    maximum_routes: 0
    ebgp_multihop: 3
  - ip_address: 123.1.1.11
    remote_as: '1234'
    local_as: '123'
    description: External IPv4 BGP peer
    password: oBztv71m2uhR7hh58/OCNA==
    update_source: Loopback123
    route_map_in: RM-123-1-1-11-IN
    route_map_out: RM-123-1-1-11-OUT
    default_originate:
      always: false
    send_community: standard extended
    maximum_routes: 0
    ebgp_multihop: 3
  - ip_address: fd5a:fe45:8831:06c5::a
    remote_as: '12345'
    route_map_out: RM-Tenant_A_WAN_Zone-fd5a:fe45:8831:06c5::a-SET-NEXT-HOP-OUT
    send_community: all
  - ip_address: fd5a:fe45:8831:06c5::b
    remote_as: '12345'
  redistribute:
    connected:
      enabled: true
      route_map: RM-CONN-2-BGP
  address_family_evpn:
    peer_groups:
    - name: EVPN-OVERLAY-PEERS
      activate: true
  address_family_ipv4:
    peer_groups:
    - name: IPv4-UNDERLAY-PEERS
      activate: true
    - name: EVPN-OVERLAY-PEERS
      activate: false
    neighbors:
    - ip_address: 123.1.1.10
      activate: true
    - ip_address: 123.1.1.11
      activate: true
  address_family_ipv6:
    neighbors:
    - ip_address: fd5a:fe45:8831:06c5::a
      activate: true
    - ip_address: fd5a:fe45:8831:06c5::b
      activate: true
service_routing_protocols_model: multi-agent
spanning_tree:
  mode: none
static_routes:
- vrf: MGMT
  destination_address_prefix: 0.0.0.0/0
  gateway: 172.16.1.1
transceiver_qsfp_default_mode_4x10: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vrfs:
- name: MGMT
  ip_routing: false
